// Generated by AshTypescript - RPC Actions
// Do not edit this file manually


import type { AccountsOrgFilterInput, AccountsOrgResourceSchema, AccountsOrgSortField, AshRpcError, BillingSubscriptionFilterInput, BillingSubscriptionResourceSchema, BillingSubscriptionSortField, ConditionalPaginatedResultMixed, InferResult, MarketplaceProviderFilterInput, MarketplaceProviderResourceSchema, MarketplaceProviderSortField, SortString, UnifiedFieldSelection, UtcDateTime } from "./ash_types";
export type * from "./ash_types";

// Helper Functions

/**
 * Configuration options for action RPC requests
 */
export interface ActionConfig {
  // Request data
  input?: Record<string, any> | undefined;
  identity?: any;
  fields?: Array<string | Record<string, any>> | undefined; // Field selection
  filter?: Record<string, any> | undefined; // Filter options (for reads)
  sort?: string | string[] | undefined; // Sort options
  page?:
    | {
        // Offset-based pagination
        limit?: number;
        offset?: number;
        count?: boolean;
      }
    | {
        // Keyset pagination
        limit?: number;
        after?: string;
        before?: string;
      }
    | undefined;

  // Metadata
  metadataFields?: ReadonlyArray<string> | undefined;

  // HTTP customization
  headers?: Record<string, string> | undefined; // Custom headers
  fetchOptions?: RequestInit | undefined; // Fetch options (signal, cache, etc.)
  customFetch?: ((
    input: RequestInfo | URL,
    init?: RequestInit,
  ) => Promise<Response>) | undefined;

  // Multitenancy
  tenant?: string | undefined; // Tenant parameter

  // Hook context
  hookCtx?: Record<string, any> | undefined;
}




/**
 * Gets the CSRF token from the page's meta tag
 * Returns null if no CSRF token is found
 */
export function getPhoenixCSRFToken(): string | null {
  return document
    ?.querySelector("meta[name='csrf-token']")
    ?.getAttribute("content") || null;
}

/**
 * Builds headers object with CSRF token for Phoenix applications
 * Returns headers object with X-CSRF-Token (if available)
 */
export function buildCSRFHeaders(headers: Record<string, string> = {}): Record<string, string> {
  const csrfToken = getPhoenixCSRFToken();
  if (csrfToken) {
    headers["X-CSRF-Token"] = csrfToken;
  }

  return headers;
}

/**
 * Internal helper function for making action RPC requests
 * Handles hooks, request configuration, fetch execution, and error handling
 * @param config Configuration matching ActionConfig
 */
export async function executeActionRpcRequest<T>(
  payload: Record<string, any>,
  config: ActionConfig
): Promise<T> {
    const processedConfig = config;

  const headers: Record<string, string> = {
    "Content-Type": "application/json",
    ...processedConfig.headers,
    ...config.headers,
  };

  const fetchFunction = config.customFetch || processedConfig.customFetch || fetch;
  const fetchOptions: RequestInit = {
    ...processedConfig.fetchOptions,
    ...config.fetchOptions,
    method: "POST",
    headers,
    body: JSON.stringify(payload),
  };

  const response = await fetchFunction("/internal-api/rpc/run", fetchOptions);
  const result = response.ok ? await response.json() : null;


  if (!response.ok) {
    return {
      success: false,
      errors: [
        {
          type: "network_error",
          message: `Network request failed: ${response.statusText}`,
          shortMessage: "Network error",
          vars: { statusCode: response.status, statusText: response.statusText },
          fields: [],
          path: [],
          details: { statusCode: response.status }
        }
      ],
    } as T;
  }

  return result as T;
}









export type ListAccountsOrgsFields = UnifiedFieldSelection<AccountsOrgResourceSchema>[];


export type InferListAccountsOrgsResult<
  Fields extends ListAccountsOrgsFields | undefined,
  Page extends ListAccountsOrgsConfig["page"] = undefined
> = ConditionalPaginatedResultMixed<Page, Array<InferResult<AccountsOrgResourceSchema, Fields>>, {
  results: Array<InferResult<AccountsOrgResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  offset: number;
  count?: number | null;
  type: "offset";
}, {
  results: Array<InferResult<AccountsOrgResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  after: string | null;
  before: string | null;
  previousPage: string | null;
  nextPage: string | null;
  count?: number | null;
  type: "keyset";
}>;

export type ListAccountsOrgsConfig = {
  tenant?: string;
  fields: ListAccountsOrgsFields;
  filter?: AccountsOrgFilterInput;
  sort?: SortString<AccountsOrgSortField> | SortString<AccountsOrgSortField>[];
  page?: (
    {
      limit?: number;
      offset?: number;
      count?: boolean;
    } | {
      limit?: number;
      after?: string;
      before?: string;
    }
  );
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
};

export type ListAccountsOrgsResult<Fields extends ListAccountsOrgsFields, Page extends ListAccountsOrgsConfig["page"] = undefined> = | { success: true; data: InferListAccountsOrgsResult<Fields, Page>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read Org records
 *
 * @ashActionType :read
 */
export async function listAccountsOrgs<Fields extends ListAccountsOrgsFields, Config extends ListAccountsOrgsConfig = ListAccountsOrgsConfig>(
  config: Config & { fields: Fields }
): Promise<ListAccountsOrgsResult<Fields, Config["page"]>> {
  const payload = {
    action: "list_accounts_orgs",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: Array.isArray(config.sort) ? config.sort.join(",") : config.sort }),
    ...(config.page && { page: config.page })
  };

  return executeActionRpcRequest<ListAccountsOrgsResult<Fields, Config["page"]>>(
    payload,
    config
  );
}


export type ListBillingSubscriptionsFields = UnifiedFieldSelection<BillingSubscriptionResourceSchema>[];


export type InferListBillingSubscriptionsResult<
  Fields extends ListBillingSubscriptionsFields | undefined,
  Page extends ListBillingSubscriptionsConfig["page"] = undefined
> = ConditionalPaginatedResultMixed<Page, Array<InferResult<BillingSubscriptionResourceSchema, Fields>>, {
  results: Array<InferResult<BillingSubscriptionResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  offset: number;
  count?: number | null;
  type: "offset";
}, {
  results: Array<InferResult<BillingSubscriptionResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  after: string | null;
  before: string | null;
  previousPage: string | null;
  nextPage: string | null;
  count?: number | null;
  type: "keyset";
}>;

export type ListBillingSubscriptionsConfig = {
  tenant?: string;
  fields: ListBillingSubscriptionsFields;
  filter?: BillingSubscriptionFilterInput;
  sort?: SortString<BillingSubscriptionSortField> | SortString<BillingSubscriptionSortField>[];
  page?: (
    {
      limit?: number;
      offset?: number;
      count?: boolean;
    } | {
      limit?: number;
      after?: string;
      before?: string;
    }
  );
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
};

export type ListBillingSubscriptionsResult<Fields extends ListBillingSubscriptionsFields, Page extends ListBillingSubscriptionsConfig["page"] = undefined> = | { success: true; data: InferListBillingSubscriptionsResult<Fields, Page>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read Subscription records
 *
 * @ashActionType :read
 */
export async function listBillingSubscriptions<Fields extends ListBillingSubscriptionsFields, Config extends ListBillingSubscriptionsConfig = ListBillingSubscriptionsConfig>(
  config: Config & { fields: Fields }
): Promise<ListBillingSubscriptionsResult<Fields, Config["page"]>> {
  const payload = {
    action: "list_billing_subscriptions",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: Array.isArray(config.sort) ? config.sort.join(",") : config.sort }),
    ...(config.page && { page: config.page })
  };

  return executeActionRpcRequest<ListBillingSubscriptionsResult<Fields, Config["page"]>>(
    payload,
    config
  );
}


export type ListMarketplaceProvidersFields = UnifiedFieldSelection<MarketplaceProviderResourceSchema>[];


export type InferListMarketplaceProvidersResult<
  Fields extends ListMarketplaceProvidersFields | undefined,
  Page extends ListMarketplaceProvidersConfig["page"] = undefined
> = ConditionalPaginatedResultMixed<Page, Array<InferResult<MarketplaceProviderResourceSchema, Fields>>, {
  results: Array<InferResult<MarketplaceProviderResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  offset: number;
  count?: number | null;
  type: "offset";
}, {
  results: Array<InferResult<MarketplaceProviderResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  after: string | null;
  before: string | null;
  previousPage: string | null;
  nextPage: string | null;
  count?: number | null;
  type: "keyset";
}>;

export type ListMarketplaceProvidersConfig = {
  tenant?: string;
  fields: ListMarketplaceProvidersFields;
  filter?: MarketplaceProviderFilterInput;
  sort?: SortString<MarketplaceProviderSortField> | SortString<MarketplaceProviderSortField>[];
  page?: (
    {
      limit?: number;
      offset?: number;
      count?: boolean;
    } | {
      limit?: number;
      after?: string;
      before?: string;
    }
  );
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
};

export type ListMarketplaceProvidersResult<Fields extends ListMarketplaceProvidersFields, Page extends ListMarketplaceProvidersConfig["page"] = undefined> = | { success: true; data: InferListMarketplaceProvidersResult<Fields, Page>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read Provider records
 *
 * @ashActionType :read
 */
export async function listMarketplaceProviders<Fields extends ListMarketplaceProvidersFields, Config extends ListMarketplaceProvidersConfig = ListMarketplaceProvidersConfig>(
  config: Config & { fields: Fields }
): Promise<ListMarketplaceProvidersResult<Fields, Config["page"]>> {
  const payload = {
    action: "list_marketplace_providers",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: Array.isArray(config.sort) ? config.sort.join(",") : config.sort }),
    ...(config.page && { page: config.page })
  };

  return executeActionRpcRequest<ListMarketplaceProvidersResult<Fields, Config["page"]>>(
    payload,
    config
  );
}


export type MeasureProjectInput = {
  subjectSha: string;
  since: UtcDateTime;
  until: UtcDateTime;
};

export type InferMeasureProjectResult = Record<string, any>;

export type MeasureProjectResult = | { success: true; data: InferMeasureProjectResult; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Execute generic action on Measurement
 *
 * @ashActionType :action
 */
export async function measureProject(
  config: {
  tenant?: string;
  input: MeasureProjectInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<MeasureProjectResult> {
  const payload = {
    action: "measure_project",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeActionRpcRequest<MeasureProjectResult>(
    payload,
    config
  );
}

