PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX schema: <https://schema.org/>
PREFIX xl: <https://ggen.io/ontology/xaas-library#>

SELECT ?checkoutClass WHERE {
  xl:Checkout a ?type ;
              rdfs:subClassOf schema:BorrowAction, prov:Activity .
  BIND(xl:Checkout AS ?checkoutClass)
}
