PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX schema: <https://schema.org/>
PREFIX xl: <https://ggen.io/ontology/xaas-library#>

SELECT ?curationClass WHERE {
  xl:Curation a ?type ;
              rdfs:subClassOf schema:Collection, prov:Entity .
  BIND(xl:Curation AS ?curationClass)
}
