PREFIX agp: <https://ggen.io/ontology/ash-igniter-gen-pipeline#>

SELECT ?target ?order ?mixTask ?targetModule ?domainModule ?resourceModule ?mixArgs WHERE {
  ?target a agp:CodegenTarget ;
          agp:phase "core" ;
          agp:order ?order ;
          agp:mixTask ?mixTask ;
          agp:targetModule ?targetModule ;
          agp:domainModule ?domainModule ;
          agp:resourceModule ?resourceModule ;
          agp:mixArgs ?mixArgs .
}
ORDER BY ?order
