// @generated by AshSurface.Projector.Expo (CalVer 26.10.1)
// Explicit authority boundaries and semantic identities for machine discoverability.

export const ACTIONS = Object.freeze([
  {
    "action": "create",
    "authorityBoundary": null,
    "doAuthority": null,
    "evidenceRequired": true,
    "id": "Xaas.Conference.Attendee#create",
    "possibleRefusals": [
      "REFUSED_AUTHORITY_CEILING",
      "REFUSED_VALIDATION",
      "REFUSED_NOT_FOUND"
    ],
    "profile": {
      "evidenceRequired": true,
      "possibleRefusals": [
        "REFUSED_AUTHORITY_CEILING",
        "REFUSED_VALIDATION",
        "REFUSED_NOT_FOUND"
      ]
    },
    "receiptRequired": null,
    "resource": "Xaas.Conference.Attendee",
    "semanticId": null
  },
  {
    "action": "destroy",
    "authorityBoundary": null,
    "doAuthority": null,
    "evidenceRequired": true,
    "id": "Xaas.Conference.Attendee#destroy",
    "possibleRefusals": [
      "REFUSED_AUTHORITY_CEILING",
      "REFUSED_NOT_FOUND"
    ],
    "profile": {
      "evidenceRequired": true,
      "possibleRefusals": [
        "REFUSED_AUTHORITY_CEILING",
        "REFUSED_NOT_FOUND"
      ]
    },
    "receiptRequired": null,
    "resource": "Xaas.Conference.Attendee",
    "semanticId": null
  },
  {
    "action": "read",
    "authorityBoundary": null,
    "doAuthority": null,
    "evidenceRequired": true,
    "id": "Xaas.Conference.Attendee#read",
    "possibleRefusals": [
      "REFUSED_AUTHORITY_CEILING",
      "REFUSED_NOT_FOUND"
    ],
    "profile": {
      "evidenceRequired": true,
      "possibleRefusals": [
        "REFUSED_AUTHORITY_CEILING",
        "REFUSED_NOT_FOUND"
      ]
    },
    "receiptRequired": null,
    "resource": "Xaas.Conference.Attendee",
    "semanticId": null
  },
  {
    "action": "create",
    "authorityBoundary": null,
    "doAuthority": null,
    "evidenceRequired": true,
    "id": "Xaas.Conference.Event#create",
    "possibleRefusals": [
      "REFUSED_AUTHORITY_CEILING",
      "REFUSED_VALIDATION",
      "REFUSED_NOT_FOUND"
    ],
    "profile": {
      "evidenceRequired": true,
      "possibleRefusals": [
        "REFUSED_AUTHORITY_CEILING",
        "REFUSED_VALIDATION",
        "REFUSED_NOT_FOUND"
      ]
    },
    "receiptRequired": null,
    "resource": "Xaas.Conference.Event",
    "semanticId": null
  },
  {
    "action": "destroy",
    "authorityBoundary": null,
    "doAuthority": null,
    "evidenceRequired": true,
    "id": "Xaas.Conference.Event#destroy",
    "possibleRefusals": [
      "REFUSED_AUTHORITY_CEILING",
      "REFUSED_NOT_FOUND"
    ],
    "profile": {
      "evidenceRequired": true,
      "possibleRefusals": [
        "REFUSED_AUTHORITY_CEILING",
        "REFUSED_NOT_FOUND"
      ]
    },
    "receiptRequired": null,
    "resource": "Xaas.Conference.Event",
    "semanticId": null
  },
  {
    "action": "read",
    "authorityBoundary": null,
    "doAuthority": null,
    "evidenceRequired": true,
    "id": "Xaas.Conference.Event#read",
    "possibleRefusals": [
      "REFUSED_AUTHORITY_CEILING",
      "REFUSED_NOT_FOUND"
    ],
    "profile": {
      "evidenceRequired": true,
      "possibleRefusals": [
        "REFUSED_AUTHORITY_CEILING",
        "REFUSED_NOT_FOUND"
      ]
    },
    "receiptRequired": null,
    "resource": "Xaas.Conference.Event",
    "semanticId": null
  },
  {
    "action": "create",
    "authorityBoundary": null,
    "doAuthority": null,
    "evidenceRequired": true,
    "id": "Xaas.Conference.Registration#create",
    "possibleRefusals": [
      "REFUSED_AUTHORITY_CEILING",
      "REFUSED_VALIDATION",
      "REFUSED_NOT_FOUND"
    ],
    "profile": {
      "evidenceRequired": true,
      "possibleRefusals": [
        "REFUSED_AUTHORITY_CEILING",
        "REFUSED_VALIDATION",
        "REFUSED_NOT_FOUND"
      ]
    },
    "receiptRequired": null,
    "resource": "Xaas.Conference.Registration",
    "semanticId": null
  },
  {
    "action": "destroy",
    "authorityBoundary": null,
    "doAuthority": null,
    "evidenceRequired": true,
    "id": "Xaas.Conference.Registration#destroy",
    "possibleRefusals": [
      "REFUSED_AUTHORITY_CEILING",
      "REFUSED_NOT_FOUND"
    ],
    "profile": {
      "evidenceRequired": true,
      "possibleRefusals": [
        "REFUSED_AUTHORITY_CEILING",
        "REFUSED_NOT_FOUND"
      ]
    },
    "receiptRequired": null,
    "resource": "Xaas.Conference.Registration",
    "semanticId": null
  },
  {
    "action": "read",
    "authorityBoundary": null,
    "doAuthority": null,
    "evidenceRequired": true,
    "id": "Xaas.Conference.Registration#read",
    "possibleRefusals": [
      "REFUSED_AUTHORITY_CEILING",
      "REFUSED_NOT_FOUND"
    ],
    "profile": {
      "evidenceRequired": true,
      "possibleRefusals": [
        "REFUSED_AUTHORITY_CEILING",
        "REFUSED_NOT_FOUND"
      ]
    },
    "receiptRequired": null,
    "resource": "Xaas.Conference.Registration",
    "semanticId": null
  },
  {
    "action": "update",
    "authorityBoundary": null,
    "doAuthority": null,
    "evidenceRequired": true,
    "id": "Xaas.Conference.Registration#update",
    "possibleRefusals": [
      "REFUSED_AUTHORITY_CEILING",
      "REFUSED_VALIDATION",
      "REFUSED_NOT_FOUND"
    ],
    "profile": {
      "evidenceRequired": true,
      "possibleRefusals": [
        "REFUSED_AUTHORITY_CEILING",
        "REFUSED_VALIDATION",
        "REFUSED_NOT_FOUND"
      ]
    },
    "receiptRequired": null,
    "resource": "Xaas.Conference.Registration",
    "semanticId": null
  },
  {
    "action": "create",
    "authorityBoundary": null,
    "doAuthority": null,
    "evidenceRequired": true,
    "id": "Xaas.Conference.Session#create",
    "possibleRefusals": [
      "REFUSED_AUTHORITY_CEILING",
      "REFUSED_VALIDATION",
      "REFUSED_NOT_FOUND"
    ],
    "profile": {
      "evidenceRequired": true,
      "possibleRefusals": [
        "REFUSED_AUTHORITY_CEILING",
        "REFUSED_VALIDATION",
        "REFUSED_NOT_FOUND"
      ]
    },
    "receiptRequired": null,
    "resource": "Xaas.Conference.Session",
    "semanticId": null
  },
  {
    "action": "destroy",
    "authorityBoundary": null,
    "doAuthority": null,
    "evidenceRequired": true,
    "id": "Xaas.Conference.Session#destroy",
    "possibleRefusals": [
      "REFUSED_AUTHORITY_CEILING",
      "REFUSED_NOT_FOUND"
    ],
    "profile": {
      "evidenceRequired": true,
      "possibleRefusals": [
        "REFUSED_AUTHORITY_CEILING",
        "REFUSED_NOT_FOUND"
      ]
    },
    "receiptRequired": null,
    "resource": "Xaas.Conference.Session",
    "semanticId": null
  },
  {
    "action": "read",
    "authorityBoundary": null,
    "doAuthority": null,
    "evidenceRequired": true,
    "id": "Xaas.Conference.Session#read",
    "possibleRefusals": [
      "REFUSED_AUTHORITY_CEILING",
      "REFUSED_NOT_FOUND"
    ],
    "profile": {
      "evidenceRequired": true,
      "possibleRefusals": [
        "REFUSED_AUTHORITY_CEILING",
        "REFUSED_NOT_FOUND"
      ]
    },
    "receiptRequired": null,
    "resource": "Xaas.Conference.Session",
    "semanticId": null
  },
  {
    "action": "create",
    "authorityBoundary": null,
    "doAuthority": null,
    "evidenceRequired": true,
    "id": "Xaas.Conference.Speaker#create",
    "possibleRefusals": [
      "REFUSED_AUTHORITY_CEILING",
      "REFUSED_VALIDATION",
      "REFUSED_NOT_FOUND"
    ],
    "profile": {
      "evidenceRequired": true,
      "possibleRefusals": [
        "REFUSED_AUTHORITY_CEILING",
        "REFUSED_VALIDATION",
        "REFUSED_NOT_FOUND"
      ]
    },
    "receiptRequired": null,
    "resource": "Xaas.Conference.Speaker",
    "semanticId": null
  },
  {
    "action": "destroy",
    "authorityBoundary": null,
    "doAuthority": null,
    "evidenceRequired": true,
    "id": "Xaas.Conference.Speaker#destroy",
    "possibleRefusals": [
      "REFUSED_AUTHORITY_CEILING",
      "REFUSED_NOT_FOUND"
    ],
    "profile": {
      "evidenceRequired": true,
      "possibleRefusals": [
        "REFUSED_AUTHORITY_CEILING",
        "REFUSED_NOT_FOUND"
      ]
    },
    "receiptRequired": null,
    "resource": "Xaas.Conference.Speaker",
    "semanticId": null
  },
  {
    "action": "read",
    "authorityBoundary": null,
    "doAuthority": null,
    "evidenceRequired": true,
    "id": "Xaas.Conference.Speaker#read",
    "possibleRefusals": [
      "REFUSED_AUTHORITY_CEILING",
      "REFUSED_NOT_FOUND"
    ],
    "profile": {
      "evidenceRequired": true,
      "possibleRefusals": [
        "REFUSED_AUTHORITY_CEILING",
        "REFUSED_NOT_FOUND"
      ]
    },
    "receiptRequired": null,
    "resource": "Xaas.Conference.Speaker",
    "semanticId": null
  },
  {
    "action": "create",
    "authorityBoundary": null,
    "doAuthority": null,
    "evidenceRequired": true,
    "id": "Xaas.Conference.Sponsor#create",
    "possibleRefusals": [
      "REFUSED_AUTHORITY_CEILING",
      "REFUSED_VALIDATION",
      "REFUSED_NOT_FOUND"
    ],
    "profile": {
      "evidenceRequired": true,
      "possibleRefusals": [
        "REFUSED_AUTHORITY_CEILING",
        "REFUSED_VALIDATION",
        "REFUSED_NOT_FOUND"
      ]
    },
    "receiptRequired": null,
    "resource": "Xaas.Conference.Sponsor",
    "semanticId": null
  },
  {
    "action": "destroy",
    "authorityBoundary": null,
    "doAuthority": null,
    "evidenceRequired": true,
    "id": "Xaas.Conference.Sponsor#destroy",
    "possibleRefusals": [
      "REFUSED_AUTHORITY_CEILING",
      "REFUSED_NOT_FOUND"
    ],
    "profile": {
      "evidenceRequired": true,
      "possibleRefusals": [
        "REFUSED_AUTHORITY_CEILING",
        "REFUSED_NOT_FOUND"
      ]
    },
    "receiptRequired": null,
    "resource": "Xaas.Conference.Sponsor",
    "semanticId": null
  },
  {
    "action": "read",
    "authorityBoundary": null,
    "doAuthority": null,
    "evidenceRequired": true,
    "id": "Xaas.Conference.Sponsor#read",
    "possibleRefusals": [
      "REFUSED_AUTHORITY_CEILING",
      "REFUSED_NOT_FOUND"
    ],
    "profile": {
      "evidenceRequired": true,
      "possibleRefusals": [
        "REFUSED_AUTHORITY_CEILING",
        "REFUSED_NOT_FOUND"
      ]
    },
    "receiptRequired": null,
    "resource": "Xaas.Conference.Sponsor",
    "semanticId": null
  },
  {
    "action": "create",
    "authorityBoundary": null,
    "doAuthority": null,
    "evidenceRequired": true,
    "id": "Xaas.Conference.Track#create",
    "possibleRefusals": [
      "REFUSED_AUTHORITY_CEILING",
      "REFUSED_VALIDATION",
      "REFUSED_NOT_FOUND"
    ],
    "profile": {
      "evidenceRequired": true,
      "possibleRefusals": [
        "REFUSED_AUTHORITY_CEILING",
        "REFUSED_VALIDATION",
        "REFUSED_NOT_FOUND"
      ]
    },
    "receiptRequired": null,
    "resource": "Xaas.Conference.Track",
    "semanticId": null
  },
  {
    "action": "destroy",
    "authorityBoundary": null,
    "doAuthority": null,
    "evidenceRequired": true,
    "id": "Xaas.Conference.Track#destroy",
    "possibleRefusals": [
      "REFUSED_AUTHORITY_CEILING",
      "REFUSED_NOT_FOUND"
    ],
    "profile": {
      "evidenceRequired": true,
      "possibleRefusals": [
        "REFUSED_AUTHORITY_CEILING",
        "REFUSED_NOT_FOUND"
      ]
    },
    "receiptRequired": null,
    "resource": "Xaas.Conference.Track",
    "semanticId": null
  },
  {
    "action": "read",
    "authorityBoundary": null,
    "doAuthority": null,
    "evidenceRequired": true,
    "id": "Xaas.Conference.Track#read",
    "possibleRefusals": [
      "REFUSED_AUTHORITY_CEILING",
      "REFUSED_NOT_FOUND"
    ],
    "profile": {
      "evidenceRequired": true,
      "possibleRefusals": [
        "REFUSED_AUTHORITY_CEILING",
        "REFUSED_NOT_FOUND"
      ]
    },
    "receiptRequired": null,
    "resource": "Xaas.Conference.Track",
    "semanticId": null
  }
]);

export function getAction(id) {
  return ACTIONS.find((a) => a.id === id) ?? null;
}

export function hasDoAuthority(id) {
  const action = getAction(id);
  return action ? action.doAuthority === true : false;
}

export function getAuthorityBoundary(id) {
  const action = getAction(id);
  return action ? action.authorityBoundary : null;
}
