// @generated by AshSurface.Projector.Expo (CalVer 26.10.1)
// Complete, executable client manufactured with pre-bound Zod boundary schemas.

import { createClient } from "ash_surface";
import { SCHEMAS } from "./zoela_surface.schemas.mjs";
import { ACTIONS } from "./zoela_surface.actions.mjs";

// The server owns reconcile classification; the client only observes it.
// Anything it cannot observe within the deadline, or cannot read as one of
// these statuses, stays STILL_UNKNOWN - never invented, never upgraded.
const RECONCILE_STATUSES = ["COMPLETED", "NOT_OBSERVED", "STILL_UNKNOWN"];

export function createZoelaClient({ contract, transports = {}, prefer = "http", reconcileEndpoint, reconcileTimeoutMs = 10000 }) {
  const client = createClient({
    contract,
    transports,
    prefer,
    schemas: SCHEMAS,
  });

  return Object.freeze({
    ...client,
    actionsMetadata: ACTIONS,
    async reconcile(commandId) {
      if (!reconcileEndpoint) {
        throw new Error("No reconcileEndpoint configured on client");
      }
      const controller = new AbortController();
      const timer = setTimeout(() => controller.abort(), reconcileTimeoutMs);
      try {
        const res = await fetch(`${reconcileEndpoint}?commandId=${encodeURIComponent(commandId)}`, { signal: controller.signal });
        if (!res.ok) return { status: "STILL_UNKNOWN" };
        const body = await res.json();
        return RECONCILE_STATUSES.includes(body?.status) ? body : { status: "STILL_UNKNOWN" };
      } catch {
        return { status: "STILL_UNKNOWN" };
      } finally {
        clearTimeout(timer);
      }
    }
  });
}
