// @generated by AshSurface.Projector.Expo (CalVer 26.10.1)
// Do not edit directly; modify authoritative Ash resources or ontology instead.

import { z } from "zod";

export const Xaas_Conference_Attendee_create_inputSchema = z.object({
  affiliation: z.string(),
  email: z.string(),
  id: z.string().uuid(),
  name: z.string()
}).passthrough();

export const Xaas_Conference_Attendee_create_outputSchema = z.object({
  success: z.boolean(),
  data: z.record(z.string(), z.unknown()).optional(),
  receiptRef: z.string().optional(),
  error: z.string().optional()
}).passthrough();


export const Xaas_Conference_Attendee_destroy_inputSchema = z.object({
  affiliation: z.string(),
  email: z.string(),
  id: z.string().uuid(),
  name: z.string()
}).passthrough();

export const Xaas_Conference_Attendee_destroy_outputSchema = z.object({
  success: z.boolean(),
  data: z.record(z.string(), z.unknown()).optional(),
  receiptRef: z.string().optional(),
  error: z.string().optional()
}).passthrough();


export const Xaas_Conference_Attendee_read_inputSchema = z.object({
  affiliation: z.string(),
  email: z.string(),
  id: z.string().uuid(),
  name: z.string()
}).passthrough();

export const Xaas_Conference_Attendee_read_outputSchema = z.object({
  success: z.boolean(),
  data: z.record(z.string(), z.unknown()).optional(),
  receiptRef: z.string().optional(),
  error: z.string().optional()
}).passthrough();


export const Xaas_Conference_Event_create_inputSchema = z.object({
  ends_at: z.string(),
  id: z.string().uuid(),
  location: z.string(),
  name: z.string(),
  slug: z.string(),
  starts_at: z.string()
}).passthrough();

export const Xaas_Conference_Event_create_outputSchema = z.object({
  success: z.boolean(),
  data: z.record(z.string(), z.unknown()).optional(),
  receiptRef: z.string().optional(),
  error: z.string().optional()
}).passthrough();


export const Xaas_Conference_Event_destroy_inputSchema = z.object({
  ends_at: z.string(),
  id: z.string().uuid(),
  location: z.string(),
  name: z.string(),
  slug: z.string(),
  starts_at: z.string()
}).passthrough();

export const Xaas_Conference_Event_destroy_outputSchema = z.object({
  success: z.boolean(),
  data: z.record(z.string(), z.unknown()).optional(),
  receiptRef: z.string().optional(),
  error: z.string().optional()
}).passthrough();


export const Xaas_Conference_Event_read_inputSchema = z.object({
  ends_at: z.string(),
  id: z.string().uuid(),
  location: z.string(),
  name: z.string(),
  slug: z.string(),
  starts_at: z.string()
}).passthrough();

export const Xaas_Conference_Event_read_outputSchema = z.object({
  success: z.boolean(),
  data: z.record(z.string(), z.unknown()).optional(),
  receiptRef: z.string().optional(),
  error: z.string().optional()
}).passthrough();


export const Xaas_Conference_Registration_create_inputSchema = z.object({
  attendee_id: z.string().uuid(),
  id: z.string().uuid(),
  session_id: z.string().uuid(),
  status: z.unknown()
}).passthrough();

export const Xaas_Conference_Registration_create_outputSchema = z.object({
  success: z.boolean(),
  data: z.record(z.string(), z.unknown()).optional(),
  receiptRef: z.string().optional(),
  error: z.string().optional()
}).passthrough();


export const Xaas_Conference_Registration_destroy_inputSchema = z.object({
  attendee_id: z.string().uuid(),
  id: z.string().uuid(),
  session_id: z.string().uuid(),
  status: z.unknown()
}).passthrough();

export const Xaas_Conference_Registration_destroy_outputSchema = z.object({
  success: z.boolean(),
  data: z.record(z.string(), z.unknown()).optional(),
  receiptRef: z.string().optional(),
  error: z.string().optional()
}).passthrough();


export const Xaas_Conference_Registration_read_inputSchema = z.object({
  attendee_id: z.string().uuid(),
  id: z.string().uuid(),
  session_id: z.string().uuid(),
  status: z.unknown()
}).passthrough();

export const Xaas_Conference_Registration_read_outputSchema = z.object({
  success: z.boolean(),
  data: z.record(z.string(), z.unknown()).optional(),
  receiptRef: z.string().optional(),
  error: z.string().optional()
}).passthrough();


export const Xaas_Conference_Registration_update_inputSchema = z.object({
  attendee_id: z.string().uuid(),
  id: z.string().uuid(),
  session_id: z.string().uuid(),
  status: z.unknown()
}).passthrough();

export const Xaas_Conference_Registration_update_outputSchema = z.object({
  success: z.boolean(),
  data: z.record(z.string(), z.unknown()).optional(),
  receiptRef: z.string().optional(),
  error: z.string().optional()
}).passthrough();


export const Xaas_Conference_Session_create_inputSchema = z.object({
  description: z.string(),
  ends_at: z.string(),
  id: z.string().uuid(),
  slug: z.string(),
  speaker_id: z.string().uuid(),
  starts_at: z.string(),
  title: z.string(),
  track_id: z.string().uuid()
}).passthrough();

export const Xaas_Conference_Session_create_outputSchema = z.object({
  success: z.boolean(),
  data: z.record(z.string(), z.unknown()).optional(),
  receiptRef: z.string().optional(),
  error: z.string().optional()
}).passthrough();


export const Xaas_Conference_Session_destroy_inputSchema = z.object({
  description: z.string(),
  ends_at: z.string(),
  id: z.string().uuid(),
  slug: z.string(),
  speaker_id: z.string().uuid(),
  starts_at: z.string(),
  title: z.string(),
  track_id: z.string().uuid()
}).passthrough();

export const Xaas_Conference_Session_destroy_outputSchema = z.object({
  success: z.boolean(),
  data: z.record(z.string(), z.unknown()).optional(),
  receiptRef: z.string().optional(),
  error: z.string().optional()
}).passthrough();


export const Xaas_Conference_Session_read_inputSchema = z.object({
  description: z.string(),
  ends_at: z.string(),
  id: z.string().uuid(),
  slug: z.string(),
  speaker_id: z.string().uuid(),
  starts_at: z.string(),
  title: z.string(),
  track_id: z.string().uuid()
}).passthrough();

export const Xaas_Conference_Session_read_outputSchema = z.object({
  success: z.boolean(),
  data: z.record(z.string(), z.unknown()).optional(),
  receiptRef: z.string().optional(),
  error: z.string().optional()
}).passthrough();


export const Xaas_Conference_Speaker_create_inputSchema = z.object({
  bio: z.string(),
  id: z.string().uuid(),
  keynote?: z.boolean(),
  name: z.string(),
  slug: z.string()
}).passthrough();

export const Xaas_Conference_Speaker_create_outputSchema = z.object({
  success: z.boolean(),
  data: z.record(z.string(), z.unknown()).optional(),
  receiptRef: z.string().optional(),
  error: z.string().optional()
}).passthrough();


export const Xaas_Conference_Speaker_destroy_inputSchema = z.object({
  bio: z.string(),
  id: z.string().uuid(),
  keynote?: z.boolean(),
  name: z.string(),
  slug: z.string()
}).passthrough();

export const Xaas_Conference_Speaker_destroy_outputSchema = z.object({
  success: z.boolean(),
  data: z.record(z.string(), z.unknown()).optional(),
  receiptRef: z.string().optional(),
  error: z.string().optional()
}).passthrough();


export const Xaas_Conference_Speaker_read_inputSchema = z.object({
  bio: z.string(),
  id: z.string().uuid(),
  keynote?: z.boolean(),
  name: z.string(),
  slug: z.string()
}).passthrough();

export const Xaas_Conference_Speaker_read_outputSchema = z.object({
  success: z.boolean(),
  data: z.record(z.string(), z.unknown()).optional(),
  receiptRef: z.string().optional(),
  error: z.string().optional()
}).passthrough();


export const Xaas_Conference_Sponsor_create_inputSchema = z.object({
  id: z.string().uuid(),
  name: z.string(),
  slug: z.string(),
  tier: z.unknown(),
  url: z.string()
}).passthrough();

export const Xaas_Conference_Sponsor_create_outputSchema = z.object({
  success: z.boolean(),
  data: z.record(z.string(), z.unknown()).optional(),
  receiptRef: z.string().optional(),
  error: z.string().optional()
}).passthrough();


export const Xaas_Conference_Sponsor_destroy_inputSchema = z.object({
  id: z.string().uuid(),
  name: z.string(),
  slug: z.string(),
  tier: z.unknown(),
  url: z.string()
}).passthrough();

export const Xaas_Conference_Sponsor_destroy_outputSchema = z.object({
  success: z.boolean(),
  data: z.record(z.string(), z.unknown()).optional(),
  receiptRef: z.string().optional(),
  error: z.string().optional()
}).passthrough();


export const Xaas_Conference_Sponsor_read_inputSchema = z.object({
  id: z.string().uuid(),
  name: z.string(),
  slug: z.string(),
  tier: z.unknown(),
  url: z.string()
}).passthrough();

export const Xaas_Conference_Sponsor_read_outputSchema = z.object({
  success: z.boolean(),
  data: z.record(z.string(), z.unknown()).optional(),
  receiptRef: z.string().optional(),
  error: z.string().optional()
}).passthrough();


export const Xaas_Conference_Track_create_inputSchema = z.object({
  description: z.string(),
  event_id: z.string().uuid(),
  id: z.string().uuid(),
  name: z.string(),
  slug: z.string()
}).passthrough();

export const Xaas_Conference_Track_create_outputSchema = z.object({
  success: z.boolean(),
  data: z.record(z.string(), z.unknown()).optional(),
  receiptRef: z.string().optional(),
  error: z.string().optional()
}).passthrough();


export const Xaas_Conference_Track_destroy_inputSchema = z.object({
  description: z.string(),
  event_id: z.string().uuid(),
  id: z.string().uuid(),
  name: z.string(),
  slug: z.string()
}).passthrough();

export const Xaas_Conference_Track_destroy_outputSchema = z.object({
  success: z.boolean(),
  data: z.record(z.string(), z.unknown()).optional(),
  receiptRef: z.string().optional(),
  error: z.string().optional()
}).passthrough();


export const Xaas_Conference_Track_read_inputSchema = z.object({
  description: z.string(),
  event_id: z.string().uuid(),
  id: z.string().uuid(),
  name: z.string(),
  slug: z.string()
}).passthrough();

export const Xaas_Conference_Track_read_outputSchema = z.object({
  success: z.boolean(),
  data: z.record(z.string(), z.unknown()).optional(),
  receiptRef: z.string().optional(),
  error: z.string().optional()
}).passthrough();


export const SCHEMAS = {
  "Xaas.Conference.Attendee#create": { input: Xaas_Conference_Attendee_create_inputSchema, output: Xaas_Conference_Attendee_create_outputSchema },
  "Xaas.Conference.Attendee#destroy": { input: Xaas_Conference_Attendee_destroy_inputSchema, output: Xaas_Conference_Attendee_destroy_outputSchema },
  "Xaas.Conference.Attendee#read": { input: Xaas_Conference_Attendee_read_inputSchema, output: Xaas_Conference_Attendee_read_outputSchema },
  "Xaas.Conference.Event#create": { input: Xaas_Conference_Event_create_inputSchema, output: Xaas_Conference_Event_create_outputSchema },
  "Xaas.Conference.Event#destroy": { input: Xaas_Conference_Event_destroy_inputSchema, output: Xaas_Conference_Event_destroy_outputSchema },
  "Xaas.Conference.Event#read": { input: Xaas_Conference_Event_read_inputSchema, output: Xaas_Conference_Event_read_outputSchema },
  "Xaas.Conference.Registration#create": { input: Xaas_Conference_Registration_create_inputSchema, output: Xaas_Conference_Registration_create_outputSchema },
  "Xaas.Conference.Registration#destroy": { input: Xaas_Conference_Registration_destroy_inputSchema, output: Xaas_Conference_Registration_destroy_outputSchema },
  "Xaas.Conference.Registration#read": { input: Xaas_Conference_Registration_read_inputSchema, output: Xaas_Conference_Registration_read_outputSchema },
  "Xaas.Conference.Registration#update": { input: Xaas_Conference_Registration_update_inputSchema, output: Xaas_Conference_Registration_update_outputSchema },
  "Xaas.Conference.Session#create": { input: Xaas_Conference_Session_create_inputSchema, output: Xaas_Conference_Session_create_outputSchema },
  "Xaas.Conference.Session#destroy": { input: Xaas_Conference_Session_destroy_inputSchema, output: Xaas_Conference_Session_destroy_outputSchema },
  "Xaas.Conference.Session#read": { input: Xaas_Conference_Session_read_inputSchema, output: Xaas_Conference_Session_read_outputSchema },
  "Xaas.Conference.Speaker#create": { input: Xaas_Conference_Speaker_create_inputSchema, output: Xaas_Conference_Speaker_create_outputSchema },
  "Xaas.Conference.Speaker#destroy": { input: Xaas_Conference_Speaker_destroy_inputSchema, output: Xaas_Conference_Speaker_destroy_outputSchema },
  "Xaas.Conference.Speaker#read": { input: Xaas_Conference_Speaker_read_inputSchema, output: Xaas_Conference_Speaker_read_outputSchema },
  "Xaas.Conference.Sponsor#create": { input: Xaas_Conference_Sponsor_create_inputSchema, output: Xaas_Conference_Sponsor_create_outputSchema },
  "Xaas.Conference.Sponsor#destroy": { input: Xaas_Conference_Sponsor_destroy_inputSchema, output: Xaas_Conference_Sponsor_destroy_outputSchema },
  "Xaas.Conference.Sponsor#read": { input: Xaas_Conference_Sponsor_read_inputSchema, output: Xaas_Conference_Sponsor_read_outputSchema },
  "Xaas.Conference.Track#create": { input: Xaas_Conference_Track_create_inputSchema, output: Xaas_Conference_Track_create_outputSchema },
  "Xaas.Conference.Track#destroy": { input: Xaas_Conference_Track_destroy_inputSchema, output: Xaas_Conference_Track_destroy_outputSchema },
  "Xaas.Conference.Track#read": { input: Xaas_Conference_Track_read_inputSchema, output: Xaas_Conference_Track_read_outputSchema }
};
