// @generated by AshSurface.Projectors.JS (CalVer 26.10.1); prefix "xaas_ash_surface_client"
// Do not edit directly; change the admitted IR sources, then re-project.
// Law: pi_JS(IR) = JavaScript + JSDoc + Zod. TypeScript-free, no build step.
// DO-boundary actions project dispatch-INTENT descriptors only: an intent
// is data and carries no execution authority; this artifact contains no
// invoke/dispatch execution path.

import { z } from "zod";

/**
 * A dispatch intent for a DO-boundary action. DATA ONLY: minting an
 * intent never executes the action. Execution requires a separately
 * admitted, brokered, receipt-bearing dispatch path.
 * @typedef {Object} DispatchIntent
 * @property {"DISPATCH_INTENT"} kind
 * @property {string} actionId
 * @property {Record<string, unknown>} input - boundary-validated by the action Zod schema when present
 */

/** Zod boundary schema for `Pack.create` (input schema of the compiled IR.Schema.zod program). */
export const Pack_create_schema = z.object({
  deprecated: z.boolean(),
  description: z.string(),
  digest: z.string(),
  download_url: z.string(),
  lifecycle_tier: z.string(),
  name: z.string(),
  ontology_fingerprint: z.string().optional().nullable(),
  pack_class: z.string().optional().nullable(),
  readiness: z.string(),
  version: z.string()
}).passthrough();

/** Zod boundary schema for `Pack.destroy` (input schema of the compiled IR.Schema.zod program). */
export const Pack_destroy_schema = z.object({

}).passthrough();

/** Zod boundary schema for `Pack.read` (input schema of the compiled IR.Schema.zod program). */
export const Pack_read_schema = z.object({

}).passthrough();

/** Zod boundary schema for `Pack.update` (input schema of the compiled IR.Schema.zod program). */
export const Pack_update_schema = z.object({
  deprecated: z.boolean(),
  description: z.string(),
  digest: z.string(),
  download_url: z.string(),
  lifecycle_tier: z.string(),
  ontology_fingerprint: z.string().optional().nullable(),
  pack_class: z.string().optional().nullable(),
  readiness: z.string(),
  version: z.string()
}).passthrough();

/**
 * JSDoc-typed namespace for resource `Pack` (4 actions: create, destroy, read, update).
 * @typedef {Object} PackNamespace
 * @property {Object} create - `Pack.create` (authorityBoundary: not delegated, descriptorKind: "DESCRIPTOR")
 * @property {Object} destroy - `Pack.destroy` (authorityBoundary: not delegated, descriptorKind: "DESCRIPTOR")
 * @property {Object} read - `Pack.read` (authorityBoundary: not delegated, descriptorKind: "DESCRIPTOR")
 * @property {Object} update - `Pack.update` (authorityBoundary: not delegated, descriptorKind: "DESCRIPTOR")
 */
export const Pack = Object.freeze({
  /** `Pack.create` — not delegated; no dispatch intent. */
  create: Object.freeze({
    id: "Pack.create",
    resource: "Pack",
    action: "create",
    actionType: "create",
    authorityBoundary: null,
    receiptRequired: false,
    descriptorKind: "DESCRIPTOR",
    capabilityIri: null,
    label: "Create",
    schema: Pack_create_schema
  }),
  /** `Pack.destroy` — not delegated; no dispatch intent. */
  destroy: Object.freeze({
    id: "Pack.destroy",
    resource: "Pack",
    action: "destroy",
    actionType: "destroy",
    authorityBoundary: null,
    receiptRequired: false,
    descriptorKind: "DESCRIPTOR",
    capabilityIri: null,
    label: "Destroy",
    schema: Pack_destroy_schema
  }),
  /** `Pack.read` — not delegated; no dispatch intent. */
  read: Object.freeze({
    id: "Pack.read",
    resource: "Pack",
    action: "read",
    actionType: "read",
    authorityBoundary: null,
    receiptRequired: false,
    descriptorKind: "DESCRIPTOR",
    capabilityIri: null,
    label: "Read",
    schema: Pack_read_schema
  }),
  /** `Pack.update` — not delegated; no dispatch intent. */
  update: Object.freeze({
    id: "Pack.update",
    resource: "Pack",
    action: "update",
    actionType: "update",
    authorityBoundary: null,
    receiptRequired: false,
    descriptorKind: "DESCRIPTOR",
    capabilityIri: null,
    label: "Update",
    schema: Pack_update_schema
  })
});

/**
 * Every action descriptor, sorted by id. DO-boundary descriptors carry
 * descriptorKind "DISPATCH_INTENT"; every other descriptor is a plain
 * "DESCRIPTOR". Members are the namespace objects themselves, so
 * descriptor identity is shared.
 */
export const ACTIONS = Object.freeze([
  Pack.create,
  Pack.destroy,
  Pack.read,
  Pack.update
]);

/** Zod boundary schemas by action id, present only where the IR delegated one. */
export const SCHEMAS = Object.freeze({
  "Pack.create": Pack_create_schema,
  "Pack.destroy": Pack_destroy_schema,
  "Pack.read": Pack_read_schema,
  "Pack.update": Pack_update_schema
});

/** Resource namespaces, sorted by resource name. */
export const NAMESPACES = Object.freeze({
  Pack
});

/** Descriptor lookup by action id; null when unknown. */
export function getAction(id) {
  return ACTIONS.find((a) => a.id === id) ?? null;
}

/**
 * Mints a dispatch INTENT for a DO-boundary action. Refused for unknown
 * actions and for any action whose delegated boundary is not exactly
 * "DO". Input is boundary-validated by the action's Zod schema when the
 * IR delegated one. Never executes anything.
 * @param {string} id
 * @param {Record<string, unknown>} input
 * @returns {DispatchIntent}
 */
export function dispatchIntent(id, input) {
  const action = getAction(id);
  if (action === null) {
    throw new Error("REFUSED_UNKNOWN_ACTION: " + id);
  }
  if (action.descriptorKind !== "DISPATCH_INTENT") {
    throw new Error("REFUSED_NOT_DO_BOUNDARY: " + id + " has descriptorKind " + action.descriptorKind);
  }
  const parsed = action.schema ? action.schema.parse(input) : input;
  return Object.freeze({ kind: "DISPATCH_INTENT", actionId: id, input: parsed });
}
