defmodule XaasWeb.Plugs.ProvOriginHeader do
  @moduledoc """
  W605 (WP-1, OS-16 / EU AI Act Art. 50(2)): machine-detectable
  artificial-origin provenance on the public machine surfaces (`/api`
  forward scope, `/a2a` transport).

  ## Header shape (the one machine-detectable form, pinned here)

      x-prov-o: wasGeneratedBy=<agent-iri>; actedOnBehalfOf=<operator-iri>

  IRIs are wrapped in angle brackets per the W3C PROV-N / PROV-O convention.
  The terms `wasGeneratedBy` and `actedOnBehalfOf` are PROV-O object
  properties from the W3C PROVENANCE ontology namespace
  `http://www.w3.org/ns/prov#` (PROV-O, W3C Recommendation, 2013-04-30,
  https://www.w3.org/TR/prov-o/). The assertion carried by the header is
  exactly "this response is machine-generated by `<agent-iri>`, which acted
  on behalf of `<operator-iri>`".

  ## Constant, config-driven values

  The IRIs are application identity, NOT per-request fabricated values.
  They come from `Application.get_env(:xaas, :prov_origin)` (keys
  `:agent_iri`, `:operator_iri`), falling back to compile-time constants.
  A response never carries a per-request value — the assertion is about the
  software origin, not the conversational turn.

  ## Seam

  A router pipeline plug (`pipeline :prov_origin`) wired into the `/api`
  forward scope and the `/a2a` scope. The plug registers a
  `register_before_send` callback, so the header is attached to every
  response from a wired surface — including 401/403 refusal envelopes
  emitted by a later halting plug (before_send callbacks run for halted
  conns). Placed FIRST in both wired pipelines so refusal envelopes are
  provenance-marked too; it performs no content negotiation and cannot
  re-open the W150/W739 content-type leak class.

  Not wired into `:browser`/LiveView: those are human-facing surfaces, and
  the assertion "this response is machine-generated" is false for them.
  Disclosed per W605 dispatch: the clean `:browser` pipeline hook exists,
  wiring it would assert a false provenance, so it is deliberately left out.
  """

  @behaviour Plug

  @header "x-prov-o"

  @default_agent_iri "https://w3id.org/xaas/agent/xaas-platform"
  @default_operator_iri "https://w3id.org/xaas/operator/xaas-operators"

  @doc "The exact header name this plug attaches (`x-prov-o`)."
  def header_name, do: @header

  @doc """
  The exact header value shape — `wasGeneratedBy=<iri>; actedOnBehalfOf=<iri>`
  with PROV-O terms from `http://www.w3.org/ns/prov#`, IRIs angle-bracketed.
  Constant (config-driven), identical for every request.
  """
  def header_value do
    cfg = Application.get_env(:xaas, :prov_origin, [])

    agent = Keyword.get(cfg, :agent_iri, @default_agent_iri)
    operator = Keyword.get(cfg, :operator_iri, @default_operator_iri)

    "wasGeneratedBy=<#{agent}>; actedOnBehalfOf=<#{operator}>"
  end

  @impl true
  def init(opts), do: opts

  @impl true
  def call(conn, _opts) do
    Plug.Conn.register_before_send(conn, fn conn ->
      Plug.Conn.put_resp_header(conn, @header, header_value())
    end)
  end
end
