defmodule KanbanWeb.MarketplaceProviderControllerTest do
  @moduledoc """
  Real Chicago-style ConnCase test: real Phoenix HTTP requests against the
  real `/api/marketplace_providers` `get`/`index` routes generated by
  `Xaas.Marketplace.Provider`'s `json_api do routes do ... end end` block,
  gated by the real `KanbanWeb.Plugs.RequireInternalApiToken` plug on the
  `/api` forward. No mocking.
  """
  use KanbanWeb.ConnCase

  alias Xaas.Marketplace.Provider

  setup do
    Ecto.Adapters.SQL.Sandbox.checkout(Xaas.Repo)
    :ok
  end

  defp json_headers(conn) do
    conn
    |> put_req_header("authorization", "Bearer " <> System.fetch_env!("INTERNAL_API_TOKEN"))
    |> put_req_header("accept", "application/vnd.api+json")
  end

  defp create_provider!(attrs) do
    Provider
    |> Ash.Changeset.for_create(:create, attrs)
    |> Ash.create!(authorize?: false)
  end

  test "GET /api/marketplace_providers without the internal API token is really rejected", %{
    conn: conn
  } do
    resp = conn |> put_req_header("accept", "application/vnd.api+json") |> get("/api/marketplace_providers")
    assert resp.status in [401, 403, 503]
  end

  test "GET /api/marketplace_providers with a valid token but no policy bypass is really forbidden",
       %{conn: conn} do
    _provider =
      create_provider!(%{
        name: "Acme Widgets",
        slug: "acme-widgets-http-#{System.unique_integer([:positive])}",
        org_id: "org-http"
      })

    body = conn |> json_headers() |> get("/api/marketplace_providers") |> json_response(200)

    # Real deny-by-default floor: this resource has no real actor-scoping
    # rule designed yet (see the resource's own moduledoc). AshJsonApi's
    # index route is filter-based, so a real, authenticated-to-the-app
    # (valid internal API token) request that fails the resource's real
    # policy comes back 200 with a really-empty result set -- the just-
    # created row is really excluded, not silently returned.
    assert body["data"] == []
  end

  test "GET /api/marketplace_providers/:id with a valid token is really not found", %{
    conn: conn
  } do
    provider =
      create_provider!(%{
        name: "Beta Co",
        slug: "beta-co-http-#{System.unique_integer([:positive])}",
        org_id: "org-http-2"
      })

    resp = conn |> json_headers() |> get("/api/marketplace_providers/#{provider.id}")

    # Same real deny-by-default floor via the get-by-id route: the row is
    # really excluded by the policy filter before the id lookup can match
    # it, so AshJsonApi reports a real 404, not a 403 or a leaked 200.
    assert resp.status == 404
  end
end
