# GENERATED by ggen_igniter from priv/packs/xaas_library_pack/ontology.ttl.
# Do not edit directly. Regenerate with:
#   mix ggen_igniter.sync --pack-dir priv/packs/xaas_library_pack
defmodule Mix.Tasks.Xaas.Library.Manufacture do
  @moduledoc """
  Manufactures the Xaas.Library domain, resources (Book, Checkout, Curation),
  and applies core resource definitions grounded in Schema.org and BIBO ontologies.

  Usage:
      mix xaas.library.manufacture --phase base --yes
      mix xaas.library.manufacture --phase core --yes
  """
  use Mix.Task

  @shortdoc "Manufactures Xaas.Library domain and resources from ontology"

  @base_targets [

    %{
      order: 1,
      mix_task: "ash.gen.domain",
      target_module: "Xaas.Library",
      domain_module: "Xaas",
      resource_module: "",
      mix_args: ""
    },

    %{
      order: 2,
      mix_task: "ash.gen.resource",
      target_module: "Xaas.Library.Book",
      domain_module: "Xaas.Library",
      resource_module: "Book",
      mix_args: "--ignore-if-exists --default-actions read --uuid-primary-key id"
    },

    %{
      order: 3,
      mix_task: "ash.gen.resource",
      target_module: "Xaas.Library.Checkout",
      domain_module: "Xaas.Library",
      resource_module: "Checkout",
      mix_args: "--ignore-if-exists --default-actions read --uuid-primary-key id"
    },

    %{
      order: 4,
      mix_task: "ash.gen.resource",
      target_module: "Xaas.Library.Curation",
      domain_module: "Xaas.Library",
      resource_module: "Curation",
      mix_args: "--ignore-if-exists --default-actions read --uuid-primary-key id"
    },

  ]

  @core_targets [

    %{
      order: 1,
      mix_task: "xaas.library.core",
      target_module: "Xaas.Library.Book",
      domain_module: "Xaas.Library",
      resource_module: "Book",
      mix_args: ""
    },

    %{
      order: 2,
      mix_task: "xaas.library.core",
      target_module: "Xaas.Library.Checkout",
      domain_module: "Xaas.Library",
      resource_module: "Checkout",
      mix_args: ""
    },

    %{
      order: 3,
      mix_task: "xaas.library.core",
      target_module: "Xaas.Library.Curation",
      domain_module: "Xaas.Library",
      resource_module: "Curation",
      mix_args: ""
    },

  ]

  @impl Mix.Task
  def run(args) do
    {opts, _rest, _invalid} =
      OptionParser.parse(args,
        strict: [phase: :string, yes: :boolean],
        aliases: [p: :phase, y: :yes]
      )

    phase = opts[:phase] || "all"
    yes? = opts[:yes] || false

    Mix.shell().info("[xaas.library.manufacture] Running phase: #{phase} (yes=#{yes?})")

    case phase do
      "base" ->
        run_base_phase(yes?)

      "core" ->
        run_core_phase(yes?)

      "all" ->
        run_base_phase(yes?)
        run_core_phase(yes?)

      other ->
        Mix.raise("Unknown phase: #{other}. Expected: base, core, all")
    end
  end

  def base_targets, do: @base_targets
  def core_targets, do: @core_targets

  defp run_base_phase(_yes?) do
    Mix.shell().info("==> Executing Phase 1: Base Scaffolding via Igniter / Ash Generators")

    # 1. Ensure Domain file exists
    domain_path = "lib/xaas/library.ex"
    domain_content = """
defmodule Xaas.Library do
  @moduledoc \"\"\"
  Domain module for Library management (Books, Checkouts, Curations)
  grounded in Schema.org and BIBO ontologies.
  \"\"\"
  use Ash.Domain,
    otp_app: :kanban,
    extensions: [AshJsonApi.Domain, AshGraphql.Domain, AshAdmin.Domain]

  admin do
    show? true
  end

  resources do
    resource Xaas.Library.Book
    resource Xaas.Library.Checkout
    resource Xaas.Library.Curation
  end
end
"""
    File.mkdir_p!("lib/xaas")
    File.write!(domain_path, domain_content)
    Mix.shell().info("  [ok] Wrote #{domain_path}")

    # Ensure registration in config/config.exs ash_domains
    ensure_domain_configured()

    # 2. Scaffolding base resource stubs
    Enum.each(@base_targets, fn target ->
      if target.resource_module != "" do
        file_name = Macro.underscore(target.resource_module) <> ".ex"
        res_path = Path.join(["lib", "xaas", "library", file_name])
        File.mkdir_p!("lib/xaas/library")
        unless File.exists?(res_path) do
          stub_content = """
defmodule #{target.target_module} do
  use Xaas.Resource,
    otp_app: :kanban,
    domain: Xaas.Library,
    data_layer: AshPostgres.DataLayer,
    authorizers: [Ash.Policy.Authorizer]

  postgres do
    table "#{Macro.underscore(target.resource_module)}s"
    repo Xaas.Repo
  end

  actions do
    defaults [:read]
  end

  policies do
    policy always() do
      authorize_if always()
    end
  end

  attributes do
    uuid_primary_key :id
  end
end
"""
          File.write!(res_path, stub_content)
          Mix.shell().info("  [ok] Initialized stub for #{target.target_module} at #{res_path}")
        end
      end
    end)
  end

  defp run_core_phase(_yes?) do
    Mix.shell().info("==> Executing Phase 2: Core Resource Realization with Public Ontology Grounding")

    # Realize Book
    write_book_resource()

    # Realize Checkout
    write_checkout_resource()

    # Realize Curation
    write_curation_resource()

    Mix.shell().info("==> Realized Xaas.Library.Book, Checkout, and Curation.")
  end

  defp ensure_domain_configured do
    config_path = "config/config.exs"
    content = File.read!(config_path)
    unless String.contains?(content, "Xaas.Library") do
      updated = String.replace(content, "ash_domains: [", "ash_domains: [\n    Xaas.Library,")
      File.write!(config_path, updated)
      Mix.shell().info("  [ok] Added Xaas.Library to ash_domains in config/config.exs")
    end
  end

  defp write_book_resource do
    content = """
defmodule Xaas.Library.Book do
  @moduledoc \"\"\"
  Ash resource for Library Books, grounded in BIBO (bibo:Book) and Schema.org (schema:Book).
  Represents library items with ISBN, grade-level reading fit, genres, and availability.
  \"\"\"
  use Xaas.Resource,
    otp_app: :kanban,
    domain: Xaas.Library,
    data_layer: AshPostgres.DataLayer,
    authorizers: [Ash.Policy.Authorizer]

  postgres do
    table "library_books"
    repo Xaas.Repo
  end

  actions do
    defaults [:read, :destroy]

    create :create do
      primary? true
      accept [
        :title,
        :author,
        :isbn,
        :grade_level,
        :genres,
        :synopsis,
        :available_copies,
        :total_copies,
        :embedding
      ]
    end

    update :update do
      primary? true
      accept [
        :title,
        :author,
        :isbn,
        :grade_level,
        :genres,
        :synopsis,
        :available_copies,
        :total_copies,
        :embedding
      ]
    end

    read :by_grade_band do
      argument :min_grade, :integer, allow_nil?: false
      argument :max_grade, :integer, allow_nil?: false

      filter expr(grade_level >= ^arg(:min_grade) and grade_level <= ^arg(:max_grade))
    end
  end

  policies do
    # Scoped reads bypass for general library search
    bypass always() do
      authorize_if always()
    end

    # Default deny floor
    policy always() do
      forbid_if always()
    end
  end

  attributes do
    uuid_primary_key :id

    attribute :title, :string do
      allow_nil? false
      public? true
    end

    attribute :author, :string do
      allow_nil? false
      public? true
    end

    attribute :isbn, :string do
      allow_nil? true
      public? true
    end

    attribute :grade_level, :integer do
      allow_nil? false
      public? true
    end

    attribute :genres, {:array, :string} do
      allow_nil? false
      default []
      public? true
    end

    attribute :synopsis, :string do
      allow_nil? true
      public? true
    end

    attribute :available_copies, :integer do
      allow_nil? false
      default 1
      public? true
    end

    attribute :total_copies, :integer do
      allow_nil? false
      default 1
      public? true
    end

    attribute :embedding, {:array, :float} do
      allow_nil? true
      public? true
    end

    create_timestamp :inserted_at
    update_timestamp :updated_at
  end

  relationships do
    has_many :checkouts, Xaas.Library.Checkout
    has_many :curations, Xaas.Library.Curation
  end
end
"""
    File.write!("lib/xaas/library/book.ex", content)
    Mix.shell().info("  [ok] Materialized lib/xaas/library/book.ex")
  end

  defp write_checkout_resource do
    content = """
defmodule Xaas.Library.Checkout do
  @moduledoc \"\"\"
  Ash resource for Book Checkouts, grounded in Schema.org (schema:BorrowAction) and PROV (prov:Activity).
  Tracks circulation transactions of books borrowed by readers.
  \"\"\"
  use Xaas.Resource,
    otp_app: :kanban,
    domain: Xaas.Library,
    data_layer: AshPostgres.DataLayer,
    authorizers: [Ash.Policy.Authorizer]

  postgres do
    table "library_checkouts"
    repo Xaas.Repo
  end

  actions do
    defaults [:read, :destroy]

    create :create do
      primary? true
      accept [:book_id, :user_id, :borrowed_at, :returned_at, :status]
    end

    update :update do
      primary? true
      accept [:returned_at, :status]
    end

    read :for_user do
      argument :user_id, :uuid, allow_nil?: false
      filter expr(user_id == ^arg(:user_id))
    end
  end

  policies do
    bypass always() do
      authorize_if always()
    end

    policy always() do
      forbid_if always()
    end
  end

  attributes do
    uuid_primary_key :id

    attribute :borrowed_at, :utc_datetime_usec do
      allow_nil? false
      default &DateTime.utc_now/0
      public? true
    end

    attribute :returned_at, :utc_datetime_usec do
      allow_nil? true
      public? true
    end

    attribute :status, :atom do
      constraints [one_of: [:borrowed, :returned, :overdue]]
      default :borrowed
      allow_nil? false
      public? true
    end

    create_timestamp :inserted_at
    update_timestamp :updated_at
  end

  relationships do
    belongs_to :book, Xaas.Library.Book do
      allow_nil? false
      attribute_writable? true
      public? true
    end

    belongs_to :user, Xaas.Accounts.User do
      allow_nil? false
      attribute_writable? true
      public? true
    end
  end
end
"""
    File.write!("lib/xaas/library/checkout.ex", content)
    Mix.shell().info("  [ok] Materialized lib/xaas/library/checkout.ex")
  end

  defp write_curation_resource do
    content = """
defmodule Xaas.Library.Curation do
  @moduledoc \"\"\"
  Ash resource for Librarian Curation, grounded in Schema.org (schema:Collection) and PROV (prov:Entity).
  Staff spotlight that boosts recommendation scores for specific grade bands.
  \"\"\"
  use Xaas.Resource,
    otp_app: :kanban,
    domain: Xaas.Library,
    data_layer: AshPostgres.DataLayer,
    authorizers: [Ash.Policy.Authorizer]

  postgres do
    table "library_curations"
    repo Xaas.Repo
  end

  actions do
    defaults [:read, :destroy]

    create :create do
      primary? true
      accept [:book_id, :curated_by, :grade_band, :reason, :active]
    end

    update :update do
      primary? true
      accept [:grade_band, :reason, :active]
    end

    read :active_for_grade do
      argument :grade_level, :integer, allow_nil?: false
      filter expr(active == true)
    end
  end

  policies do
    bypass always() do
      authorize_if always()
    end

    policy always() do
      forbid_if always()
    end
  end

  attributes do
    uuid_primary_key :id

    attribute :curated_by, :string do
      allow_nil? false
      public? true
    end

    attribute :grade_band, :string do
      allow_nil? false
      public? true
    end

    attribute :reason, :string do
      allow_nil? true
      public? true
    end

    attribute :active, :boolean do
      allow_nil? false
      default true
      public? true
    end

    create_timestamp :inserted_at
    update_timestamp :updated_at
  end

  relationships do
    belongs_to :book, Xaas.Library.Book do
      allow_nil? false
      attribute_writable? true
      public? true
    end
  end
end
"""
    File.write!("lib/xaas/library/curation.ex", content)
    Mix.shell().info("  [ok] Materialized lib/xaas/library/curation.ex")
  end
end
