# GENERATED by ggen_igniter from priv/packs/xaas_telemetry_pack/ontology.ttl.
# Do not edit directly. Regenerate with:
#   mix ggen_igniter.sync --pack-dir priv/packs/xaas_telemetry_pack --template priv/packs/xaas_telemetry_pack/templates/ocel_envelope.ex.eex --out lib/xaas/telemetry/ocel_envelope.ex
defmodule Xaas.Telemetry.OcelEnvelope do
  @moduledoc """
  Pure OCEL v2 batch-envelope field construction, generated from
  `priv/packs/xaas_telemetry_pack/ontology.ttl`, which vendors (not a live
  cross-repo pointer) the envelope shape required by
  `Ex4pm.OCEL.validate_envelope/1`, read field-for-field from
  `/Users/sac/ex4pm/lib/ex4pm/ocel.ex` (around line 366-417), at ex4pm
  commit `725f495eb90d32a1582e6f44c08151d07743b784` (2026-09-09).

  Required top-level fields (ontology-grounded, one section per
  `xt:EnvelopeField` individual, ordered by `xt:fieldOrder`):

    * `"schema" -- Any non-nil value, stringified by validate_envelope/1 via to_string/1.

    * `"producer" -- Caller-supplied map (validate_envelope/1 requires is_map/1); ex4pm's Ingest.ingest_envelope/2 additionally reads 'agent_id'/'run_id' out of it, defaulting to 'unknown' if absent -- xaas always supplies both.

    * `"sequence" -- Non-negative integer, caller-supplied (xaas passes System.unique_integer([:positive, :monotonic])).

    * `"events" -- A list or map of OCEL event records; xaas forwards exactly one event per envelope today, so this wraps the single caller-supplied event map in a one-element list, unchanged (ocel:eid/ocel:activity/ocel:timestamp/ocel:omap/ocel:vmap keys passed through verbatim).

  This module builds ONLY the envelope map -- it performs no HTTP call and
  no call to `Ex4pm.OCEL.validate_envelope/1` itself. Both remain the
  responsibility of `Xaas.Telemetry.OcelForwarder.do_forward/2`, per
  doctrine (hand-written business logic is never generated).

  ## Vendored SHACL divergences (explicit, not corrected)

    * timestamp -- xaas's `"ocel:timestamp"` is a plain `String.t()`
      (`DateTime.to_iso8601/1` output), not ex4pm's own typed
      `xsd:dateTime`/`DateTime` shape.
    * omap -- xaas's `"ocel:omap"` is a type-name list (e.g. `["Book"]`),
      not ex4pm's canonical per-instance Object-identifier list.
  """

  @doc """
  Builds one OCEL v2 batch envelope wrapping a single already-built xaas
  OCEL event map.

    * `event` -- the event map (unchanged, forwarded verbatim inside the
      one-element `"events"` list)
    * `producer` -- caller-supplied producer map (e.g.
      `%{"agent_id" => "xaas", "run_id" => run_id}`)
    * `sequence` -- caller-supplied non-negative integer

  Returns the envelope map. Does not validate or POST it.
  """
  @spec build(map(), map(), integer()) :: map()
  def build(event, producer, sequence) when is_map(event) and is_map(producer) and is_integer(sequence) do
    %{
      "schema" => "xaas.ocel.v2",
      "producer" => producer,
      "sequence" => sequence,
      "events" => [event]
    }
  end
end
