defmodule Xaas.Telemetry.ZcodeOcelValidator do
  @moduledoc """
  Hand-written validation glue (SJ-002) for the zcode agent-loop OCEL
  event/object-type vocabulary: the only thing genuinely business-logic
  here is the accept/refuse *decision* and how a refusal is reported. The
  vocabulary itself (`Xaas.Generated.ZcodeEventRegistry`) is generated by
  `mix ggen_igniter.sync --pack-dir priv/packs/xaas_zcode_ocel_pack`, never
  hand-listed -- see that module's moduledoc for provenance.

  This is the wiring point `priv/zcode_plugin`'s OCEL emission and
  `Xaas.Telemetry.OcelAshEmitter` are expected to call before treating any
  zcode-loop-sourced event as valid, so an event type absent from the
  generated registry is refused here rather than silently accepted and
  forwarded downstream (the falsifier this ticket names).
  """

  alias Xaas.Generated.ZcodeEventRegistry

  @typedoc "A refusal reason, always naming the exact unknown value."
  @type refusal :: {:unknown_event_type, String.t()} | {:unknown_object_type, String.t()}

  @doc """
  Validates a zcode OCEL event's `"ocel:activity"` value against the
  generated `Xaas.Generated.ZcodeEventRegistry.event_type?/1`.

  Returns `{:ok, event_type}` when `event_type` is one of the generated
  event types, `{:error, {:unknown_event_type, event_type}}` otherwise --
  never raises, so callers on a hot telemetry path can log-and-drop rather
  than crash.
  """
  @spec validate_event_type(String.t()) :: {:ok, String.t()} | {:error, refusal()}
  def validate_event_type(event_type) when is_binary(event_type) do
    if ZcodeEventRegistry.event_type?(event_type) do
      {:ok, event_type}
    else
      {:error, {:unknown_event_type, event_type}}
    end
  end

  @doc """
  Same as `validate_event_type/1` but raises `ArgumentError` on refusal,
  for call sites that want a hard fail-fast (e.g. constructing a zcode
  OCEL event map before it is ever appended/forwarded).
  """
  @spec validate_event_type!(String.t()) :: String.t()
  def validate_event_type!(event_type) do
    case validate_event_type(event_type) do
      {:ok, event_type} ->
        event_type

      {:error, {:unknown_event_type, unknown}} ->
        raise ArgumentError,
              "unknown zcode OCEL event type #{inspect(unknown)} -- not present in " <>
                "Xaas.Generated.ZcodeEventRegistry.event_types/0 (#{inspect(ZcodeEventRegistry.event_types())})"
    end
  end

  @doc """
  Validates an OCEL object type against the generated
  `Xaas.Generated.ZcodeEventRegistry.object_type?/1`. Same contract as
  `validate_event_type/1`.
  """
  @spec validate_object_type(String.t()) :: {:ok, String.t()} | {:error, refusal()}
  def validate_object_type(object_type) when is_binary(object_type) do
    if ZcodeEventRegistry.object_type?(object_type) do
      {:ok, object_type}
    else
      {:error, {:unknown_object_type, object_type}}
    end
  end

  @doc """
  Builds one zcode OCEL v2 JSON-OCEL event map (`ocel:eid`/`ocel:activity`/
  `ocel:timestamp`/`ocel:omap`/`ocel:vmap`, mirroring
  `Xaas.Telemetry.OcelAshEmitter.build_ocel_event/3`'s existing shape) from
  `event_type` and `vmap`, refusing to build the event at all when
  `event_type` is absent from the generated registry.

  `omap` defaults to the event's generated primary object type
  (`ZcodeEventRegistry.primary_object/0`) when not given explicitly.
  """
  @spec build_event(String.t(), map(), keyword()) :: {:ok, map()} | {:error, refusal()}
  def build_event(event_type, vmap \\ %{}, opts \\ []) when is_map(vmap) do
    with {:ok, event_type} <- validate_event_type(event_type) do
      omap =
        Keyword.get_lazy(opts, :omap, fn ->
          case Map.fetch(ZcodeEventRegistry.primary_object(), event_type) do
            {:ok, primary} -> [primary]
            :error -> []
          end
        end)

      {:ok,
       %{
         "ocel:eid" => Keyword.get_lazy(opts, :eid, fn -> Ash.UUIDv7.generate() end),
         "ocel:activity" => event_type,
         "ocel:timestamp" =>
           Keyword.get_lazy(opts, :timestamp, fn ->
             DateTime.utc_now() |> DateTime.to_iso8601()
           end),
         "ocel:omap" => omap,
         "ocel:vmap" => vmap
       }}
    end
  end
end
