# GENERATED by ggen_igniter from priv/ggen/reactor-scaffold-pack/ontology.ttl.
# Do not edit. Regenerate with:
#   mix ggen_igniter.sync --pack reactor-scaffold-pack \
#     --out lib/ggen_igniter/reactors/examples/expense_approval_reactor.ex
#
# Practice/dogfood example: a full-featured plain `Reactor` (per ADR-0003,
# never Ash.Reactor) manufactured entirely from ontology data, exercising
# every construct in the real Reactor cheatsheet
# (https://reactor.hexdocs.pm/reactor-cheatsheet.html): input, step
# (argument/value/run/compensate/undo/async?/where/guard/max_retries/
# wait_for), debug, group, switch, compose, collect, map, around, template,
# middlewares, return.
defmodule Xaas.Ultracode.EpochReactor do
  @moduledoc """
  Manufactured example Reactor demonstrating the full plain-Reactor DSL
  surface documented at
  https://reactor.hexdocs.pm/reactor-cheatsheet.html — the same primitives
  `GgenIgniter.Reactors.ReconcileReactor` itself uses in production.

  Regenerate via `mix ggen_igniter.sync --pack reactor-scaffold-pack
  --out lib/ggen_igniter/reactors/examples/expense_approval_reactor.ex`.
  Never hand-edit this file — edit `priv/ggen/reactor-scaffold-pack/ontology.ttl`
  instead.
  """
  use Reactor


  input :epoch_id


  step :observe do
    argument(:epoch_id, input(:epoch_id))
    async? true

    run fn %{epoch_id: epoch_id}, _context ->
      case Ash.get(Xaas.Ultracode.Epoch, epoch_id, authorize?: false, load: [:run]) do
        {:ok, epoch} -> {:ok, epoch}
        {:error, error} -> {:error, {:observe_failed, error}}
      end
    end
  end


  step :admit do
    argument(:epoch, result(:observe))
    async? true

    run fn %{epoch: epoch}, _context ->
      if epoch.state in [:expected, :running] do
        {:ok, %{epoch: epoch, admitted?: true}}
      else
        {:error, {:refused, :epoch_not_admissible, epoch.state}}
      end
    end
  end


  step :plan do
    argument(:admission, result(:admit))
    async? true

    run fn %{admission: %{epoch: epoch}}, _context ->
      next_action = if epoch.state == :expected, do: :start, else: :complete
      {:ok, %{epoch: epoch, next_action: next_action}}
    end
  end


  step :construct do
    argument(:plan, result(:plan))
    async? true

    run fn %{plan: %{epoch: epoch, next_action: next_action}}, _context ->
      changeset = Ash.Changeset.for_update(epoch, next_action, %{}, authorize?: false)

      case Ash.update(changeset) do
        {:ok, updated_epoch} -> {:ok, %{epoch: updated_epoch, action_taken: next_action}}
        {:error, error} -> {:error, {:construct_failed, next_action, error}}
      end
    end
  end


  step :verify do
    argument(:constructed, result(:construct))
    argument(:original, result(:observe))
    async? true

    run fn %{constructed: %{epoch: constructed_epoch, action_taken: action_taken}, original: original},
           _context ->
      expected_state = if action_taken == :start, do: :running, else: :completed

      case Ash.get(Xaas.Ultracode.Epoch, constructed_epoch.id, authorize?: false) do
        {:ok, %{state: ^expected_state} = reloaded} ->
          {:ok,
           %{
             outcome: :alive,
             epoch: reloaded,
             original_state: original.state,
             action_taken: action_taken,
             evidence: %{
               "expected_state" => Atom.to_string(expected_state),
               "observed_state" => Atom.to_string(reloaded.state)
             }
           }}

        {:ok, mismatched} ->
          {:ok,
           %{
             outcome: :build_broken,
             epoch: mismatched,
             original_state: original.state,
             action_taken: action_taken,
             evidence: %{
               "expected_state" => Atom.to_string(expected_state),
               "observed_state" => Atom.to_string(mismatched.state)
             }
           }}

        {:error, error} ->
          {:error, {:verify_failed, error}}
      end
    end
  end


  step :receipt do
    argument(:verification, result(:verify))
    argument(:epoch, result(:observe))
    async? true

    run fn %{verification: verification, epoch: original_epoch}, _context ->
      Xaas.Ultracode.Receipt
      |> Ash.Changeset.for_create(
        :seal,
        %{
          epoch_id: original_epoch.id,
          subject: original_epoch.exact_subject,
          outcome: verification.outcome,
          evidence: verification.evidence,
          sealed_at: DateTime.utc_now()
        },
        authorize?: false
      )
      |> Ash.create()
      |> case do
        {:ok, receipt} ->
          {:ok,
           %{
             epoch_id: original_epoch.id,
             action_taken: verification.action_taken,
             outcome: verification.outcome,
             receipt_id: receipt.id
           }}

        {:error, error} ->
          {:error, {:receipt_seal_failed, error}}
      end
    end
  end


  return :receipt
end
