# GENERATED by ggen_igniter from priv/ggen/reactor-scaffold-pack/ontology.ttl.
# Do not edit. Regenerate with:
#   mix ggen_igniter.sync --pack reactor-scaffold-pack \
#     --out lib/ggen_igniter/reactors/examples/expense_approval_reactor.ex
#
# Practice/dogfood example: a full-featured plain `Reactor` (per ADR-0003,
# never Ash.Reactor) manufactured entirely from ontology data, exercising
# every construct in the real Reactor cheatsheet
# (https://reactor.hexdocs.pm/reactor-cheatsheet.html): input, step
# (argument/value/run/compensate/undo/async?/where/guard/max_retries/
# wait_for), debug, group, switch, compose, collect, map, around, template,
# middlewares, return.
defmodule Xaas.Ultracode.Probe.EpochReactor do
  @moduledoc """
  Manufactured example Reactor demonstrating the full plain-Reactor DSL
  surface documented at
  https://reactor.hexdocs.pm/reactor-cheatsheet.html — the same primitives
  `GgenIgniter.Reactors.ReconcileReactor` itself uses in production.

  Regenerate via `mix ggen_igniter.sync --pack reactor-scaffold-pack
  --out lib/ggen_igniter/reactors/examples/expense_approval_reactor.ex`.
  Never hand-edit this file — edit `priv/ggen/reactor-scaffold-pack/ontology.ttl`
  instead.
  """
  use Reactor


  input :epoch_id


  step :observe do
    argument :epoch_id, input(:epoch_id)
    async? false

    run fn %{epoch_id: epoch_id}, _context ->
      case Ash.get(Xaas.Ultracode.Epoch, epoch_id, load: [:run]) do
        {:ok, epoch} -> {:ok, epoch}
        {:error, error} -> {:error, {:observe_failed, error}}
      end
    end
  end


  step :admit do
    argument :epoch, result(:observe)
    async? false

    run fn %{epoch: epoch}, _context ->
      if epoch.state in [:expected, :running] do
        {:ok, epoch}
      else
        {:error, {:refused, :epoch_not_admissible, epoch.state}}
      end
    end
  end


  step :plan do
    argument :epoch, result(:admit)
    async? false

    run fn %{epoch: epoch}, _context ->
      next_action = if epoch.state == :expected, do: :start, else: :complete
      {:ok, next_action}
    end
  end


  step :construct do
    argument :epoch, result(:admit)
    argument :next_action, result(:plan)
    async? false

    run fn %{epoch: epoch, next_action: next_action}, _context ->
      Ash.update(epoch, %{}, action: next_action)
    end
  end


  step :verify do
    argument :epoch, result(:construct)
    argument :next_action, result(:plan)
    async? false

    run fn %{epoch: epoch, next_action: next_action}, _context ->
      expected_state = if next_action == :start, do: :running, else: :completed
      case Ash.get(Xaas.Ultracode.Epoch, epoch.id) do
        {:ok, %{state: ^expected_state}} -> {:ok, :alive}
        {:ok, _mismatched} -> {:ok, :build_broken}
        {:error, error} -> {:error, {:verify_failed, error}}
      end
    end
  end


  step :receipt do
    argument :epoch, result(:construct)
    argument :outcome, result(:verify)
    async? false

    run fn %{epoch: epoch, outcome: outcome}, _context ->
      Xaas.Ultracode.Receipt
      |> Ash.Changeset.for_create(:seal, %{
        epoch_id: epoch.id,
        subject: epoch.exact_subject,
        outcome: outcome,
        sealed_at: DateTime.utc_now()
      })
      |> Ash.create()
    end
  end


  return :receipt
end
