# GENERATED by ggen_igniter (probe run) from priv/packs/xaas_ultracode_pack/ontology.ttl.
# Falsifier for ULTRACODE-50 Semantic Manufacture Closure -- SCRATCH resource,
# does not touch the real hand-written Xaas.Ultracode.Run/Epoch.
defmodule GeneratedUltracodeProbeManifest do

  # Xaas.Ultracode.Probe.Epoch (table: ultracode_probe_epochs)
  @epoch_fields [
    "completed_at:utc_datetime_usec",
    "cycle:integer",
    "exact_subject:string",
    "expected_at:utc_datetime_usec",
    "started_at:utc_datetime_usec",
    "state:atom",
  ]

  # Xaas.Ultracode.Probe.Run (table: ultracode_probe_runs)
  @run_fields [
    "cycle:integer",
    "deadline_at:utc_datetime_usec",
    "epoch_timeout_seconds:integer",
    "goal:string",
    "last_completed_epoch_at:utc_datetime_usec",
    "last_expected_epoch_at:utc_datetime_usec",
    "max_cycles:integer",
    "standing:atom",
    "started_at:utc_datetime_usec",
    "state:atom",
  ]

end
