# ---
# Excerpted from "Engineering Elixir Applications",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material,
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose.
# Visit https://pragprog.com/titles/beamops for more book information.
# ---
# in config/dev.exs

import Config

port = String.to_integer(System.get_env("PORT") || "4000")

# Configure your database
# Real fix: username/password/hostname/port now read from env vars with the
# book's original plaintext defaults as fallback -- needed to point local
# `mix ash_postgres.generate_migrations`/`mix ecto.migrate` at the real
# running docker-compose Postgres (whose POSTGRES_PASSWORD_FILE-backed
# secret and randomly-published host port differ from the book's hardcoded
# "postgres"/5432 defaults), without hardcoding that real secret into a
# committed file.
config :xaas, Xaas.LegacyRepo,
  username: System.get_env("DEV_DB_USERNAME", "postgres"),
  password: System.get_env("DEV_DB_PASSWORD", "postgres"),
  hostname: System.get_env("DEV_DB_HOSTNAME", "localhost"),
  port: String.to_integer(System.get_env("DEV_DB_PORT", "5432")),
  database: "xaas_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# ash-migration Phase 3: Xaas.Repo is a real, separate AshPostgres.Repo (the
# 89 real Ash.Resource modules ported from ~/dev-fresh/xaas reference it
# directly via `postgres do repo Xaas.Repo end`) -- deliberately not merged
# into Xaas.LegacyRepo, same real database, separate Ecto.Repo/OTP child.
config :xaas, Xaas.Accounts.Token,
  onetime_revoke_key: System.get_env("DEV_ONETIME_REVOKE_KEY", "dev-only-onetime-revoke-key")

config :xaas, Xaas.Repo,
  username: System.get_env("DEV_DB_USERNAME", "postgres"),
  password: System.get_env("DEV_DB_PASSWORD", "postgres"),
  hostname: System.get_env("DEV_DB_HOSTNAME", "localhost"),
  port: String.to_integer(System.get_env("DEV_DB_PORT", "5432")),
  database: "xaas_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10,
  # Real fix: registers AshPostgres.Extensions.Vector's Postgrex type
  # encoding for the pgvector `vector` column type -- see the identical
  # comment in config/test.exs for why this is required.
  types: Xaas.PostgrexTypes

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with esbuild to bundle .js and .css sources.

config :xaas, XaasWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: port],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "1Tm0Lz/glhTKmCnt284nv+OUGMvuNHo1IRWYFXkafdDX3E6frvnas0DBytqhJkQQ",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:default, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:default, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :xaas, XaasWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/xaas_web/(controllers|live|components)/.*(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :xaas, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# Fabric verifier: the APS Chicago-TDD definition-of-done court. Operator-owned
# worktrees and tickets live under ~/xaas-worktrees; the court script is
# resolved from this app's priv/ (never from a worktree the worker controls).
config :xaas, :ultracode_worktree_root, Path.expand("~/xaas-worktrees/runs")
config :xaas, :ultracode_ticket_dir, Path.expand("~/xaas-worktrees/tickets")

config :xaas, :ultracode_repos, %{
  "aps" => Path.expand("~/xaas-worktrees/repos/aps"),
  # Additional operator-owned targets (wave-5): fresh clones with real test
  # suites, judged at close time by the matching <alias>-dod verifier suite.
  "nounverb" => Path.expand("~/xaas-worktrees/repos/nounverb"),
  "eds" => Path.expand("~/xaas-worktrees/repos/eds")
}

# APS's own five canonical gates, run by the fabric at the integration head.
aps_env = %{
  "PATH" => "/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin",
  "LANG" => "en_US.UTF-8",
  "PYTHONUSERBASE" => Path.expand("~/Library/Python/3.14")
}

config :xaas, :ultracode_verifier_suites, %{
  "aps-canonical" => %{
    env: aps_env,
    max_output_bytes: 16_384,
    steps: [
      %{id: "verify", timeout_ms: 120_000, argv: ["python3", "tools/verify.py", "--no-receipt"]},
      %{
        id: "unittest",
        timeout_ms: 120_000,
        argv: ["python3", "-m", "unittest", "discover", "-s", "tests"]
      },
      %{id: "ggen", timeout_ms: 120_000, argv: ["python3", "tools/verify_ggen_ecosystem.py"]},
      %{
        id: "mdbook",
        timeout_ms: 120_000,
        argv: ["/bin/sh", "-c", ~S(mdbook build -d "$TMPDIR/book" specification-guide)]
      },
      %{
        id: "simulate",
        timeout_ms: 120_000,
        argv: [
          "python3",
          "tools/simulate_fortune500.py",
          "examples/fortune500-fibo/enterprise.json"
        ]
      }
    ]
  },
  "aps-dod" => %{
    env: %{
      "PATH" => "/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin",
      "LANG" => "en_US.UTF-8",
      # rdflib lives in the user site; the verifier gives children a throwaway
      # HOME, so point Python at the real user base explicitly.
      "PYTHONUSERBASE" => Path.expand("~/Library/Python/3.14")
    },
    max_output_bytes: 65_536,
    toolchain: [["python3", "--version"], ["git", "--version"], ["mdbook", "--version"]],
    steps: [
      %{
        id: "court",
        timeout_ms: 600_000,
        infra_exit_codes: [2],
        receipt: true,
        argv: [
          "python3",
          "priv:verifiers/aps_dod_court.py",
          "--worktree",
          "{worktree}",
          "--head",
          "{head}",
          "--ticket",
          "{ticket}",
          "--executor",
          "{executor}",
          "--verifier-identity",
          "{verifier_id}"
        ]
      }
    ]
  }
}

# Non-APS targets: declared as code in Xaas.Ultracode.TargetSuites (with a
# registration-time admission gate, TargetSuites.validate/1). The value is the
# MODULE ITSELF -- only an atom at config-evaluation time -- and the verifier
# resolves and merges it at runtime, so config never depends on project
# compilation. Unset (test/prod) = registry unchanged.
config :xaas, :ultracode_target_suites, Xaas.Ultracode.TargetSuites
