# ---
# Excerpted from "Engineering Elixir Applications",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material,
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose.
# Visit https://pragprog.com/titles/beamops for more book information.
# ---
# in config/dev.exs

import Config

port = String.to_integer(System.get_env("PORT") || "4000")

# Configure your database
# Real fix: username/password/hostname/port now read from env vars with
# plaintext defaults as fallback -- env vars override without hardcoding
# real credentials into a committed file. Current dev db (observed
# 2026-09-26): native brew postgresql@14 on localhost:5432, database
# xaas_dev; a docker-compose Postgres would also work via these vars.
config :xaas, Xaas.LegacyRepo,
  username: System.get_env("DEV_DB_USERNAME", "postgres"),
  password: System.get_env("DEV_DB_PASSWORD", "postgres"),
  hostname: System.get_env("DEV_DB_HOSTNAME", "localhost"),
  port: String.to_integer(System.get_env("DEV_DB_PORT", "5432")),
  database: "xaas_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# ash-migration Phase 3: Xaas.Repo is a real, separate AshPostgres.Repo (the
# 89 real Ash.Resource modules ported from ~/dev-fresh/xaas reference it
# directly via `postgres do repo Xaas.Repo end`) -- deliberately not merged
# into Xaas.LegacyRepo, same real database, separate Ecto.Repo/OTP child.
config :xaas, Xaas.Accounts.Token,
  onetime_revoke_key: System.get_env("DEV_ONETIME_REVOKE_KEY", "dev-only-onetime-revoke-key")

config :xaas, Xaas.Repo,
  username: System.get_env("DEV_DB_USERNAME", "postgres"),
  password: System.get_env("DEV_DB_PASSWORD", "postgres"),
  hostname: System.get_env("DEV_DB_HOSTNAME", "localhost"),
  port: String.to_integer(System.get_env("DEV_DB_PORT", "5432")),
  database: "xaas_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10,
  # Real fix: registers AshPostgres.Extensions.Vector's Postgrex type
  # encoding for the pgvector `vector` column type -- see the identical
  # comment in config/test.exs for why this is required.
  types: Xaas.PostgrexTypes

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with esbuild to bundle .js and .css sources.

config :xaas, XaasWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: port],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "1Tm0Lz/glhTKmCnt284nv+OUGMvuNHo1IRWYFXkafdDX3E6frvnas0DBytqhJkQQ",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:default, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:default, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :xaas, XaasWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/xaas_web/(controllers|live|components)/.*(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :xaas, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# Fabric verifier: the APS Chicago-TDD definition-of-done court. Operator-owned
# worktrees and tickets live under ~/xaas/worktrees; the court script is
# resolved from this app's priv/ (never from a worktree the worker controls).
config :xaas, :ultracode_worktree_root, Path.expand("~/xaas/worktrees/runs")
config :xaas, :ultracode_ticket_dir, Path.expand("~/xaas/worktrees/tickets")

# Wave-loop surfaces for the CRON path (2026-09-26 burn-in wiring): the
# AshOban `:wave_loop` schedule's action runner calls
# `Xaas.Ultracode.WaveLoop.tick/1` with NO opts, so the loop's STATE and
# telemetry paths resolve through these app-env seams (WaveLoop moduledoc).
# The manual burn-in drivers passed explicit `state_path:`/`telemetry_path:`
# opts, which the cron path cannot do -- without these, every cron tick
# lands on the module defaults (~/xaas/tmp/w8-loop/...; last ticked 09-21)
# and can never advance the live burn-in STATE. Env-overridable per this
# file's DEV_DB_* convention; unset env keeps the module defaults.
config :xaas,
       :ultracode_wave_loop_state_path,
       System.get_env("ULTRACODE_WAVE_LOOP_STATE_PATH", "/Users/sac/xaas/tmp/w8-loop/STATE.md")

config :xaas,
       :ultracode_wave_loop_telemetry_path,
       System.get_env(
         "ULTRACODE_WAVE_LOOP_TELEMETRY_PATH",
         "/Users/sac/xaas/tmp/w8-loop/loop.ndjson"
       )

# Multi-repo registry (Xaas.Ultracode.Repos). This env entry is the
# code-seeded baseline; durable operator registrations -- other campaign
# targets -- live in the registry file written ONLY by
# `mix xaas.ultracode.repos --register` and merged over this baseline
# (file wins per alias).
config :xaas, :ultracode_repos_file, Path.expand("~/xaas/worktrees/ultracode-repos.json")

config :xaas, :ultracode_repos, %{
  # Structured form: the entry names its own suite/sensing facts.
  "aps" => %{
    path: Path.expand("~/xaas/worktrees/repos/aps"),
    sensing: "aps",
    suite: "aps-dod",
    canonical_suite: "aps-canonical"
  },
  # Additional operator-owned targets (wave-5 onward): fresh clones with real
  # test suites, judged at close time by the matching <alias>-dod verifier
  # suite. Structured entries NAME their suite facts (the historical
  # path-string default -- aps-dod/aps-canonical -- is correct for aps only).
  "nounverb" => %{
    path: Path.expand("~/xaas/worktrees/repos/nounverb"),
    sensing: "nounverb",
    suite: "nounverb-dod",
    canonical_suite: "nounverb-dod"
  },
  "eds" => %{
    path: Path.expand("~/xaas/worktrees/repos/eds"),
    sensing: "eds",
    suite: "eds-dod",
    canonical_suite: "eds-dod"
  },
  "spr" => Path.expand("~/xaas/worktrees/repos/spr"),
  # SJ-program targets (`git clone --local` of the operator checkouts; each
  # opts in to `refresh` so a stale clone is fetched + fast-forwarded before
  # the loop pins base_sha). Sensing names resolve to the declared profiles
  # below; suites are declared as code in Xaas.Ultracode.TargetSuites.
  "xaas" => %{
    path: Path.expand("~/xaas/worktrees/repos/xaas"),
    sensing: "xaas-sjira",
    suite: "xaas-dod",
    canonical_suite: "xaas-canonical",
    refresh: true
  },
  "autofde-lab" => %{
    path: Path.expand("~/xaas/worktrees/repos/autofde-lab"),
    sensing: "autofde-lab-jira",
    suite: "autofde-lab-dod",
    canonical_suite: "autofde-lab-canonical",
    refresh: true
  },
  "gymact" => %{
    path: Path.expand("~/xaas/worktrees/repos/gymact"),
    sensing: "gymact-jira",
    suite: "gymact-dod",
    canonical_suite: "gymact-canonical",
    refresh: true
  },
  "ggen-igniter" => %{
    path: Path.expand("~/xaas/worktrees/repos/ggen-igniter"),
    sensing: "ggen-igniter-jira",
    suite: "ggen-igniter-dod",
    canonical_suite: "ggen-igniter-canonical",
    refresh: true
  },
  # Composition roots (2026-09-30). `ggen-ecosystem` is the ggen manufacturer
  # root; `gym-ecosystem` the gym composition root that pins it (plus gymact,
  # autofde-lab, beam4pm) as gitlinks. Sensing is failing-court derived (their
  # tickets carry no `## Status` section); suites are declared in
  # Xaas.Ultracode.TargetSuites.sj_program_suites/0.
  "ggen-ecosystem" => %{
    path: Path.expand("~/xaas/worktrees/repos/ggen-ecosystem"),
    sensing: "ggen-ecosystem-courts",
    suite: "ggen-ecosystem-dod",
    canonical_suite: "ggen-ecosystem-canonical",
    refresh: true
  },
  "gym-ecosystem" => %{
    path: Path.expand("~/xaas/worktrees/repos/gym-ecosystem"),
    sensing: "gym-ecosystem-courts",
    suite: "gym-ecosystem-dod",
    canonical_suite: "gym-ecosystem-canonical",
    refresh: true
  },
  # Owned public Ash packages (2026-09-30). RESERVED targets: the registry
  # entries are real; `sensing` and suite names are deliberate Reservation-law
  # gaps (see Xaas.Ultracode.Repos) -- none of these repos' tickets carry a
  # `## Status` section (jira_dir would sense nothing) and no suite argv has
  # been executed yet, so dispatch fails closed at `VerifierSuiteRegistered`
  # until each is registered with an observed-exit argv. Construction of any
  # Ash surface stays on the ggen_igniter ash-manufacture-pack route.
  "ash_a2a" => %{
    path: Path.expand("~/xaas/worktrees/repos/ash_a2a"),
    sensing: "ash_a2a-courts",
    suite: "ash_a2a-dod",
    canonical_suite: "ash_a2a-canonical",
    refresh: true
  },
  "ash_graphlaw" => %{
    path: Path.expand("~/xaas/worktrees/repos/ash_graphlaw"),
    sensing: "ash_graphlaw-courts",
    suite: "ash_graphlaw-dod",
    canonical_suite: "ash_graphlaw-canonical",
    refresh: true
  },
  "ash_pplan" => %{
    path: Path.expand("~/xaas/worktrees/repos/ash_pplan"),
    sensing: "ash_pplan-courts",
    suite: "ash_pplan-dod",
    canonical_suite: "ash_pplan-canonical",
    refresh: true
  },
  "ash_r2rml" => %{
    path: Path.expand("~/xaas/worktrees/repos/ash_r2rml"),
    sensing: "ash_r2rml-courts",
    suite: "ash_r2rml-dod",
    canonical_suite: "ash_r2rml-canonical",
    refresh: true
  },
  "ash_surface" => %{
    path: Path.expand("~/xaas/worktrees/repos/ash_surface"),
    sensing: "ash_surface-courts",
    suite: "ash_surface-dod",
    canonical_suite: "ash_surface-canonical",
    refresh: true
  },
  "ash_n8n" => %{
    path: Path.expand("~/xaas/worktrees/repos/ash_n8n"),
    sensing: "ash_n8n-courts",
    suite: "ash_n8n-dod",
    canonical_suite: "ash_n8n-canonical",
    refresh: true
  },
  "ash_planning_center" => %{
    path: Path.expand("~/xaas/worktrees/repos/ash_planning_center"),
    sensing: "ash_planning_center-courts",
    suite: "ash_planning_center-dod",
    canonical_suite: "ash_planning_center-canonical",
    refresh: true
  },
  "ash_expo" => %{
    path: Path.expand("~/xaas/worktrees/repos/ash_expo"),
    sensing: "ash_expo-courts",
    suite: "ash_expo-dod",
    canonical_suite: "ash_expo-canonical",
    refresh: true
  },
  "ash_dspy" => %{
    path: Path.expand("~/xaas/worktrees/repos/ash_dspy"),
    sensing: "ash_dspy-courts",
    suite: "ash_dspy-dod",
    canonical_suite: "ash_dspy-canonical",
    refresh: true
  },
  "ash_ex4pm" => %{
    path: Path.expand("~/xaas/worktrees/repos/ash_ex4pm"),
    sensing: "ash_ex4pm-courts",
    suite: "ash_ex4pm-dod",
    canonical_suite: "ash_ex4pm-canonical",
    refresh: true
  }
}

# Per-repo sense scripts (`Xaas.Ultracode.Autonomic.backlog_script/1`): the
# SPR family derives Chicago-school negative-test items from the public
# functions of its root tool module; the eds and nounverb families derive
# them from their package/CLI public surface (eds: every src/eds module,
# nounverb: the lib/ex_noun_verb_cli Elixir modules); APS keeps its default
# script.
config :xaas, :ultracode_backlog_scripts, %{
  "spr" => "spr_backlog.py",
  "eds" => "eds_backlog.py",
  "nounverb" => "nounverb_backlog.py",
  # Profile-owned sensing: the default aps_backlog.py exits 0 with no items on
  # these repos and would shadow their failing-court profiles. This sentinel
  # exits 2 so sense_one/4 falls back to the registry entry's profile.
  "ggen-ecosystem" => "profile_sensing_only.py",
  "gym-ecosystem" => "profile_sensing_only.py"
}

# Sensing-profile names -> deterministic profiles (`Xaas.Ultracode.Sensing.
# profile/1`): the Autonomic sense stage's fallback when a repo's backlog
# script fails (xaas has no fitting script; the aps default exits 2 on it).
# "xaas-sjira" reads the xaas clone's own docs/sjira tickets: open = the
# `## Status` section's first word NOT in `closed`; BLOCKED tickets are real
# but not worker-workable, so they are closed to the wave.
config :xaas, :ultracode_sensing_profiles, %{
  "xaas-sjira" => %{
    "type" => "jira_dir",
    "dir" => "docs/sjira",
    "closed" => ["DONE", "MERGED", "LANDED", "CLOSED", "RESOLVED", "ALIVE", "BLOCKED"]
  },
  "autofde-lab-jira" => %{"type" => "jira_dir", "dir" => "docs/jira"},
  "gymact-jira" => %{"type" => "jira_dir", "dir" => "docs/jira"},
  # ggen-igniter's older tickets carry free-form bold statuses; the profile's
  # own `closed` option lists the completion words actually used there, so the
  # loop is not pointed at work that is already done (PLANNED and
  # PARTIAL_ALIVE stay open).
  "ggen-igniter-jira" => %{
    "type" => "jira_dir",
    "dir" => "docs/jira",
    "closed" =>
      ~w(DONE MERGED LANDED CLOSED RESOLVED ALIVE COMPLETE. **EXECUTED **EXECUTED.** **REWRITTEN **IMPLEMENTED)
  },
  # ggen-ecosystem: one item per failing unittest in its own discover surface
  # (stdlib unittest, no network, ~2s; non-zero exit is the expected "failing"
  # signal). Parameterized subtests carry their `(case='...')` in the id.
  "ggen-ecosystem-courts" => %{
    "type" => "failing_tests",
    "command" => [
      "python3",
      "-m",
      "unittest",
      "discover",
      "-s",
      "tests",
      "-t",
      ".",
      "-p",
      "test_*.py"
    ],
    "parser" => "regex",
    "pattern" => "^(?:FAIL|ERROR): (?<id>.+)$",
    "timeout_ms" => 300_000
  },
  # gym-ecosystem: gitlink/lock provenance court. Every reported line is
  # `<vendor path>: <reason>` after a PROVENANCE_BLOCKED header; ALIVE => no items.
  "gym-ecosystem-courts" => %{
    "type" => "failing_tests",
    "command" => ["bash", "scripts/verify-provenance.sh"],
    "parser" => "regex",
    "pattern" =>
      "^(?<id>(?:vendor/\\S+|[a-z0-9_-]+): (?:missing|locked|declared|mode=|gitlink=|checkout=).*)$",
    "timeout_ms" => 120_000
  }
}

# APS's own five canonical gates, run by the fabric at the integration head.
aps_env = %{
  "PATH" => "/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin",
  "LANG" => "en_US.UTF-8",
  "PYTHONUSERBASE" => Path.expand("~/Library/Python/3.14")
}

config :xaas, :ultracode_verifier_suites, %{
  "aps-canonical" => %{
    env: aps_env,
    max_output_bytes: 16_384,
    steps: [
      %{id: "verify", timeout_ms: 120_000, argv: ["python3", "tools/verify.py", "--no-receipt"]},
      %{
        id: "unittest",
        timeout_ms: 120_000,
        argv: ["python3", "-m", "unittest", "discover", "-s", "tests"]
      },
      %{id: "ggen", timeout_ms: 120_000, argv: ["python3", "tools/verify_ggen_ecosystem.py"]},
      %{
        id: "mdbook",
        timeout_ms: 120_000,
        argv: ["/bin/sh", "-c", ~S(mdbook build -d "$TMPDIR/book" specification-guide)]
      },
      %{
        id: "simulate",
        timeout_ms: 120_000,
        argv: [
          "python3",
          "tools/simulate_fortune500.py",
          "examples/fortune500-fibo/enterprise.json"
        ]
      }
    ]
  },
  "aps-dod" => %{
    env: %{
      "PATH" => "/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin",
      "LANG" => "en_US.UTF-8",
      # rdflib lives in the user site; the verifier gives children a throwaway
      # HOME, so point Python at the real user base explicitly.
      "PYTHONUSERBASE" => Path.expand("~/Library/Python/3.14")
    },
    max_output_bytes: 65_536,
    toolchain: [["python3", "--version"], ["git", "--version"], ["mdbook", "--version"]],
    steps: [
      %{
        id: "court",
        timeout_ms: 600_000,
        infra_exit_codes: [2],
        receipt: true,
        argv: [
          "python3",
          "priv:verifiers/aps_dod_court.py",
          "--worktree",
          "{worktree}",
          "--head",
          "{head}",
          "--ticket",
          "{ticket}",
          "--executor",
          "{executor}",
          "--verifier-identity",
          "{verifier_id}"
        ]
      }
    ]
  },

  # TEMPORARY OPERATIONAL PATCH (wave-5 W5-A7, 2026-09-20, uncommitted by
  # design: the committed mechanism for non-APS suites is Xaas.Ultracode.
  # TargetSuites on feat/ultracode-cron-wave @ a3bd1a9; the RUNNING server
  # here predates it, so the spr-dod court is registered old-shape until the
  # server's next real deploy). SPR's definition of done: its own pytest
  # suite green at the closed head.
  "spr-dod" => %{
    env: %{
      "PATH" => "/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin",
      "LANG" => "en_US.UTF-8"
    },
    max_output_bytes: 16_384,
    toolchain: [["python3", "--version"], ["git", "--version"]],
    steps: [
      %{
        id: "test",
        timeout_ms: 300_000,
        argv: [
          "python3",
          "-m",
          "pytest",
          "tests",
          "--basetemp",
          "{tmpdir}",
          "-q",
          "-p",
          "no:cacheprovider"
        ]
      }
    ]
  }
}

# Non-APS targets: declared as code in Xaas.Ultracode.TargetSuites (with a
# registration-time admission gate, TargetSuites.validate/1). The value is the
# MODULE ITSELF -- only an atom at config-evaluation time -- and the verifier
# resolves and merges it at runtime, so config never depends on project
# compilation. Unset (test/prod) = registry unchanged.
config :xaas, :ultracode_target_suites, Xaas.Ultracode.TargetSuites

# ash_a2a 26.9.28 boots under a strict security preflight; dev/test have no durable outbox,
# authority broker or kill-switch class. prod stays :strict (compile_env default).
config :ash_a2a, :security_profile, :legacy_compat
