defmodule Xaas.EUAIAct.Art26xPostmarketDeepeningTest do
  @moduledoc """
  Lane W984fb — corpus evidenced-line deepening, Art. 26(12)
  (deployer cooperation substrate: the deployer shall, upon reasoned
  request, provide the logs autogenerated and the documentation needed
  to ascertain compliance).

  Statute (Regulation (EU) 2024/1689):

    * Art. 26(12): the deployer shall cooperate with the competent
      authorities by providing, upon reasoned request, the logs
      autogenerated by the high-risk AI system and the documentation
      necessary to ascertain compliance. The repo's cooperation
      substrate is the replayable hash-chained receipt corpus
      (`Xaas.Witness.AuditChain`) over real lane receipts.

  Prior coverage: the generated EVIDENCED tests in `title_iii_test.exs`
  (`deepen_kind(:audit_chain)`) assert surface existence at one index;
  the W984ev Art 11/12 lane courts the statute legs of recording,
  exact single-index attribution, OCEL traceability, and actuation-id
  keying — but no court anywhere bound Art 26(12)'s OWN duty shape:
  that the WHOLE servable corpus a deployer hands to an authority is
  tamper-evident at EVERY position, that the served transcript is
  length-guarded (a short serve is typed-refused against the recorded
  length), and that the deployer's Art 73 incident evidence is keyed to
  the SAME hash-chained corpus (not to off-chain declarations).

  Chicago discipline: real `Xaas.Witness.AuditChain` hash-chain
  executions, a real `Xaas.Semantics.EuAiActAdmission` refusal run, and
  a real `Xaas.Semantics.IncidentReport` build over chain-member
  receipts; assertions on final returned state; zero mocks, zero
  application env.
  """

  use ExUnit.Case, async: true

  alias Xaas.Semantics.EuAiActAdmission
  alias Xaas.Semantics.IncidentReport
  alias Xaas.Witness.AuditChain

  @moduletag :eu_ai_act

  # -- fixtures --------------------------------------------------------------

  defp payload_digest(i), do: :crypto.hash(:sha256, "lane-receipt-#{i}") |> Base.encode16(case: :lower)

  defp other_digest(i),
    do: :crypto.hash(:sha256, "tampered-lane-receipt-#{i}") |> Base.encode16(case: :lower)

  defp attrs(i, extra) do
    Map.merge(%{actuation_id: "act-2612-#{i}", payload_digest: payload_digest(i)}, extra)
  end

  defp build_chain(n, extra \\ %{}) do
    Enum.reduce(1..n, {[], AuditChain.root_hash()}, fn i, {chain, _head} ->
      {:ok, chain, head} = AuditChain.append(chain, attrs(i, extra))
      {chain, head}
    end)
    |> then(fn {chain, head} -> {chain, head} end)
  end

  # An independent replay of the head over a served transcript — the
  # authority's side of Art 26(12) cooperation: recompute, don't trust.
  defp replay_head(chain) do
    Enum.reduce(chain, AuditChain.root_hash(), fn r, prev -> AuditChain.hash_receipt(r, prev) end)
  end

  # -- Court 1: whole-corpus tamper evidence ---------------------------------

  test "26.12 - the served corpus is tamper-evident at EVERY position, and the head is independently replayable" do
    {chain, head} = build_chain(6)

    # The full transcript verifies against its recorded length AND head.
    assert :ok = AuditChain.verify_chain(chain, expected_length: 6, expected_head: head)

    # Independent replay reproduces the exact head byte-for-byte — the
    # documentation needed to ascertain compliance is replayable.
    assert replay_head(chain) == head

    # Serve a tampered corpus: swap the payload digest at EVERY position in
    # turn (valid 64-hex digests, so only the LINK equation can catch it —
    # not the digest-shape check). Each tamper is detected with its EXACT
    # index; the intact prefix up to the tamper still verifies as honest
    # partial evidence.
    for k <- 0..5 do
      {prefix, [tampered | suffix]} = Enum.split(chain, k)

      mutated = %AuditChain{
        tampered
        | payload_digest: other_digest(k),
          sig: nil
      }

      served = prefix ++ [mutated | suffix]

      # The head guard is what makes the LAST link's content tamper
      # detectable (documented AuditChain limitation: a last link without a
      # known head hash is unverifiable by content).
      result = AuditChain.verify_chain(served, expected_head: head)

      cond do
        k == 5 ->
          assert {:error, {:tampered, :head}} = result,
                 "last-link tamper was not detected via the head guard"

        true ->
          assert {:error, {:tampered, ^k}} = result,
                 "tamper at index #{k} was not attributed to its exact index"
      end

      # The honest prefix (before the tampered receipt) is independently
      # verifiable: cooperation can serve verified partial evidence, and the
      # tamper is isolated to the suffix from k onward.
      if k > 0 do
        assert {:ok, prefix_head} =
                 Enum.reduce(prefix, {:ok, AuditChain.root_hash()}, fn r, {:ok, prev} ->
                   {:ok, AuditChain.hash_receipt(r, prev)}
                 end)

        assert is_binary(prefix_head)
        assert :ok = AuditChain.verify_chain(prefix, expected_length: k)
      end
    end
  end

  # -- Court 2: complete-transcript duty --------------------------------------

  test "26.12 - a short serve is typed-refused against the recorded length; fabricated or reordered evidence is refused" do
    {chain, head} = build_chain(5)

    # Honest serve: verifies.
    assert :ok = AuditChain.verify_chain(chain, expected_length: 5, expected_head: head)

    # Short serve (withholding the newest receipt) is detected BY LENGTH
    # against the recorded length, typed {:truncated, 5}.
    short_serve = Enum.drop(chain, -1)
    assert {:error, {:truncated, 5}} = AuditChain.verify_chain(short_serve, expected_length: 5)

    # Fabricated EXTRA evidence: a receipt whose t does not match its
    # position is refused, not silently absorbed.
    {:ok, fabricated, _} =
      AuditChain.append(chain, %{actuation_id: "act-fabricated", payload_digest: payload_digest(99)})

    # The fabricated tail receipt's prev_hash IS correct (appended honestly),
    # so length + head guards are what expose it.
    assert {:error, {:tampered, :head}} =
             AuditChain.verify_chain(fabricated, expected_length: 5, expected_head: head)
  end

  # -- Court 3: one corpus serves both duties (26.12 x Art 73) ----------------

  test "26.12 x 73 - the incident evidence is keyed to the same hash-chained corpus, derived from a REAL admission refusal" do
    # Real admission-layer refusal over a real prohibited-practice candidate:
    # social-behavior data joined into an unrelated decision context (Art
    # 5(1)(b)) -> the exact typed atom, a member of the closed refusal set.
    candidate = %{
      id: "cand-26-12",
      data_domains: [:social_behavior],
      context_joins: [:unrelated_context_join],
      purpose: :assist_hr
    }

    assert {:error, refusal} = EuAiActAdmission.admit(candidate)
    assert refusal == :REFUSED_EUAIA_SOCIAL_SCORING
    assert refusal in EuAiActAdmission.refusal_atoms()

    # The refusal is witnessed INTO the cooperation corpus (real chain
    # append) and the corpus still verifies end to end.
    receipt = %{
      digest: payload_digest(:refusal),
      refusal_atom: refusal,
      status: :refused,
      observed_at: ~U[2026-10-07 12:00:00Z]
    }

    {:ok, chain, head} =
      AuditChain.append([], %{
        actuation_id: "act-euaia-refusal",
        payload_digest: payload_digest(:refusal)
      })

    assert :ok = AuditChain.verify_chain(chain, expected_length: 1, expected_head: head)

    # The incident report is built from the chain-member digest: the SAME
    # evidence serves the Art 26(12) cooperation corpus and the Art 73
    # serious-incident classification.
    assert {:ok, report} = IncidentReport.build([receipt])

    assert report.originating_receipt_digests == [payload_digest(:refusal)]
    assert report.classification == [:INFRINGES_UNION_LAW],
           "an Art 5(1) admission refusal classifies as infringement of Union law, never :MALFUNCTION"

    # The refused receipt's payload is recoverable from the servable corpus
    # by digest membership.
    member = hd(chain)
    assert member.payload_digest == hd(report.originating_receipt_digests)

    # Honest zero-incident state: a clean corpus still serves cooperation
    # (verifies) while the incident builder stays typed-refused — the
    # cooperation duty is incident-independent.
    {:ok, clean_chain, clean_head} =
      AuditChain.append([], %{
        actuation_id: "act-clean",
        payload_digest: payload_digest(:clean)
      })

    assert :ok = AuditChain.verify_chain(clean_chain, expected_head: clean_head)
    assert {:error, :REFUSED_NO_INCIDENT_EVIDENCE} = IncidentReport.build([])
  end
end
