defmodule Xaas.Repo.Migrations.AddOrgSuspensionReason do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`.

  Manually reviewed and trimmed: the autogenerated diff also included an
  unrelated `autofde_planner_cache_stats_requests.cache_hit?` column
  removal -- real, pre-existing drift between that resource's code (which
  already has no `cache_hit?` attribute) and the live DB schema, unrelated
  to this migration's own `Xaas.Accounts.Org` change. Per this session's
  own established discipline, that stale/unrelated diff is excluded here,
  not silently applied alongside this real, scoped schema change. The
  corresponding autogenerated resource snapshot for that resource was
  likewise reverted (not committed as this migration's own baseline).
  """

  use Ecto.Migration

  def up do
    alter table(:orgs) do
      add :suspension_reason, :text
    end
  end

  def down do
    alter table(:orgs) do
      remove :suspension_reason
    end
  end
end
