defmodule Xaas.Repo.Migrations.ResolvePendingBacklog20260821 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`.

  The AutoFDE planner request tables are intentionally not recreated here.
  They already have earlier dedicated migrations in this same history:
  `20260821032800_create_autofde_planner_match_requests.exs`,
  `20260821035000_create_autofde_planner_cache_stats_requests.exs`, and
  `20260821035100_create_autofde_planner_cache_hotset_requests.exs`.

  Webhook secret storage is likewise intentionally not reconverged here.
  `20260821031500_fix_webhook_secret_encryption_column.exs` already owns the
  `platform_webhooks.secret -> encrypted_secret` transition and admits both
  predecessor shapes with `IF EXISTS`/`IF NOT EXISTS`. Repeating the same
  generated rename later in the migration chain fails on a clean database
  because the plaintext column has already been removed.

  The remaining token transition is independent and is retained here because
  `Xaas.Accounts.Token` cloaks `:extra_data` and no earlier migration in this
  history owns its `encrypted_extra_data` storage transition.
  """

  use Ecto.Migration

  def up do
    alter table(:tokens) do
      add :encrypted_extra_data, :binary
      remove :extra_data
    end
  end

  def down do
    alter table(:tokens) do
      add :extra_data, :map
      remove :encrypted_extra_data
    end
  end
end
