defmodule Xaas.Repo.Migrations.AddPaperTrailTo4GovernanceResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  then hand-trimmed: the raw generator output also proposed 4
  `autofde_planner_*` tables (a concurrent peer session's in-flight work,
  not this batch's) and stale `platform_webhooks.secret` /
  `tokens.extra_data` encrypted-rename operations already covered by
  `priv/repo/migrations/20260821024131_batch5_iam_cloak.exs` per that
  file's documented precedent. Only the 4 real `*_versions` tables for
  this batch's `AshPaperTrail` wiring on the 4 Governance `Approval*`
  resources remain below.
  """

  use Ecto.Migration

  def up do
    create table(:approval_backup_retention_changes_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :org_id, :text, null: false

      add :version_source_id,
          references(:approval_backup_retention_changes,
            column: :id,
            name: "approval_backup_retention_changes_versions_version_source_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:approval_deployment_quarantines_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :org_id, :text, null: false

      add :version_source_id,
          references(:approval_deployment_quarantines,
            column: :id,
            name: "approval_deployment_quarantines_versions_version_source_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:approval_legal_hold_releases_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :org_id, :text

      add :version_source_id,
          references(:approval_legal_hold_releases,
            column: :id,
            name: "approval_legal_hold_releases_versions_version_source_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:approval_dr_failovers_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :org_id, :text, null: false

      add :version_source_id,
          references(:approval_dr_failovers,
            column: :id,
            name: "approval_dr_failovers_versions_version_source_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop constraint(
           :approval_dr_failovers_versions,
           "approval_dr_failovers_versions_version_source_id_fkey"
         )

    drop table(:approval_dr_failovers_versions)

    drop constraint(
           :approval_legal_hold_releases_versions,
           "approval_legal_hold_releases_versions_version_source_id_fkey"
         )

    drop table(:approval_legal_hold_releases_versions)

    drop constraint(
           :approval_deployment_quarantines_versions,
           "approval_deployment_quarantines_versions_version_source_id_fkey"
         )

    drop table(:approval_deployment_quarantines_versions)

    drop constraint(
           :approval_backup_retention_changes_versions,
           "approval_backup_retention_changes_versions_version_source_id_fkey"
         )

    drop table(:approval_backup_retention_changes_versions)
  end
end
