defmodule Xaas.Repo.Migrations.AddArchivalToUser do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :archived_at, :utc_datetime_usec
    end

    create table(:approval_freeze_overrides_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false

      add :version_source_id,
          references(:approval_freeze_overrides,
            column: :id,
            name: "approval_freeze_overrides_versions_version_source_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    alter table(:approval_environment_promotes) do
      add :status, :text, null: false, default: "pending"
    end
  end

  def down do
    alter table(:approval_environment_promotes) do
      remove :status
    end

    drop constraint(
           :approval_freeze_overrides_versions,
           "approval_freeze_overrides_versions_version_source_id_fkey"
         )

    drop table(:approval_freeze_overrides_versions)

    alter table(:users) do
      remove :archived_at
    end
  end
end
