defmodule Xaas.Repo.Migrations.AddAuditLogEntry do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`.

  Real, deliberate edit after generation: the raw autogenerated migration
  bundled in several unrelated pending schema changes from other
  in-flight/parallel work on this shared repo (new
  `autofde_planner_cache_stats_requests` /
  `autofde_planner_match_requests` / `autofde_planner_cache_hotset_requests`
  tables, and the known-stale `platform_webhooks.secret ->
  encrypted_secret` / `tokens.extra_data -> encrypted_extra_data` cloak
  renames already covered by their own prior migrations/precedent). This
  migration is trimmed to only the real schema change this task actually
  needs: creating `audit_log_entries`.
  """

  use Ecto.Migration

  def up do
    create table(:audit_log_entries, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :actor_id, :text
      add :actor_description, :text
      add :action, :text, null: false
      add :resource_type, :text, null: false
      add :resource_id, :text, null: false
      add :org_id, :text

      add :occurred_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :metadata, :map, default: %{}
    end
  end

  def down do
    drop table(:audit_log_entries)
  end
end
