defmodule Xaas.Repo.Migrations.AddUltracodeRunEpochReceipt do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:ultracode_runs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :goal, :text, null: false
      add :state, :text, null: false, default: "pending"
      add :standing, :text, null: false, default: "unknown"
      add :started_at, :utc_datetime_usec
      add :deadline_at, :utc_datetime_usec
      add :cycle, :bigint, null: false, default: 0
      add :max_cycles, :bigint, null: false, default: 1
      add :last_expected_epoch_at, :utc_datetime_usec
      add :last_completed_epoch_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:ultracode_receipts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :subject, :text, null: false
      add :outcome, :text, null: false
      add :evidence, :map, null: false, default: %{}

      add :sealed_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :epoch_id, :uuid, null: false
    end

    create table(:ultracode_epochs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:ultracode_receipts) do
      modify :epoch_id,
             references(:ultracode_epochs,
               column: :id,
               name: "ultracode_receipts_epoch_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:ultracode_epochs) do
      add :cycle, :bigint, null: false
      add :exact_subject, :text, null: false
      add :state, :text, null: false, default: "expected"
      add :started_at, :utc_datetime_usec
      add :completed_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :run_id,
          references(:ultracode_runs,
            column: :id,
            name: "ultracode_epochs_run_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:ultracode_epochs, [:run_id, :cycle],
             name: "ultracode_epochs_unique_run_cycle_index"
           )
  end

  def down do
    drop constraint(:ultracode_epochs, "ultracode_epochs_run_id_fkey")

    drop_if_exists unique_index(:ultracode_epochs, [:run_id, :cycle],
                     name: "ultracode_epochs_unique_run_cycle_index"
                   )

    alter table(:ultracode_epochs) do
      remove :run_id
      remove :updated_at
      remove :inserted_at
      remove :completed_at
      remove :started_at
      remove :state
      remove :exact_subject
      remove :cycle
    end

    drop constraint(:ultracode_receipts, "ultracode_receipts_epoch_id_fkey")

    alter table(:ultracode_receipts) do
      modify :epoch_id, :uuid
    end

    drop table(:ultracode_epochs)

    drop table(:ultracode_receipts)

    drop table(:ultracode_runs)
  end
end
