defmodule Xaas.Repo.Migrations.EpochTimeoutDefault900 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:ultracode_runs) do
      modify :epoch_timeout_seconds, :bigint, default: 900
    end
  end

  def down do
    alter table(:ultracode_runs) do
      modify :epoch_timeout_seconds, :bigint, default: 300
    end
  end
end
