defmodule Xaas.Repo.Migrations.AddBackupRetentionChangeTier do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  # Real, deliberate exclusion (same real gap as
  # 20260820235809_add_backup_retention_change_columns.exs): the codegen
  # again proposed renaming tokens.extra_data -> tokens.encrypted_extra_data.
  # Xaas.Accounts.Token's own code still declares `attribute :extra_data,
  # :map` (unchanged this session) -- stale resource-snapshot drift, not a
  # real code change, and a destructive PII-column rename. Excluded per
  # this repo's never-blindly-touch-sensitive-resources discipline.
  def up do
    alter table(:approval_backup_retention_changes) do
      add :tier, :text, null: false
    end
  end

  def down do
    alter table(:approval_backup_retention_changes) do
      remove :tier
    end
  end
end
