defmodule Xaas.Repo.Migrations.AddTemporalMemoryObservations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:temporal_memory_observations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :subject_type, :text, null: false
      add :subject_id, :text, null: false
      add :fact, :map, null: false, default: %{}
      add :valid_from, :utc_datetime_usec, null: false
      add :valid_to, :utc_datetime_usec
      add :observed_at, :utc_datetime_usec, null: false
      add :supersedes_id, :uuid
      add :superseded_by_id, :uuid
      add :receipt_hash, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:temporal_memory_observations, [:receipt_hash],
             name: "temporal_memory_observations_unique_receipt_hash_index"
           )
  end

  def down do
    drop_if_exists unique_index(:temporal_memory_observations, [:receipt_hash],
                     name: "temporal_memory_observations_unique_receipt_hash_index"
                   )

    drop table(:temporal_memory_observations)
  end
end
