defmodule Xaas.Repo.Migrations.AddPgvectorBookEmbedding do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:library_books) do
      modify :embedding, :vector, size: 384
    end
  end

  def down do
    alter table(:library_books) do
      modify :embedding, {:array, :float}
    end
  end
end
