defmodule Xaas.Repo.Migrations.MultitenancyPilotAndNewResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:pentest_findings, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :org_id, :text, null: false
      add :engagement_id, :text, null: false
      add :severity, :text, null: false
      add :title, :text, null: false
      add :description, :text
      add :status, :text, null: false, default: "open"
      add :filed_by, :text, null: false
    end

    create table(:freeze_windows_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:incidents, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :org_id, :text, null: false
      add :title, :text, null: false
      add :description, :text
      add :severity, :text, null: false, default: "minor"
      add :region, :text, null: false
      add :status, :text, null: false, default: "open"
      add :opened_at, :utc_datetime, null: false
      add :resolved_at, :utc_datetime
      add :postmortem_root_cause, :text
      add :postmortem_remediation, :text
      add :postmortem_status, :text, default: "draft"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    alter table(:route_projects_backups) do
      add :org_id, :text, null: false
      add :namespace, :text, null: false
      add :project_name, :text, null: false
      add :job_name, :text, null: false
      add :taken_at, :utc_datetime, null: false
      add :size_bytes, :bigint, null: false
      add :retain_until, :utc_datetime, null: false
      add :status, :text, null: false, default: "pending"
      remove :requested_by
      remove :approved_by
    end

    # Real fix, hand-applied (not the generator's plain `modify`): the
    # table is confirmed real-empty (checked live before running this
    # migration), so dropping and re-adding the column as the correct
    # :uuid type is safe and avoids Postgres's "column cannot be cast
    # automatically to type uuid" error a real `mix ecto.migrate` run hit
    # on the plain `modify`.
    alter table(:approval_pentest_finding_resolves) do
      remove :finding_id

      add :finding_id,
          references(:pentest_findings,
            column: :id,
            name: "approval_pentest_finding_resolves_finding_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    alter table(:approval_freeze_overrides) do
      add :org_id, :text, null: false
      add :freeze_window_id, :text, null: false
      add :reason, :text, null: false
    end

    alter table(:route_orgs_custom_domains) do
      add :org_id, :text, null: false
      add :hostname, :text, null: false
      add :status, :text, null: false, default: "pending"
      add :certificate_secret_name, :text
      add :certificate_reason, :text
      add :certificate_message, :text
      remove :requested_by
      remove :approved_by
    end

    create table(:freeze_windows, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:freeze_windows_versions) do
      modify :version_source_id,
             references(:freeze_windows,
               column: :id,
               name: "freeze_windows_versions_version_source_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:freeze_windows) do
      add :org_id, :text, null: false
      add :starts_at, :utc_datetime, null: false
      add :ends_at, :utc_datetime, null: false
      add :reason, :text, null: false
      add :allow_emergency_override, :boolean, null: false, default: false
      add :created_by, :text, null: false
    end

    alter table(:approval_backup_retention_changes) do
      modify :org_id,
             references(:orgs,
               column: :slug,
               name: "approval_backup_retention_changes_org_id_fkey",
               type: :text,
               prefix: "public",
               on_delete: :restrict,
               on_update: :update_all
             )
    end

    alter table(:route_feature_flags) do
      add :flag_key, :text, null: false
      add :enabled, :boolean, null: false, default: false
      add :required_tier, :text, default: "starter"
    end

    alter table(:route_secrets) do
      add :namespace, :text, null: false
      add :name, :text, null: false
    end

  end

  # Real, deliberate exclusion (same real gap as every migration this
  # session): the codegen again proposed the destructive, unrelated
  # tokens.extra_data -> tokens.encrypted_extra_data rename.
  # Xaas.Accounts.Token's own code still declares `attribute :extra_data,
  # :map` (unchanged) -- stale resource-snapshot drift, excluded.
  def down do
    alter table(:route_secrets) do
      remove :name
      remove :namespace
    end

    alter table(:route_feature_flags) do
      remove :required_tier
      remove :enabled
      remove :flag_key
    end

    drop constraint(
           :approval_backup_retention_changes,
           "approval_backup_retention_changes_org_id_fkey"
         )

    alter table(:approval_backup_retention_changes) do
      modify :org_id, :text
    end

    alter table(:freeze_windows) do
      remove :created_by
      remove :allow_emergency_override
      remove :reason
      remove :ends_at
      remove :starts_at
      remove :org_id
    end

    drop constraint(:freeze_windows_versions, "freeze_windows_versions_version_source_id_fkey")

    alter table(:freeze_windows_versions) do
      modify :version_source_id, :uuid
    end

    drop table(:freeze_windows)

    alter table(:route_orgs_custom_domains) do
      add :approved_by, :text
      add :requested_by, :text, null: false
      remove :certificate_message
      remove :certificate_reason
      remove :certificate_secret_name
      remove :status
      remove :hostname
      remove :org_id
    end

    alter table(:approval_freeze_overrides) do
      remove :reason
      remove :freeze_window_id
      remove :org_id
    end

    drop constraint(
           :approval_pentest_finding_resolves,
           "approval_pentest_finding_resolves_finding_id_fkey"
         )

    alter table(:approval_pentest_finding_resolves) do
      modify :finding_id, :text
    end

    alter table(:route_projects_backups) do
      add :approved_by, :text
      add :requested_by, :text, null: false
      remove :status
      remove :retain_until
      remove :size_bytes
      remove :taken_at
      remove :job_name
      remove :project_name
      remove :namespace
      remove :org_id
    end

    drop table(:incidents)

    drop table(:freeze_windows_versions)

    drop table(:pentest_findings)
  end
end
