defmodule Xaas.Repo.Migrations.AddEpochOrgIdMultitenancy do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:ultracode_receipts, "ultracode_receipts_epoch_id_fkey")

    alter table(:ultracode_receipts) do
      modify :epoch_id,
             references(:ultracode_epochs,
               column: :id,
               name: "ultracode_receipts_epoch_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop_if_exists unique_index(:ultracode_epochs, [:run_id, :cycle],
                     name: "ultracode_epochs_unique_run_cycle_index"
                   )

    alter table(:ultracode_epochs) do
      add :org_id, :text
    end

    drop constraint(:ultracode_epochs, "ultracode_epochs_run_id_fkey")

    create unique_index(:ultracode_epochs, [:org_id, :run_id, :cycle],
             name: "ultracode_epochs_unique_run_cycle_index"
           )

    alter table(:ultracode_epochs) do
      modify :run_id,
             references(:ultracode_runs,
               column: :id,
               name: "ultracode_epochs_run_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end

  def down do
    drop constraint(:ultracode_epochs, "ultracode_epochs_run_id_fkey")

    alter table(:ultracode_epochs) do
      modify :run_id,
             references(:ultracode_runs,
               column: :id,
               name: "ultracode_epochs_run_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop_if_exists unique_index(:ultracode_epochs, [:org_id, :run_id, :cycle],
                     name: "ultracode_epochs_unique_run_cycle_index"
                   )

    alter table(:ultracode_epochs) do
      remove :org_id
    end

    create unique_index(:ultracode_epochs, [:run_id, :cycle],
             name: "ultracode_epochs_unique_run_cycle_index"
           )

    drop constraint(:ultracode_receipts, "ultracode_receipts_epoch_id_fkey")

    alter table(:ultracode_receipts) do
      modify :epoch_id,
             references(:ultracode_epochs,
               column: :id,
               name: "ultracode_receipts_epoch_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
