defmodule Xaas.Repo.Migrations.AddMarketplaceProviders do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`.

  Real, deliberate exclusion (same recurring class documented in
  `priv/repo/migrations/20260821024131_batch5_iam_cloak.exs`'s own
  moduledoc): the codegen again proposed the same two destructive,
  stale-resource-snapshot-drift renames --

  - `tokens.extra_data -> tokens.encrypted_extra_data`
  - `platform_webhooks.secret -> platform_webhooks.encrypted_secret`

  Both excluded from `up`/`down` below, exactly as documented in that
  prior migration's moduledoc. Only this migration's own real new table
  (`marketplace_providers`, backing `Xaas.Marketplace.Provider`) remains.
  """

  use Ecto.Migration

  def up do
    create table(:marketplace_providers, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :slug, :text, null: false
      add :description, :text
      add :status, :text, null: false, default: "pending"
      add :org_id, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:marketplace_providers, [:slug],
             name: "marketplace_providers_unique_slug_index"
           )
  end

  def down do
    drop_if_exists unique_index(:marketplace_providers, [:slug],
                     name: "marketplace_providers_unique_slug_index"
                   )

    drop table(:marketplace_providers)
  end
end
