defmodule Xaas.Repo.Migrations.ProviderLease do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:ultracode_runs) do
      add :provider, :text
    end

    alter table(:ultracode_epochs) do
      add :lease_token, :text
      add :lease_expires_at, :utc_datetime_usec
      add :leased_to, :text
      add :worktree, :text
      add :final_head, :text
    end
  end

  def down do
    alter table(:ultracode_epochs) do
      remove :final_head
      remove :worktree
      remove :leased_to
      remove :lease_expires_at
      remove :lease_token
    end

    alter table(:ultracode_runs) do
      remove :provider
    end
  end
end
