defmodule Xaas.Repo.Migrations.AddOrgMembership do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`.

  Manually trimmed after generation to keep this migration scoped to the
  real task at hand -- creating `org_memberships` alone. The generator
  also proposed, unprompted:

  - Creating `autofde_planner_cache_stats_requests`,
    `autofde_planner_match_requests`, `autofde_planner_cache_hotset_requests`
    -- unrelated pending resources' own first migrations, no relation to
    this task. Left for whoever owns those resources to generate for real.
  - Renaming `platform_webhooks.secret` -> `encrypted_secret` and
    `tokens.extra_data` -> `encrypted_extra_data` -- the same stale,
    already-known rename noise documented in
    `priv/repo/migrations/20260821024131_batch5_iam_cloak.exs` and
    `priv/repo/migrations/20260821034020_add_org_fk_dr_failover_legal_hold_release_deployment_quarantine.exs`
    (an `AshCloak`/snapshot quirk unrelated to this change). Excluded
    here per that same documented precedent.
  """

  use Ecto.Migration

  def up do
    create table(:org_memberships, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :role, :text, null: false, default: "member"

      add :user_id,
          references(:users,
            column: :id,
            name: "org_memberships_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :org_id,
          references(:orgs,
            column: :id,
            name: "org_memberships_org_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create unique_index(:org_memberships, [:user_id, :org_id],
             name: "org_memberships_unique_user_org_index"
           )
  end

  def down do
    drop constraint(:org_memberships, "org_memberships_org_id_fkey")

    drop constraint(:org_memberships, "org_memberships_user_id_fkey")

    drop_if_exists unique_index(:org_memberships, [:user_id, :org_id],
                     name: "org_memberships_unique_user_org_index"
                   )

    drop table(:org_memberships)
  end
end
