defmodule Xaas.Repo.Migrations.ResolvePendingBacklog20260821 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:autofde_planner_cache_stats_requests, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :query, :text, null: false
      add :cnv_response, :map
      add :trajectory_sha256, :text
      add :requested_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:autofde_planner_match_requests, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :query, :text, null: false
      add :cnv_response, :map
      add :trajectory_sha256, :text
      add :requested_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    alter table(:platform_webhooks) do
      add :encrypted_secret, :binary, null: false
      remove :secret
    end

    create table(:autofde_planner_cache_hotset_requests, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :query, :text, null: false
      add :cnv_response, :map
      add :trajectory_sha256, :text
      add :requested_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    alter table(:tokens) do
      add :encrypted_extra_data, :binary
      remove :extra_data
    end
  end

  def down do
    alter table(:tokens) do
      add :extra_data, :map
      remove :encrypted_extra_data
    end

    drop table(:autofde_planner_cache_hotset_requests)

    alter table(:platform_webhooks) do
      add :secret, :text, null: false
      remove :encrypted_secret
    end

    drop table(:autofde_planner_match_requests)

    drop table(:autofde_planner_cache_stats_requests)
  end
end
