defmodule Xaas.Repo.Migrations.AddDrCmekDsarColumns do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:approval_dr_failovers) do
      add :org_id, :text, null: false
      add :from_region, :text, null: false
      add :to_region, :text, null: false
      add :reason, :text, null: false
    end

    alter table(:approval_cmek_key_bindings) do
      add :org_id, :text, null: false
      add :provider, :text, null: false
      add :key_ref, :text, null: false
      add :reason, :text, null: false
    end

    alter table(:approval_dsar_erasures) do
      add :org_id, :text, null: false
      add :subject_email, :text, null: false
    end

  end

  # Real, deliberate exclusion (same real gap as prior migrations this
  # session): the codegen again proposed renaming tokens.extra_data ->
  # tokens.encrypted_extra_data. Xaas.Accounts.Token's own code still
  # declares `attribute :extra_data, :map` (unchanged this session) --
  # stale resource-snapshot drift, not a real code change, and a
  # destructive PII-column rename. Excluded per this repo's
  # never-blindly-touch-sensitive-resources discipline.
  def down do
    alter table(:approval_dsar_erasures) do
      remove :subject_email
      remove :org_id
    end

    alter table(:approval_cmek_key_bindings) do
      remove :reason
      remove :key_ref
      remove :provider
      remove :org_id
    end

    alter table(:approval_dr_failovers) do
      remove :reason
      remove :to_region
      remove :from_region
      remove :org_id
    end
  end
end
