defmodule Xaas.Repo.Migrations.InitialXaasResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:route_castle_schedules, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :requested_by, :text, null: false
      add :approved_by, :text
    end

    create table(:users, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :email, :citext, null: false
      add :hashed_password, :text
      add :confirmed_at, :utc_datetime_usec
    end

    create unique_index(:users, [:email], name: "users_unique_email_index")

    create table(:approval_vendor_offboarding_attestation_issues, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :requested_by, :text, null: false
      add :approved_by, :text
    end

    create table(:approval_source_escrow_snapshots, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :requested_by, :text, null: false
      add :approved_by, :text
    end

    create table(:approval_org_deletes, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :requested_by, :text, null: false
      add :approved_by, :text
    end

    create table(:approval_patch_sla_credit_applies, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :requested_by, :text, null: false
      add :approved_by, :text
    end

    create table(:approval_quota_overrides, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :requested_by, :text, null: false
      add :approved_by, :text
    end

    create table(:ledger_accounts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :identifier, :text, null: false
      add :currency, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:ledger_accounts, [:identifier],
             name: "ledger_accounts_unique_identifier_index"
           )

    create table(:approval_dr_failovers, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :requested_by, :text, null: false
      add :approved_by, :text
    end

    create table(:route_castle_sunsets, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :requested_by, :text, null: false
      add :approved_by, :text
    end

    create table(:approval_sla_credit_applies, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :requested_by, :text, null: false
      add :approved_by, :text
    end

    create table(:route_projects_backups, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :requested_by, :text, null: false
      add :approved_by, :text
    end

    create table(:approval_personnel_attestation_records, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :requested_by, :text, null: false
      add :approved_by, :text
    end

    create table(:approval_deployment_quarantines, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :requested_by, :text, null: false
      add :approved_by, :text
    end

    create table(:approval_invoice_reconciliation_approves, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :requested_by, :text, null: false
      add :approved_by, :text
    end

    create table(:approval_pentest_finding_resolves, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :requested_by, :text, null: false
      add :approved_by, :text
    end

    create table(:approval_freeze_overrides, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :requested_by, :text, null: false
      add :approved_by, :text
    end

    create table(:route_orgs_custom_domains, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :requested_by, :text, null: false
      add :approved_by, :text
    end

    create table(:ledger_balances, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :balance, :money_with_currency
      add :transfer_id, :binary, null: false

      add :account_id,
          references(:ledger_accounts,
            column: :id,
            name: "ledger_balances_account_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create unique_index(:ledger_balances, [:account_id, :transfer_id],
             name: "ledger_balances_unique_references_index"
           )

    create table(:approval_tier_downgrades, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :requested_by, :text, null: false
      add :approved_by, :text
    end

    create table(:castle_verb_inventory_goals, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :requested_by, :text, null: false
      add :approved_by, :text
    end

    create table(:approval_cmek_key_bindings, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :requested_by, :text, null: false
      add :approved_by, :text
    end

    create table(:route_castle_deploys, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :requested_by, :text, null: false
      add :approved_by, :text
    end

    create table(:data_destruction_certificate_issues, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :requested_by, :text, null: false
      add :approved_by, :text
    end

    create table(:approval_environment_promotes, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :requested_by, :text, null: false
      add :approved_by, :text
    end

    create table(:castle_verb_fortune5_requirements, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :requested_by, :text, null: false
      add :approved_by, :text
    end

    create table(:approval_change_of_control_notifies, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :requested_by, :text, null: false
      add :approved_by, :text
    end

    create table(:approval_subprocessor_registry_updates, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :requested_by, :text, null: false
      add :approved_by, :text
    end

    create table(:approval_backup_retention_changes, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :requested_by, :text, null: false
      add :approved_by, :text
    end

    create table(:approval_pricing_overrides, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :requested_by, :text, null: false
      add :approved_by, :text
    end

    create table(:approval_insurance_policy_updates, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :requested_by, :text, null: false
      add :approved_by, :text
    end

    create table(:approval_legal_hold_releases, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :requested_by, :text, null: false
      add :approved_by, :text
    end

    create table(:ledger_transfers, primary_key: false) do
      add :id, :binary, null: false, primary_key: true
    end

    alter table(:ledger_balances) do
      modify :transfer_id,
             references(:ledger_transfers,
               column: :id,
               name: "ledger_balances_transfer_id_fkey",
               type: :binary,
               prefix: "public"
             )
    end

    alter table(:ledger_transfers) do
      add :amount, :money_with_currency, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :timestamp, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :from_account_id,
          references(:ledger_accounts,
            column: :id,
            name: "ledger_transfers_from_account_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :to_account_id,
          references(:ledger_accounts,
            column: :id,
            name: "ledger_transfers_to_account_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create table(:route_feature_flags, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :requested_by, :text, null: false
      add :approved_by, :text
    end

    create table(:approval_geofence_exception_grants, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :requested_by, :text, null: false
      add :approved_by, :text
    end

    create table(:approval_castle_verb_schedules, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :requested_by, :text, null: false
      add :approved_by, :text
    end

    create table(:approval_dsar_erasures, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :requested_by, :text, null: false
      add :approved_by, :text
    end

    create table(:approval_k8s_fault_remediate_suggests, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :requested_by, :text, null: false
      add :approved_by, :text
    end

    create table(:castle_verb_inventory_components, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :requested_by, :text, null: false
      add :approved_by, :text
    end

    create table(:approval_sso_role_mapping_updates, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :requested_by, :text, null: false
      add :approved_by, :text
    end

    create table(:approval_denied_party_overrides, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :requested_by, :text, null: false
      add :approved_by, :text
    end

    create table(:route_secrets, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :requested_by, :text, null: false
      add :approved_by, :text
    end

    create table(:approval_break_glass_justification_reviews, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :requested_by, :text, null: false
      add :approved_by, :text
    end

    create table(:approval_compliance_rotation_blocks, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :requested_by, :text, null: false
      add :approved_by, :text
    end

    create table(:tokens, primary_key: false) do
      add :jti, :text, null: false, primary_key: true
      add :subject, :text, null: false
      add :expires_at, :utc_datetime, null: false
      add :purpose, :text, null: false
      add :extra_data, :map

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:approval_le_request_responds, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :requested_by, :text, null: false
      add :approved_by, :text
    end

    create table(:approval_export_subscription_updates, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :requested_by, :text, null: false
      add :approved_by, :text
    end

    create table(:route_projects, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :requested_by, :text, null: false
      add :approved_by, :text
    end

    create table(:route_castle_runs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :requested_by, :text, null: false
      add :approved_by, :text
    end
  end

  def down do
    drop table(:route_castle_runs)

    drop table(:route_projects)

    drop table(:approval_export_subscription_updates)

    drop table(:approval_le_request_responds)

    drop table(:tokens)

    drop table(:approval_compliance_rotation_blocks)

    drop table(:approval_break_glass_justification_reviews)

    drop table(:route_secrets)

    drop table(:approval_denied_party_overrides)

    drop table(:approval_sso_role_mapping_updates)

    drop table(:castle_verb_inventory_components)

    drop table(:approval_k8s_fault_remediate_suggests)

    drop table(:approval_dsar_erasures)

    drop table(:approval_castle_verb_schedules)

    drop table(:approval_geofence_exception_grants)

    drop table(:route_feature_flags)

    drop constraint(:ledger_transfers, "ledger_transfers_to_account_id_fkey")

    drop constraint(:ledger_transfers, "ledger_transfers_from_account_id_fkey")

    alter table(:ledger_transfers) do
      remove :to_account_id
      remove :from_account_id
      remove :timestamp
      remove :updated_at
      remove :inserted_at
      remove :amount
    end

    drop constraint(:ledger_balances, "ledger_balances_account_id_fkey")

    drop constraint(:ledger_balances, "ledger_balances_transfer_id_fkey")

    alter table(:ledger_balances) do
      modify :transfer_id, :binary
    end

    drop table(:ledger_transfers)

    drop table(:approval_legal_hold_releases)

    drop table(:approval_insurance_policy_updates)

    drop table(:approval_pricing_overrides)

    drop table(:approval_backup_retention_changes)

    drop table(:approval_subprocessor_registry_updates)

    drop table(:approval_change_of_control_notifies)

    drop table(:castle_verb_fortune5_requirements)

    drop table(:approval_environment_promotes)

    drop table(:data_destruction_certificate_issues)

    drop table(:route_castle_deploys)

    drop table(:approval_cmek_key_bindings)

    drop table(:castle_verb_inventory_goals)

    drop table(:approval_tier_downgrades)

    drop_if_exists unique_index(:ledger_balances, [:account_id, :transfer_id],
                     name: "ledger_balances_unique_references_index"
                   )

    drop table(:ledger_balances)

    drop table(:route_orgs_custom_domains)

    drop table(:approval_freeze_overrides)

    drop table(:approval_pentest_finding_resolves)

    drop table(:approval_invoice_reconciliation_approves)

    drop table(:approval_deployment_quarantines)

    drop table(:approval_personnel_attestation_records)

    drop table(:route_projects_backups)

    drop table(:approval_sla_credit_applies)

    drop table(:route_castle_sunsets)

    drop table(:approval_dr_failovers)

    drop_if_exists unique_index(:ledger_accounts, [:identifier],
                     name: "ledger_accounts_unique_identifier_index"
                   )

    drop table(:ledger_accounts)

    drop table(:approval_quota_overrides)

    drop table(:approval_patch_sla_credit_applies)

    drop table(:approval_org_deletes)

    drop table(:approval_source_escrow_snapshots)

    drop table(:approval_vendor_offboarding_attestation_issues)

    drop_if_exists unique_index(:users, [:email], name: "users_unique_email_index")

    drop table(:users)

    drop table(:route_castle_schedules)
  end
end
