defmodule Xaas.Repo.Migrations.AddUltracodeTickMissedEpochs do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:ultracode_runs) do
      add :epoch_timeout_seconds, :bigint, null: false, default: 300
    end

    alter table(:ultracode_epochs) do
      add :expected_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:ultracode_epochs) do
      remove :expected_at
    end

    alter table(:ultracode_runs) do
      remove :epoch_timeout_seconds
    end
  end
end
