defmodule Xaas.Repo.Migrations.AddDurationBudgetAndWaveSession do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`,
  then trimmed to ONLY the duration-budget columns: regenerating after the
  rebase also re-listed the semantic-work-identity columns, which the
  earlier `20260919062000_add_semantic_work_identity_to_ultracode_runs`
  had already applied (that migration was hand-written without updating
  the snapshot chain; the companion snapshot `20260920084711.json` from
  this migration repairs the chain by reflecting the full current
  resource).
  """

  use Ecto.Migration

  def up do
    alter table(:ultracode_runs) do
      add :duration_budget_seconds, :bigint, null: false, default: 28800
      add :waves_run, :bigint, null: false, default: 0
      add :wave_session, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:ultracode_runs) do
      remove :wave_session
      remove :waves_run
      remove :duration_budget_seconds
    end
  end
end
