defmodule Xaas.Repo.Migrations.AddOrgFkDrFailoverLegalHoldReleaseDeploymentQuarantine do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`.

  Manually trimmed after generation to keep this migration scoped to the
  real task at hand -- 3 real `org_id` -> `orgs.slug` FKs
  (ApprovalDrFailover, ApprovalDeploymentQuarantine,
  ApprovalLegalHoldRelease). The generator also proposed, unprompted:

  - Creating `autofde_planner_match_requests` -- an unrelated pending
    resource's first migration, no relation to this task's 3 Governance
    resources. Left for whoever owns that resource to generate for real.
  - Renaming `platform_webhooks.secret` -> `encrypted_secret` and
    `tokens.extra_data` -> `encrypted_extra_data` -- the same stale,
    already-known rename noise documented in
    `priv/repo/migrations/20260821024131_batch5_iam_cloak.exs` (an
    `AshCloak`/snapshot quirk unrelated to this change). Excluded here per
    that same documented precedent.
  """

  use Ecto.Migration

  def up do
    alter table(:approval_dr_failovers) do
      modify :org_id,
             references(:orgs,
               column: :slug,
               name: "approval_dr_failovers_org_id_fkey",
               type: :text,
               prefix: "public",
               on_delete: :restrict,
               on_update: :update_all
             )
    end

    alter table(:approval_deployment_quarantines) do
      modify :org_id,
             references(:orgs,
               column: :slug,
               name: "approval_deployment_quarantines_org_id_fkey",
               type: :text,
               prefix: "public",
               on_delete: :restrict,
               on_update: :update_all
             )
    end

    alter table(:approval_legal_hold_releases) do
      modify :org_id,
             references(:orgs,
               column: :slug,
               name: "approval_legal_hold_releases_org_id_fkey",
               type: :text,
               prefix: "public",
               on_delete: :restrict,
               on_update: :update_all
             )
    end
  end

  def down do
    drop constraint(:approval_legal_hold_releases, "approval_legal_hold_releases_org_id_fkey")

    alter table(:approval_legal_hold_releases) do
      modify :org_id, :text
    end

    drop constraint(
           :approval_deployment_quarantines,
           "approval_deployment_quarantines_org_id_fkey"
         )

    alter table(:approval_deployment_quarantines) do
      modify :org_id, :text
    end

    drop constraint(:approval_dr_failovers, "approval_dr_failovers_org_id_fkey")

    alter table(:approval_dr_failovers) do
      modify :org_id, :text
    end
  end
end
