defmodule Xaas.Repo.Migrations.AddCapitalCensusSelfDigest do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:experience_clusters, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :required_closure, :text, null: false
      add :residual_shape, :text, null: false
      add :context, :text, null: false
      add :episode_count, :bigint, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:resolutions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :outcome, :text, null: false
      add :receipt_ref, :text, null: false
      add :work_order_id, :uuid, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:gaps, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :experience_cluster_id, :uuid, null: false
      add :required_closure, :text, null: false
      add :residual_shape, :text, null: false
      add :context, :text, null: false
      add :recurrence_class, :text, null: false
      add :primitive_target, :text, null: false
      add :episode_count, :bigint, null: false
      add :falsifier, :text, null: false
      add :status, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:work_orders, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :ticket_id, :text, null: false
      add :subject, :text, null: false
      add :observed, :text, null: false
      add :expected, :text, null: false
      add :residual, :text, null: false
      add :classification, :text, null: false
      add :candidate_repair, :text, null: false
      add :falsifier, :text, null: false
      add :success_criteria, :text, null: false
      add :derived_from_receipt, :text, null: false
      add :status, :text, null: false
      add :gap_id, :uuid, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:episodes, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :subject, :text, null: false
      add :outcome, :text, null: false
      add :required_closure, :text, null: false
      add :residual_shape, :text, null: false
      add :context, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop table(:episodes)

    drop table(:work_orders)

    drop table(:gaps)


    drop table(:resolutions)

    drop table(:experience_clusters)
  end
end
