defmodule Xaas.Repo.Migrations.AddTokenRevokeNonce do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:token_revoke_nonces, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end
  end

  def down do
    drop table(:token_revoke_nonces)
  end
end
