defmodule Xaas.Repo.Migrations.AddSubscriptionIdAndRequestedTierToApprovalTierDowngrade do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`,
  then hand-stripped of an unrelated cross-table operation
  (`alter table(:autofde_planner_cache_stats_requests) do remove
  :cache_hit? end`) that `mix xaas.safe_generate_migrations` correctly
  refused to let through unreviewed -- real, pre-existing pending drift on
  a resource this task never touched, not something this migration should
  carry. The corresponding unrelated resource snapshot this run also
  generated for `autofde_planner_cache_stats_requests` was deleted rather
  than committed, so a future real generation run still sees that pending
  diff and handles it on its own.
  """

  use Ecto.Migration

  def up do
    alter table(:approval_tier_downgrades) do
      add :requested_tier, :text, null: false

      add :subscription_id,
          references(:billing_subscriptions,
            column: :id,
            name: "approval_tier_downgrades_subscription_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end
  end

  def down do
    drop constraint(:approval_tier_downgrades, "approval_tier_downgrades_subscription_id_fkey")

    alter table(:approval_tier_downgrades) do
      remove :subscription_id
      remove :requested_tier
    end
  end
end
