defmodule Xaas.Repo.Migrations.AddApprovalProviderStatusChange do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`.

  Real, deliberate exclusion (same recurring class documented in
  `priv/repo/migrations/20260821024131_batch5_iam_cloak.exs`'s and
  `priv/repo/migrations/20260821024511_add_marketplace_providers.exs`'s
  own moduledocs): the codegen again proposed the same two destructive,
  stale-resource-snapshot-drift renames (`platform_webhooks.secret ->
  platform_webhooks.encrypted_secret`, `tokens.extra_data ->
  tokens.encrypted_extra_data`), plus re-`create table`s for
  `autofde_planner_cache_stats_requests`, `autofde_planner_match_requests`,
  and `autofde_planner_cache_hotset_requests` -- all three already real,
  migrated tables (see `20260821035000_create_autofde_planner_cache_stats_requests.exs`,
  `20260821032800_create_autofde_planner_match_requests.exs`,
  `20260821035100_create_autofde_planner_cache_hotset_requests.exs`), just
  resource-snapshot drift from those resources' snapshots predating this
  generator run. All excluded from `up`/`down` below. Only this
  migration's own real new table (`approval_provider_status_changes`,
  backing `Xaas.Marketplace.ApprovalProviderStatusChange`) remains.
  """

  use Ecto.Migration

  def up do
    create table(:approval_provider_status_changes, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :org_id, :text, null: false

      add :provider_id,
          references(:marketplace_providers,
            column: :id,
            name: "approval_provider_status_changes_provider_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :requested_by, :text, null: false
      add :requested_status, :text, null: false
      add :approved_by, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop constraint(
           :approval_provider_status_changes,
           "approval_provider_status_changes_provider_id_fkey"
         )

    drop table(:approval_provider_status_changes)
  end
end
