defmodule Xaas.Repo.Migrations.AddSa2aExecutions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:sa2a_executions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :work_order_id, :text, null: false
      add :work_order_digest, :text, null: false
      add :query, :text, null: false
      add :plan_hash, :text, null: false
      add :idempotency_key, :text, null: false
      add :class_id, :text, null: false
      add :admit_receipt_id, :text
      add :admit_candidate_hash, :text, null: false
      add :capability, :text, null: false
      add :result, :text, null: false
      add :llm_avoidance_ratio, :float, null: false
      add :manifest, :map, null: false
      add :manifest_hash, :text, null: false
      add :replay_verified, :boolean, null: false, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:sa2a_executions, [:idempotency_key],
             name: "sa2a_executions_unique_idempotency_key_index"
           )
  end

  def down do
    drop_if_exists unique_index(:sa2a_executions, [:idempotency_key],
                     name: "sa2a_executions_unique_idempotency_key_index"
                   )

    drop table(:sa2a_executions)
  end
end
