defmodule Xaas.Repo.Migrations.AddAuditExportTokenAndFixes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:audit_export_tokens, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :org_id, :text, null: false
      add :token_prefix, :text, null: false
      add :token_hash, :text, null: false
      add :scope, :text, null: false, default: "audit:read"
      add :created_by, :text, null: false
      add :expires_at, :utc_datetime_usec
      add :revoked_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

  end

  # Real, deliberate exclusion (same real gap as every migration this
  # session): the codegen again proposed the destructive, unrelated
  # tokens.extra_data -> tokens.encrypted_extra_data rename.
  # Xaas.Accounts.Token's own code still declares `attribute :extra_data,
  # :map` (unchanged) -- stale resource-snapshot drift, excluded.
  def down do
    drop table(:audit_export_tokens)
  end
end
