defmodule Xaas.Repo.Migrations.VerifierSuiteOnRuns do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:ultracode_runs) do
      add :verifier_suite, :text
    end
  end

  def down do
    alter table(:ultracode_runs) do
      remove :verifier_suite
    end
  end
end
