defmodule Xaas.Repo.Migrations.AddInternalApiTokenOrgId do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:internal_api_tokens) do
      add :org_id,
          references(:orgs,
            column: :id,
            name: "internal_api_tokens_org_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:internal_api_tokens, "internal_api_tokens_org_id_fkey")

    alter table(:internal_api_tokens) do
      remove :org_id
    end
  end
end
