defmodule Xaas.Repo.Migrations.ExecutionFabric do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:work_contracts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :work_id, :text, null: false
      add :repository, :text, null: false
      add :base_sha, :text, null: false
      add :worktree, :text
      add :goal, :text
      add :acceptance, :map
      add :verifier, :map
      add :falsifiers, :map
      add :authority_ceiling, :text
      add :quota_lane, :text
      add :state, :text
      add :lease_token, :text
      add :lease_expires_at, :utc_datetime
      add :final_head, :text
      add :standing, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :execution_worker_id, :uuid
    end

    create unique_index(:work_contracts, [:work_id], name: "work_contracts_unique_work_id_index")

    create table(:execution_workers, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:work_contracts) do
      modify :execution_worker_id,
             references(:execution_workers,
               column: :id,
               name: "work_contracts_execution_worker_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )
    end

    alter table(:execution_workers) do
      add :provider, :text, null: false
      add :provider_worker_id, :text, null: false
      add :provider_session_id, :text
      add :repository, :text
      add :worktree, :text
      add :model_class, :text
      add :quota_lane, :text
      add :state, :text
      add :capabilities, :map
      add :last_heartbeat_at, :utc_datetime
      add :lease_expires_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:execution_workers, [:provider, :provider_worker_id],
             name: "execution_workers_unique_provider_worker_index"
           )
  end

  def down do
    drop_if_exists unique_index(:execution_workers, [:provider, :provider_worker_id],
                     name: "execution_workers_unique_provider_worker_index"
                   )

    alter table(:execution_workers) do
      remove :updated_at
      remove :inserted_at
      remove :lease_expires_at
      remove :last_heartbeat_at
      remove :capabilities
      remove :state
      remove :quota_lane
      remove :model_class
      remove :worktree
      remove :repository
      remove :provider_session_id
      remove :provider_worker_id
      remove :provider
    end

    drop constraint(:work_contracts, "work_contracts_execution_worker_id_fkey")

    alter table(:work_contracts) do
      modify :execution_worker_id, :uuid
    end

    drop table(:execution_workers)

    drop_if_exists unique_index(:work_contracts, [:work_id],
                     name: "work_contracts_unique_work_id_index"
                   )

    drop table(:work_contracts)
  end
end
