defmodule Xaas.Repo.Migrations.AddCacheHitFlag do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:autofde_planner_cache_stats_requests) do
      add :cache_hit?, :boolean
    end
  end

  def down do
    alter table(:autofde_planner_cache_stats_requests) do
      remove :cache_hit?
    end
  end
end
