defmodule Xaas.Repo.Migrations.AddCapabilityLivenessReceipts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:capability_liveness_receipts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :capability, :text, null: false
      add :authority, :text, null: false
      add :status, :text, null: false
      add :executed, :boolean, null: false, default: true
      add :exit_code, :bigint
      add :subject, :text, null: false
      add :detail, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:capability_liveness_receipts, [:capability, :subject],
             name: "capability_liveness_receipts_capability_subject_index"
           )
  end

  def down do
    drop_if_exists unique_index(:capability_liveness_receipts, [:capability, :subject],
                     name: "capability_liveness_receipts_capability_subject_index"
                   )

    drop table(:capability_liveness_receipts)
  end
end
