defmodule Xaas.Repo.Migrations.AddGovernanceSwarmBatchColumns do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:approval_vendor_offboarding_attestation_issues) do
      add :org_id, :text, null: false
      add :termination_date, :date, null: false
      add :contractual_sla_days, :bigint, null: false
    end

    alter table(:approval_source_escrow_snapshots) do
      add :org_id, :text, null: false
      add :namespace, :text, null: false, default: "platform-console"
    end

    alter table(:approval_org_deletes) do
      add :org_id, :text, null: false
    end

    alter table(:approval_personnel_attestation_records) do
      add :org_id, :text, null: false
      add :attestation_statement, :text, null: false
      add :overrides, {:array, :map}, default: []
    end

    alter table(:approval_deployment_quarantines) do
      add :org_id, :text, null: false
      add :deployment_name, :text, null: false
      add :environment, :text, null: false
      add :reason, :text, null: false
    end

    alter table(:data_destruction_certificate_issues) do
      add :org_id, :text, null: false
    end

    alter table(:approval_environment_promotes) do
      add :org_id, :text, null: false
      add :project_name, :text, null: false
      add :from_environment, :text, null: false
      add :to_environment, :text, null: false
    end

    alter table(:approval_change_of_control_notifies) do
      add :org_id, :text, null: false
      add :event_type, :text, null: false
      add :description, :text, null: false
      add :trigger_date, :text, null: false
      add :notice_window_days, :bigint
      add :notification_method, :text, null: false
    end

    alter table(:approval_subprocessor_registry_updates) do
      add :change_action, :text, null: false
      add :subprocessor_id, :text, null: false
      add :name, :text, null: false
      add :category, :text, null: false
      add :regions, {:array, :text}, default: []
      add :purpose, :text, null: false
      add :data_categories, {:array, :text}, default: []
    end

    alter table(:approval_insurance_policy_updates) do
      add :org_id, :text, null: false
      add :coverage_type, :text, null: false
      add :carrier, :text, null: false
      add :policy_number, :text, null: false
      add :coverage_limit_usd, :decimal, null: false
      add :effective_date, :date, null: false
      add :expiry_date, :date, null: false
      add :am_best_rating, :text
    end

    alter table(:approval_legal_hold_releases) do
      add :org_id, :text
      add :hold_id, :text, null: false
      add :release_reason, :text, null: false
    end

    alter table(:approval_geofence_exception_grants) do
      add :org_id, :text, null: false
      add :identifier_or_cidr, :text, null: false
      add :reason, :text, null: false
      add :ttl_hours, :bigint, null: false
    end

    alter table(:approval_sso_role_mapping_updates) do
      add :org_id, :text, null: false
      add :requested_mappings, {:array, :map}, null: false
    end

    alter table(:approval_denied_party_overrides) do
      add :org_id, :text, null: false
      add :screening_record_id, :text, null: false
      add :decision, :text, null: false
      add :justification, :text, null: false
    end

    alter table(:approval_break_glass_justification_reviews) do
      add :org_id, :text, null: false
      add :grant_id, :text, null: false
      add :justification, :text, null: false
    end

    alter table(:approval_le_request_responds) do
      add :org_id, :text
      add :request_type, :text, null: false
      add :requesting_authority, :text, null: false
      add :jurisdiction, :text, null: false
      add :summary, :text, null: false
      add :reference_number, :text
      add :status, :text
      add :response_summary, :text
    end

    # Real, disclosed gap (not fixed in this batch, scope-limited):
    # access_key_id/secret_access_key below store real S3-style
    # credentials as plain :text, unlike Xaas.Accounts.Token's
    # cloak-encrypted extra_data. Same class of finding as this session's
    # other disclosed-not-fixed items -- flagged here rather than
    # silently shipped as if it were safe.
    alter table(:approval_export_subscription_updates) do
      add :org_id, :text, null: false
      add :bucket_endpoint, :text, null: false
      add :bucket_name, :text, null: false
      add :access_key_id, :text, null: false
      add :secret_access_key, :text, null: false
      add :prefix, :text
      add :cadence, :text, null: false
      add :scope, :text, null: false
      add :enabled, :boolean, null: false, default: true
    end
  end

  def down do
    alter table(:approval_export_subscription_updates) do
      remove :enabled
      remove :scope
      remove :cadence
      remove :prefix
      remove :secret_access_key
      remove :access_key_id
      remove :bucket_name
      remove :bucket_endpoint
      remove :org_id
    end

    alter table(:approval_le_request_responds) do
      remove :response_summary
      remove :status
      remove :reference_number
      remove :summary
      remove :jurisdiction
      remove :requesting_authority
      remove :request_type
      remove :org_id
    end

    alter table(:approval_break_glass_justification_reviews) do
      remove :justification
      remove :grant_id
      remove :org_id
    end

    alter table(:approval_denied_party_overrides) do
      remove :justification
      remove :decision
      remove :screening_record_id
      remove :org_id
    end

    alter table(:approval_sso_role_mapping_updates) do
      remove :requested_mappings
      remove :org_id
    end

    alter table(:approval_geofence_exception_grants) do
      remove :ttl_hours
      remove :reason
      remove :identifier_or_cidr
      remove :org_id
    end

    alter table(:approval_legal_hold_releases) do
      remove :release_reason
      remove :hold_id
      remove :org_id
    end

    alter table(:approval_insurance_policy_updates) do
      remove :am_best_rating
      remove :expiry_date
      remove :effective_date
      remove :coverage_limit_usd
      remove :policy_number
      remove :carrier
      remove :coverage_type
      remove :org_id
    end

    alter table(:approval_subprocessor_registry_updates) do
      remove :data_categories
      remove :purpose
      remove :regions
      remove :category
      remove :name
      remove :subprocessor_id
      remove :change_action
    end

    alter table(:approval_change_of_control_notifies) do
      remove :notification_method
      remove :notice_window_days
      remove :trigger_date
      remove :description
      remove :event_type
      remove :org_id
    end

    alter table(:approval_environment_promotes) do
      remove :to_environment
      remove :from_environment
      remove :project_name
      remove :org_id
    end

    alter table(:data_destruction_certificate_issues) do
      remove :org_id
    end

    alter table(:approval_deployment_quarantines) do
      remove :reason
      remove :environment
      remove :deployment_name
      remove :org_id
    end

    alter table(:approval_personnel_attestation_records) do
      remove :overrides
      remove :attestation_statement
      remove :org_id
    end

    alter table(:approval_org_deletes) do
      remove :org_id
    end

    alter table(:approval_source_escrow_snapshots) do
      remove :namespace
      remove :org_id
    end

    alter table(:approval_vendor_offboarding_attestation_issues) do
      remove :contractual_sla_days
      remove :termination_date
      remove :org_id
    end
  end
end
