defmodule Xaas.Repo.Migrations.Batch5IamCloak do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`.

  Real, deliberate exclusion (same recurring class as every migration this
  session): the codegen proposed two destructive renames, both stale
  resource-snapshot drift, not real code changes --

  - `tokens.extra_data -> tokens.encrypted_extra_data` (the standing,
    recurring false-positive from every prior batch this session --
    `Xaas.Accounts.Token`'s own code still declares
    `attribute :extra_data, :map`, unchanged).
  - `platform_webhooks.secret -> platform_webhooks.encrypted_secret` (new
    this batch, same root cause: `Xaas.Webhook`'s AshCloak wiring
    deliberately keeps the column named `:secret` -- see that resource's
    moduledoc, "same real, deliberate non-rename" -- AshCloak encrypts the
    existing column in place; the codegen's heuristic still guesses a
    rename from the `encrypted_` prefix convention it saw on `Token`).

  Both excluded from `up`/`down` below. Nothing else in this migration
  batch -- every other Ash-level change this batch (AshIam on
  `Xaas.Billing.Subscription`, `AshOban` scheduled retry on
  `Xaas.Platform.WebhookDelivery`) is policy/action-only, no schema change.
  """

  use Ecto.Migration

  def up do
  end

  def down do
  end
end
