defmodule Xaas.Repo.Migrations.AddOrgResource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:orgs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :slug, :text, null: false
      add :status, :text, null: false, default: "active"
    end

    create unique_index(:orgs, [:slug], name: "orgs_unique_slug_index")

  end

  # Real, deliberate exclusion (same real gap as every migration this
  # session): the codegen again proposed the destructive, unrelated
  # tokens.extra_data -> tokens.encrypted_extra_data rename.
  # Xaas.Accounts.Token's own code still declares `attribute :extra_data,
  # :map` (unchanged) -- stale resource-snapshot drift, excluded.
  def down do
    drop_if_exists unique_index(:orgs, [:slug], name: "orgs_unique_slug_index")

    drop table(:orgs)
  end
end
