defmodule Xaas.Repo.Migrations.AddCapabilityIdToUltracodeRuns do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:ultracode_runs) do
      add :capability_id, :text
    end
  end

  def down do
    alter table(:ultracode_runs) do
      remove :capability_id
    end
  end
end
