defmodule Xaas.Repo.Migrations.ResolvePendingBacklog20260821 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`.

  The AutoFDE planner request tables are intentionally not recreated here.
  They already have earlier dedicated migrations in this same history:
  `20260821032800_create_autofde_planner_match_requests.exs`,
  `20260821035000_create_autofde_planner_cache_stats_requests.exs`, and
  `20260821035100_create_autofde_planner_cache_hotset_requests.exs`.
  """

  use Ecto.Migration

  def up do
    alter table(:platform_webhooks) do
      add :encrypted_secret, :binary, null: false
      remove :secret
    end

    alter table(:tokens) do
      add :encrypted_extra_data, :binary
      remove :extra_data
    end
  end

  def down do
    alter table(:tokens) do
      add :extra_data, :map
      remove :encrypted_extra_data
    end

    alter table(:platform_webhooks) do
      add :secret, :text, null: false
      remove :encrypted_secret
    end
  end
end
