defmodule Xaas.Repo.Migrations.AddOcelTables do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:ocel_objects, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :object_type, :text, null: false
      add :ocel_id, :text, null: false
      add :ash_resource, :text
      add :ash_resource_id, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:ocel_objects, [:object_type, :ocel_id],
             name: "ocel_objects_object_type_ocel_id_index"
           )

    create table(:ocel_event_objects, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :qualifier, :text, null: false, default: "related"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :event_id, :uuid, null: false

      add :object_id,
          references(:ocel_objects,
            column: :id,
            name: "ocel_event_objects_object_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create unique_index(:ocel_event_objects, [:event_id, :object_id, :qualifier],
             name: "ocel_event_objects_event_object_qualifier_index"
           )

    create table(:ocel_events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:ocel_event_objects) do
      modify :event_id,
             references(:ocel_events,
               column: :id,
               name: "ocel_event_objects_event_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:ocel_events) do
      add :event_type, :text, null: false
      add :ocel_id, :text, null: false
      add :occurred_at, :utc_datetime_usec, null: false
      add :attributes, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:ocel_events, [:event_type, :ocel_id],
             name: "ocel_events_event_type_ocel_id_index"
           )

    create table(:ocel_object_objects, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :qualifier, :text, null: false, default: "related"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :source_object_id,
          references(:ocel_objects,
            column: :id,
            name: "ocel_object_objects_source_object_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :target_object_id,
          references(:ocel_objects,
            column: :id,
            name: "ocel_object_objects_target_object_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create unique_index(:ocel_object_objects, [:source_object_id, :target_object_id, :qualifier],
             name: "ocel_object_objects_object_object_qualifier_index"
           )

    create table(:ocel_object_state_deltas, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :attribute, :text, null: false
      add :previous_value, :text
      add :new_value, :text
      add :occurred_at, :utc_datetime_usec, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :object_id,
          references(:ocel_objects,
            column: :id,
            name: "ocel_object_state_deltas_object_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :event_id,
          references(:ocel_events,
            column: :id,
            name: "ocel_object_state_deltas_event_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:ocel_object_state_deltas, "ocel_object_state_deltas_event_id_fkey")

    drop constraint(:ocel_object_state_deltas, "ocel_object_state_deltas_object_id_fkey")

    drop table(:ocel_object_state_deltas)

    drop constraint(:ocel_object_objects, "ocel_object_objects_target_object_id_fkey")

    drop constraint(:ocel_object_objects, "ocel_object_objects_source_object_id_fkey")

    drop_if_exists unique_index(
                     :ocel_object_objects,
                     [:source_object_id, :target_object_id, :qualifier],
                     name: "ocel_object_objects_object_object_qualifier_index"
                   )

    drop table(:ocel_object_objects)

    drop_if_exists unique_index(:ocel_events, [:event_type, :ocel_id],
                     name: "ocel_events_event_type_ocel_id_index"
                   )

    alter table(:ocel_events) do
      remove :updated_at
      remove :inserted_at
      remove :attributes
      remove :occurred_at
      remove :ocel_id
      remove :event_type
    end

    drop constraint(:ocel_event_objects, "ocel_event_objects_object_id_fkey")

    drop constraint(:ocel_event_objects, "ocel_event_objects_event_id_fkey")

    alter table(:ocel_event_objects) do
      modify :event_id, :uuid
    end

    drop table(:ocel_events)

    drop_if_exists unique_index(:ocel_event_objects, [:event_id, :object_id, :qualifier],
                     name: "ocel_event_objects_event_object_qualifier_index"
                   )

    drop table(:ocel_event_objects)

    drop_if_exists unique_index(:ocel_objects, [:object_type, :ocel_id],
                     name: "ocel_objects_object_type_ocel_id_index"
                   )

    drop table(:ocel_objects)
  end
end
