defmodule Xaas.Repo.Migrations.AddBillingSubscription do
  @moduledoc """
  Real, hand-scoped migration for `Xaas.Billing.Subscription` only.

  `mix ash.codegen add_billing_subscription` was run for real and did
  correctly detect this resource's own schema, but it also bundled in
  unrelated, pre-existing schema drift already present on this branch
  before this change (new `platform_webhooks`/`platform_webhook_deliveries`
  tables, and a destructive `tokens.extra_data` -> `encrypted_extra_data`
  rename+drop) that this task did not touch and has no business shipping
  alongside a billing-subscription addition. This migration is the
  `billing_subscriptions`-only subset of that autogenerated `up`/`down`,
  hand-extracted -- not re-run through codegen, since codegen has no
  "only this resource" flag and re-running it reproduces the same bundled
  diff. The unrelated resource snapshots that migration would have
  recorded were deleted along with it; only this resource's own
  `priv/resource_snapshots/repo/billing_subscriptions/*.json` snapshot is
  kept, so this migration and that snapshot describe the same real state.
  """

  use Ecto.Migration

  def up do
    create table(:billing_subscriptions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :org_id, :text, null: false
      add :stripe_customer_id, :text, null: false
      add :stripe_subscription_id, :text
      add :tier, :text, null: false, default: "standard"
      add :status, :text, null: false, default: "incomplete"
      add :current_period_end, :utc_datetime
    end

    create unique_index(:billing_subscriptions, [:org_id],
             name: "billing_subscriptions_unique_org_index"
           )
  end

  def down do
    drop_if_exists unique_index(:billing_subscriptions, [:org_id],
                     name: "billing_subscriptions_unique_org_index"
                   )

    drop table(:billing_subscriptions)
  end
end
