defmodule Xaas.Repo.Migrations.AddBackupRetentionChangeColumns do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  # Real, deliberate exclusion: `mix ash_postgres.generate_migrations` also
  # proposed renaming tokens.extra_data -> tokens.encrypted_extra_data, an
  # unrelated, destructive change (drops a real PII/auth column) to
  # Xaas.Accounts.Token that this resource's own code does not ask for
  # (lib/xaas/accounts/token.ex still declares `attribute :extra_data,
  # :map`, confirmed by reading it) -- stale resource-snapshot drift, not a
  # real code change, and not something this migration should carry as a
  # side effect. Excluded per CLAUDE.md's "never blindly wire/change
  # sensitive resources" discipline; the stray
  # priv/resource_snapshots/repo/tokens/*.json this generation run produced
  # was reverted, not committed.
  def up do
    alter table(:approval_backup_retention_changes) do
      add :org_id, :text, null: false
      add :requested_retention_days, :bigint, null: false
    end
  end

  def down do
    alter table(:approval_backup_retention_changes) do
      remove :requested_retention_days
      remove :org_id
    end
  end
end
