defmodule Xaas.Repo.Migrations.AddLibraryPersonaGrants do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:library_persona_grants, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :caller_id, :text, null: false
      add :granted_by, :text

      add :granted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :revoked_at, :utc_datetime_usec

      add :user_id,
          references(:users,
            column: :id,
            name: "library_persona_grants_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create unique_index(:library_persona_grants, [:caller_id, :user_id],
             name: "library_persona_grants_active_caller_user_index",
             where: "(revoked_at IS NULL)"
           )
  end

  def down do
    drop constraint(:library_persona_grants, "library_persona_grants_user_id_fkey")

    drop_if_exists unique_index(:library_persona_grants, [:caller_id, :user_id],
                     name: "library_persona_grants_active_caller_user_index"
                   )

    drop table(:library_persona_grants)
  end
end
