defmodule Xaas.Repo.Migrations.AddCouplingRuns do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:coupling_runs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :proposals, {:array, :map}, null: false
      add :constraints, :map, null: false, default: %{}
      add :status, :text, null: false
      add :z, {:array, :float}
      add :weights, :map
      add :receipt, :map
      add :unsupported_reason, :map
      add :requested_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop table(:coupling_runs)
  end
end
