defmodule Xaas.Repo.Migrations.AddDeckCapabilities do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:library_curations) do
      add :student_id, :text
      add :state, :text, null: false, default: "pinned"
      modify :grade_band, :text, default: "6-8"
    end

    create table(:library_holds, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :school_id, :text, null: false, default: "willow-creek"
      add :position, :bigint, null: false, default: 1
      add :status, :text, null: false, default: "active"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :book_id,
          references(:library_books,
            column: :id,
            name: "library_holds_book_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "library_holds_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    alter table(:library_checkouts) do
      add :school_id, :text, null: false, default: "willow-creek"
      add :renewed_count, :bigint, null: false, default: 0
    end

    create table(:library_recommendation_logs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :candidate_pool_size, :bigint, null: false, default: 0
      add :weights, :map, null: false
      add :ranked_items, {:array, :map}, null: false, default: []
      add :accepted, :boolean, null: false, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "library_recommendation_logs_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    alter table(:library_books) do
      add :formats, {:array, :text}, null: false
      add :cover_color, :text, null: false, default: "#23405F"
      add :review_status, :text, null: false, default: "approved"
      modify :grade_level, :decimal, default: "5.0"
    end
  end

  def down do
    alter table(:library_books) do
      modify :grade_level, :bigint, default: nil
      remove :review_status
      remove :cover_color
      remove :formats
    end

    drop constraint(:library_recommendation_logs, "library_recommendation_logs_user_id_fkey")

    drop table(:library_recommendation_logs)

    alter table(:library_checkouts) do
      remove :renewed_count
      remove :school_id
    end

    drop constraint(:library_holds, "library_holds_user_id_fkey")

    drop constraint(:library_holds, "library_holds_book_id_fkey")

    drop table(:library_holds)

    alter table(:library_curations) do
      modify :grade_band, :text, default: nil
      remove :state
      remove :student_id
    end
  end
end
