defmodule Xaas.Repo.Migrations.AddUltracodeOcelMoments do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:ultracode_runs) do
      add :terminal_at, :utc_datetime_usec
    end

    alter table(:ultracode_epochs) do
      add :terminal_at, :utc_datetime_usec
      add :claimed_at, :utc_datetime_usec
      add :last_heartbeat_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:ultracode_epochs) do
      remove :last_heartbeat_at
      remove :claimed_at
      remove :terminal_at
    end

    alter table(:ultracode_runs) do
      remove :terminal_at
    end
  end
end
