defmodule Xaas.Repo.Migrations.AddUserGradeLevelSchoolId do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :grade_level, :bigint
      add :school_id, :text
    end

    create table(:library_schools, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :slug, :text, null: false
      add :name, :text, null: false
      add :domain, :text, null: false
      add :default?, :boolean, null: false, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:library_schools, [:slug], name: "library_schools_unique_slug_index")
  end

  def down do
    drop_if_exists unique_index(:library_schools, [:slug],
                     name: "library_schools_unique_slug_index"
                   )

    drop table(:library_schools)

    alter table(:users) do
      remove :school_id
      remove :grade_level
    end
  end
end
