defmodule Xaas.Repo.Migrations.AddOrgIdCreditAmountSlaCredits do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:approval_patch_sla_credit_applies) do
      add :org_id, :text, null: false
      add :credit_amount_cents, :bigint, null: false
    end

    alter table(:approval_sla_credit_applies) do
      add :org_id, :text, null: false
      add :credit_amount_cents, :bigint, null: false
    end
  end

  def down do
    alter table(:approval_sla_credit_applies) do
      remove :credit_amount_cents
      remove :org_id
    end

    alter table(:approval_patch_sla_credit_applies) do
      remove :credit_amount_cents
      remove :org_id
    end
  end
end
