defmodule ExNounVerbCli.Completions do
  @moduledoc """
  Shell-completion scripts as a pure projection of the introspection
  manifest: nouns as subcommands, verbs per noun, option flags per verb.
  No hand-authored command strings exist here -- if a word is not in the
  registry, it cannot appear in a generated script (an ARD falsifier).

  `script/3` renders for the shells `ExNounVerbCli.Shell` marks
  supported (bash, zsh, fish); the caller refuses unsupported shells
  before rendering. Line endings follow the shell's policy table entry.
  """

  alias ExNounVerbCli.Shell

  @doc """
  Renders the completion script for `command` (the binary or function
  name completions attach to) from `manifest`
  (`ExNounVerbCli.Introspect.manifest/1` output).
  """
  @spec script(map(), Shell.t(), String.t()) :: String.t()
  def script(manifest, :bash, command), do: bash(manifest, command, Shell.line_ending(:bash))
  def script(manifest, :zsh, command), do: zsh(manifest, command, Shell.line_ending(:zsh))
  def script(manifest, :fish, command), do: fish(manifest, command, Shell.line_ending(:fish))

  # -- bash ----------------------------------------------------------------

  defp bash(manifest, command, eol) do
    fn_name = "_" <> sanitize(command) <> "_completions"
    nouns = manifest |> noun_names() |> Enum.sort()

    noun_cases =
      manifest
      |> sorted_nouns()
      |> Enum.map(fn noun ->
        verb_words = manifest |> verb_records(noun) |> verb_names() |> Enum.join(" ")

        flag_cases =
          manifest
          |> verb_records(noun)
          |> Enum.map(fn record ->
            flags = record |> flags() |> Enum.join(" ")

            """
                 #{record["verb"]})
                   COMPREPLY=( $(compgen -W "#{flags}" -- "$cur") )
                   return
                   ;;
            """
          end)
          |> Enum.join(eol)

        """
            #{noun})
              case "${COMP_WORDS[2]}" in
          #{flag_cases}
                "")
                  COMPREPLY=( $(compgen -W "#{verb_words}" -- "$cur") )
                  return
                  ;;
              esac
              ;;
        """
      end)
      |> Enum.join(eol)

    """
    # completions for #{command} -- generated by ex_noun_verb_cli --completions bash
    #{fn_name}() {
      local cur="${COMP_WORDS[COMP_CWORD]}"
      case "${COMP_WORDS[1]}" in
    #{noun_cases}
      esac
      COMPREPLY=( $(compgen -W "#{Enum.join(nouns, " ")}" -- "$cur") )
    }
    complete -F #{fn_name} #{command}
    """
    |> String.replace("\n", eol)
  end

  # -- zsh -----------------------------------------------------------------

  defp zsh(manifest, command, eol) do
    fn_name = "_" <> sanitize(command)
    noun_words = manifest |> noun_names() |> Enum.sort() |> Enum.join(" ")

    verb_cases =
      manifest
      |> sorted_nouns()
      |> Enum.map(fn noun ->
        verbs = manifest |> verb_records(noun) |> verb_names() |> Enum.join(" ")
        "        #{noun}) _values 'verb' #{verbs} ;;"
      end)
      |> Enum.join(eol)

    """
    #compdef #{command}
    # completions for #{command} -- generated by ex_noun_verb_cli --completions zsh
    #{fn_name}() {
      local state
      _arguments -C '1: :->noun' '2: :->verb'
      case $state in
        noun) _values 'noun' #{noun_words} ;;
        verb)
          case $words[2] in
    #{verb_cases}
          esac
          ;;
      esac
    }
    #{fn_name} "$@"
    """
    |> String.replace("\n", eol)
  end

  # -- fish ----------------------------------------------------------------

  defp fish(manifest, command, eol) do
    noun_words = manifest |> noun_names() |> Enum.sort() |> Enum.join(" ")

    header = [
      "# completions for #{command} -- generated by ex_noun_verb_cli --completions fish",
      "complete -c #{command} -n '__fish_use_subcommand' -a '#{noun_words}'"
    ]

    per_verb =
      for noun <- sorted_nouns(manifest), record <- verb_records(manifest, noun) do
        # fish's -l takes the long-flag name without leading dashes
        flag_args =
          record["schema"] |> Enum.map(fn {flag, _type} -> "-l #{flag}" end) |> Enum.join(" ")

        verb_line =
          "complete -c #{command} -n '__fish_seen_subcommand_from #{noun}' -a '#{record["verb"]}'"

        if flag_args == "" do
          verb_line
        else
          [
            verb_line,
            "complete -c #{command} -n '__fish_seen_subcommand_from #{noun}; and __fish_seen_subcommand_from #{record["verb"]}' #{flag_args}"
          ]
        end
      end
      |> List.flatten()

    Enum.join(header ++ per_verb, eol) <> eol
  end

  # -- manifest helpers ----------------------------------------------------

  defp sorted_nouns(manifest), do: manifest["nouns"] |> Map.keys() |> Enum.sort()

  defp noun_names(manifest), do: Map.keys(manifest["nouns"])

  defp verb_records(manifest, noun),
    do: Enum.filter(manifest["verbs"], &(&1["noun"] == noun))

  defp verb_names(records), do: Enum.map(records, & &1["verb"])

  defp flags(record), do: Enum.map(record["schema"], fn {flag, _type} -> "--#{flag}" end)

  defp sanitize(command), do: String.replace(command, ~r/[^a-zA-Z0-9_]/, "_")
end
