#!/usr/bin/env node
// ultracode-run.mjs -- ZCode runtime for Claude Code Workflow scripts ("ultracode").
//
// Spec: skills/ultracode-takeover/SKILL.md. This file is GENERATED by
// `cd priv/zcode_plugin && ggen sync run` from templates/script-ultracode-run.mjs.tmpl;
// never hand-edit the marketplace copy. The JS body is irreducible handwritten residue,
// recorded in HANDWRITTEN.md as UNSUPPORTED(generator-capability): workflow runtime logic.
//
// Strategy B: workflow scripts load as REAL ES modules. A node:module loader hook
// (module.register with a data: URL hooks module) resolves the bare specifier "claude"
// to a generated module exporting the primitives of the run named in the importing
// module's URL (?ultracode_run=<id>, propagated to relative imports), and wraps
// body-form scripts (top-level `return` is illegal in ESM) in an async function inside a
// generated module. Node >= 22, node: builtins only.
//
// CLI:
//   node ultracode-run.mjs run <script.js> [--args <json|text|@file>] [--run-dir <dir>]
//        [--resume-from <claudeTranscriptDir|zcodeRunDir>] [--cwd <dir>]
//        [--concurrency N] [--dry-run] [--json]
//   node ultracode-run.mjs selftest
//
// Env: ULTRACODE_AGENT_CMD (default `node ${ZCODE_CLI_DIR:-/Users/sac/dev/zcode-cli}/bin/zcode.js`),
//   ULTRACODE_HOME (default ~/.zcode/ultracode), ULTRACODE_CLAUDE_HOME (default ~/.claude),
//   ULTRACODE_CONCURRENCY, MAX_STRUCTURED_OUTPUT_RETRIES (5), ULTRACODE_MAX_AGENTS (1000),
//   ULTRACODE_RATE_LIMIT_RETRIES (5), ULTRACODE_BACKOFF_BASE_MS (5000), ULTRACODE_BACKOFF_MAX_MS
//   (120000), ULTRACODE_AGENT_TIMEOUT_MS (0 = none), ULTRACODE_PREFLIGHT_TIMEOUT_MS (30000),
//   ULTRACODE_SELFTEST_AGENT (scripted backend path for `selftest`).

import { register } from 'node:module';
import { spawn, spawnSync } from 'node:child_process';
import { createHash, randomBytes } from 'node:crypto';
import fs, { readFileSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const SELF = fileURLToPath(import.meta.url);
const SELF_DIR = path.dirname(SELF);
const REGISTRY_SYMBOL = Symbol.for('ultracode.registry');
const REGISTRY = (globalThis[REGISTRY_SYMBOL] ??= new Map());

// ---------------------------------------------------------------------------
// Typed errors

class UltracodeError extends Error {
  constructor(code, message, detail) {
    super(message);
    this.name = 'UltracodeError';
    this.code = code;
    if (detail !== undefined) this.detail = detail;
  }
}

// Internal: stops a preflight pass (cap or timeout) without failing the run.
class PreflightStop extends Error {
  constructor(why) {
    super(`preflight stopped: ${why}`);
    this.code = 'PREFLIGHT_STOP';
  }
}

function errInfo(e) {
  if (e && e.code && typeof e.message === 'string') {
    const o = { code: e.code, message: e.message };
    if (e.detail !== undefined) o.detail = e.detail;
    return o;
  }
  return { code: 'SCRIPT_ERROR', message: String(e && e.stack ? e.stack.split('\n').slice(0, 4).join('\n') : e) };
}

// ---------------------------------------------------------------------------
// Canonical JSON + hashing

function canonicalJSON(v) {
  if (v === null || typeof v !== 'object') return JSON.stringify(v === undefined ? null : v);
  if (Array.isArray(v)) return '[' + v.map((x) => (x === undefined || typeof x === 'function' ? 'null' : canonicalJSON(x))).join(',') + ']';
  const keys = Object.keys(v).filter((k) => v[k] !== undefined && typeof v[k] !== 'function').sort();
  return '{' + keys.map((k) => JSON.stringify(k) + ':' + canonicalJSON(v[k])).join(',') + '}';
}

function sha256(s) {
  return createHash('sha256').update(s).digest('hex');
}

function jsonSafe(v) {
  return v === undefined ? undefined : JSON.parse(JSON.stringify(v));
}

// ---------------------------------------------------------------------------
// Source analysis. These four functions are self-contained (no module-scope
// references) because their source text is embedded verbatim in the loader-hooks
// module, which runs off-thread.

// Offsets of every line whose first character is top-level code: not inside a
// string, template literal, comment or regex, and at bracket depth 0.
function scanTopLevel(src) {
  const starts = [];
  const n = src.length;
  const stack = [];
  let i = 0;
  let depth = 0;
  let inTemplate = false;
  let prevSig = '';
  let prevWord = '';
  let lineStart = true;
  const REGEX_WORDS = ['return', 'typeof', 'instanceof', 'in', 'of', 'new', 'delete', 'void', 'throw', 'case', 'do', 'else', 'yield', 'await'];
  while (i < n) {
    const c = src[i];
    if (lineStart) {
      if (!inTemplate && depth === 0 && stack.length === 0) starts.push(i);
      lineStart = false;
    }
    if (inTemplate) {
      if (c === '\\') {
        if (src[i + 1] === '\n') lineStart = true;
        i += 2;
        continue;
      }
      if (c === '`') {
        inTemplate = false;
        prevSig = '`';
        prevWord = '';
        i++;
        continue;
      }
      if (c === '$' && src[i + 1] === '{') {
        stack.push(depth);
        depth++;
        inTemplate = false;
        prevSig = '{';
        i += 2;
        continue;
      }
      if (c === '\n') lineStart = true;
      i++;
      continue;
    }
    if (c === '\n') {
      lineStart = true;
      i++;
      continue;
    }
    if (c === ' ' || c === '\t' || c === '\r') {
      i++;
      continue;
    }
    if (c === '/' && src[i + 1] === '/') {
      while (i < n && src[i] !== '\n') i++;
      continue;
    }
    if (c === '/' && src[i + 1] === '*') {
      const e = src.indexOf('*/', i + 2);
      i = e < 0 ? n : e + 2;
      continue;
    }
    if (c === '"' || c === "'") {
      i++;
      while (i < n && src[i] !== c) {
        if (src[i] === '\\') i++;
        else if (src[i] === '\n') break;
        i++;
      }
      i++;
      prevSig = c;
      prevWord = '';
      continue;
    }
    if (c === '`') {
      inTemplate = true;
      i++;
      continue;
    }
    if (c === '/') {
      const regexAllowed = prevSig === 'w' ? REGEX_WORDS.includes(prevWord) : !(prevSig && ')]}`"\''.includes(prevSig));
      if (regexAllowed) {
        i++;
        let inClass = false;
        while (i < n) {
          const ch = src[i];
          if (ch === '\\') {
            i += 2;
            continue;
          }
          if (ch === '\n') break;
          if (inClass) {
            if (ch === ']') inClass = false;
          } else if (ch === '[') inClass = true;
          else if (ch === '/') {
            i++;
            break;
          }
          i++;
        }
        while (i < n && /[a-z]/i.test(src[i])) i++;
        prevSig = ')';
        prevWord = '';
        continue;
      }
      prevSig = '/';
      prevWord = '';
      i++;
      continue;
    }
    if (c === '{' || c === '(' || c === '[') {
      depth++;
      prevSig = c;
      prevWord = '';
      i++;
      continue;
    }
    if (c === '}' || c === ')' || c === ']') {
      if (c === '}' && stack.length && stack[stack.length - 1] === depth - 1) {
        stack.pop();
        depth--;
        inTemplate = true;
        i++;
        continue;
      }
      depth = Math.max(0, depth - 1);
      prevSig = c;
      prevWord = '';
      i++;
      continue;
    }
    if (/[A-Za-z0-9_$]/.test(c)) {
      let j = i;
      while (j < n && /[A-Za-z0-9_$]/.test(src[j])) j++;
      prevWord = src.slice(i, j);
      prevSig = 'w';
      i = j;
      continue;
    }
    prevSig = c;
    prevWord = '';
    i++;
  }
  return starts;
}

// Parses exactly one pure literal (object/array/string/number/true/false/null,
// comments and trailing commas allowed) starting at `pos`. Anything computed --
// identifiers, calls, spreads, computed keys, shorthand/method properties, template
// interpolation -- throws.
function parseLiteralAt(src, pos) {
  let i = pos;
  const fail = (msg) => {
    throw new Error(`${msg} (offset ${i})`);
  };
  const ws = () => {
    for (;;) {
      while (i < src.length && /\s/.test(src[i])) i++;
      if (src[i] === '/' && src[i + 1] === '/') {
        while (i < src.length && src[i] !== '\n') i++;
        continue;
      }
      if (src[i] === '/' && src[i + 1] === '*') {
        const e = src.indexOf('*/', i + 2);
        if (e < 0) fail('unterminated comment');
        i = e + 2;
        continue;
      }
      return;
    }
  };
  const str = () => {
    const q = src[i];
    i++;
    let out = '';
    while (i < src.length) {
      const c = src[i];
      if (c === q) {
        i++;
        return out;
      }
      if (q === '`' && c === '$' && src[i + 1] === '{') fail('template interpolation is not a literal');
      if (c === '\\') {
        const d = src[i + 1];
        i += 2;
        const simple = { n: '\n', t: '\t', r: '\r', b: '\b', f: '\f', v: '\v', 0: '\0' };
        if (d === 'u') {
          if (src[i] === '{') {
            const e = src.indexOf('}', i);
            out += String.fromCodePoint(parseInt(src.slice(i + 1, e), 16));
            i = e + 1;
          } else {
            out += String.fromCharCode(parseInt(src.slice(i, i + 4), 16));
            i += 4;
          }
        } else if (d === 'x') {
          out += String.fromCharCode(parseInt(src.slice(i, i + 2), 16));
          i += 2;
        } else if (d === '\n') {
          // line continuation
        } else if (d === '\r') {
          if (src[i] === '\n') i++;
        } else out += d in simple ? simple[d] : d;
        continue;
      }
      if (c === '\n' && q !== '`') fail('newline in string literal');
      out += c;
      i++;
    }
    fail('unterminated string');
  };
  const num = () => {
    const m = /^[+-]?(?:0[xX][0-9a-fA-F_]+|0[oO][0-7_]+|0[bB][01_]+|(?:\d[\d_]*\.?[\d_]*|\.\d[\d_]*)(?:[eE][+-]?\d+)?)/.exec(src.slice(i, i + 80));
    if (!m) fail('bad number');
    i += m[0].length;
    const t = m[0].replace(/_/g, '');
    const neg = t[0] === '-';
    const body = t[0] === '-' || t[0] === '+' ? t.slice(1) : t;
    const v = Number(body);
    if (Number.isNaN(v)) fail('bad number');
    return neg ? -v : v;
  };
  const value = () => {
    ws();
    const c = src[i];
    if (c === '{') return obj();
    if (c === '[') return arr();
    if (c === '"' || c === "'" || c === '`') return str();
    if (c === '-' || c === '+' || c === '.' || (c >= '0' && c <= '9')) {
      if (c === '.' && src[i + 1] === '.') fail('spread is not a literal');
      return num();
    }
    const w = /^[A-Za-z_$][\w$]*/.exec(src.slice(i, i + 80));
    if (w) {
      if (w[0] === 'true') {
        i += 4;
        return true;
      }
      if (w[0] === 'false') {
        i += 5;
        return false;
      }
      if (w[0] === 'null') {
        i += 4;
        return null;
      }
      fail(`identifier \`${w[0]}\` is not a literal`);
    }
    fail(`unexpected \`${c === undefined ? 'EOF' : c}\``);
  };
  const obj = () => {
    i++;
    const o = {};
    for (;;) {
      ws();
      if (src[i] === '}') {
        i++;
        return o;
      }
      let k;
      const c = src[i];
      if (c === '"' || c === "'") k = str();
      else if (c === '`') fail('template-literal key is not a literal');
      else if (c === '[') fail('computed key is not a literal');
      else if (c === '.') fail('spread is not a literal');
      else {
        const w = /^(?:[A-Za-z_$][\w$]*|\d+)/.exec(src.slice(i, i + 256));
        if (!w) fail('bad property key');
        k = w[0];
        i += k.length;
      }
      ws();
      if (src[i] !== ':') fail(`expected \`:\` after key \`${k}\` (shorthand and method properties are not literals)`);
      i++;
      Object.defineProperty(o, k, { value: value(), enumerable: true, writable: true, configurable: true });
      ws();
      if (src[i] === ',') {
        i++;
        continue;
      }
      if (src[i] === '}') {
        i++;
        return o;
      }
      fail('expected `,` or `}`');
    }
  };
  const arr = () => {
    i++;
    const a = [];
    for (;;) {
      ws();
      if (src[i] === ']') {
        i++;
        return a;
      }
      if (src[i] === '.' && src[i + 1] === '.') fail('spread is not a literal');
      if (src[i] === ',') fail('array holes are not allowed');
      a.push(value());
      ws();
      if (src[i] === ',') {
        i++;
        continue;
      }
      if (src[i] === ']') {
        i++;
        return a;
      }
      fail('expected `,` or `]`');
    }
  };
  const v = value();
  return { value: v, end: i };
}

// Finds `export const meta = <pure literal>` at top level. Returns {ok, meta, start, end}
// or {ok:false, code, message} with code META_MISSING | META_NOT_LITERAL | META_INVALID.
function extractMeta(src) {
  for (const s of scanTopLevel(src)) {
    const head = src.slice(s, s + 200);
    const m = /^export\s+(const|let|var)\s+meta\b\s*(=)?\s*/.exec(head);
    if (!m) continue;
    if (m[1] !== 'const') return { ok: false, code: 'META_NOT_LITERAL', message: 'meta must be declared `export const meta = { ... }`' };
    if (!m[2]) return { ok: false, code: 'META_NOT_LITERAL', message: 'meta has no initializer' };
    let parsed;
    try {
      parsed = parseLiteralAt(src, s + m[0].length);
    } catch (e) {
      return { ok: false, code: 'META_NOT_LITERAL', message: `meta must be a pure literal: ${e.message}` };
    }
    let j = parsed.end;
    for (;;) {
      while (j < src.length && (src[j] === ' ' || src[j] === '\t' || src[j] === '\r')) j++;
      if (src[j] === '/' && src[j + 1] === '*') {
        const e = src.indexOf('*/', j + 2);
        if (e < 0) break;
        j = e + 2;
        continue;
      }
      break;
    }
    if (src[j] === ';') j++;
    else if (!(j >= src.length || src[j] === '\n' || (src[j] === '/' && src[j + 1] === '/'))) {
      return { ok: false, code: 'META_NOT_LITERAL', message: `meta must be a pure literal: unexpected \`${src[j]}\` after the literal` };
    }
    const v = parsed.value;
    if (!v || typeof v !== 'object' || Array.isArray(v)) return { ok: false, code: 'META_INVALID', message: 'meta must be an object literal' };
    if (typeof v.name !== 'string' || !v.name) return { ok: false, code: 'META_INVALID', message: 'meta.name (non-empty string) is required' };
    if (typeof v.description !== 'string') return { ok: false, code: 'META_INVALID', message: 'meta.description (string) is required' };
    if (v.phases !== undefined && !Array.isArray(v.phases)) return { ok: false, code: 'META_INVALID', message: 'meta.phases must be an array' };
    return { ok: true, meta: v, start: s, end: j };
  }
  if (/^\s*export\s*\{[^}]*\bmeta\b/m.test(src)) return { ok: false, code: 'META_NOT_LITERAL', message: 'meta must be declared `export const meta = { ... }`, not re-exported' };
  return { ok: false, code: 'META_MISSING', message: 'script has no top-level `export const meta = { ... }`' };
}

// Body form -> module: meta re-exported as JSON, top-level imports hoisted, other
// top-level `export` keywords dropped, and the body wrapped in an async IIFE inside
// the default-exported function that receives the primitives. The prelude has no
// newline and removed text is replaced by blanks, so line numbers are preserved.
function transformBody(src) {
  const info = extractMeta(src);
  if (!info.ok) throw new Error(`${info.code}: ${info.message}`);
  const cuts = [[info.start, info.end, null]];
  const imports = [];
  if (src.startsWith('#!')) {
    const e = src.indexOf('\n');
    cuts.push([0, e < 0 ? src.length : e, null]);
  }
  for (const s of scanTopLevel(src)) {
    if (s >= info.start && s < info.end) continue;
    const rest = src.slice(s, s + 4000);
    let m;
    if (!/^import\s*[(.]/.test(rest)) {
      m = /^import\s*(?:[\w$*{][\s\S]*?\bfrom\s*)?(['"])[^'"\n]*\1(?:\s*(?:with|assert)\s*\{[^}]*\})?\s*;?/.exec(rest);
      if (m) {
        imports.push(m[0].replace(/\s+/g, ' ').replace(/;?\s*$/, ';'));
        cuts.push([s, s + m[0].length, null]);
        continue;
      }
    }
    m = /^export\s+(?=(?:async\s+)?function\b|const\b|let\b|var\b|class\b)/.exec(rest);
    if (m) {
      cuts.push([s, s + m[0].length, ' '.repeat(m[0].length)]);
      continue;
    }
    m = /^export\s*\{[^}]*\}\s*(?:from\s*(['"])[^'"\n]*\1)?\s*;?/.exec(rest);
    if (m) cuts.push([s, s + m[0].length, null]);
  }
  cuts.sort((a, b) => a[0] - b[0]);
  let out = '';
  let pos = 0;
  for (const [a, b, rep] of cuts) {
    if (a < pos) continue;
    out += src.slice(pos, a) + (rep === null ? src.slice(a, b).replace(/[^\n]/g, ' ') : rep);
    pos = b;
  }
  out += src.slice(pos);
  const prelude =
    imports.join(' ') +
    ' export const meta = ' +
    JSON.stringify(info.meta) +
    '; export default async function __ultracode_body(__uc) { const { agent, pipeline, parallel, phase, log, args, budget, workflow } = __uc; return await (async () => {';
  return prelude + out + '\n})(); }\n';
}

function detectForm(src) {
  for (const s of scanTopLevel(src)) {
    const rest = src.slice(s, s + 200);
    if (
      /^export\s+(?:async\s+)?function\s*\*?\s*run\s*\(/.test(rest) ||
      /^export\s+(?:const|let|var)\s+run\s*=/.test(rest) ||
      /^export\s*\{[^}]*\brun\b[^}]*\}/.test(rest) ||
      /^export\s+default\s+(?:async\s+)?function\b/.test(rest)
    ) {
      return 'module';
    }
  }
  return 'body';
}

function normalizeMeta(meta) {
  const phases = (meta.phases || []).map((p) =>
    typeof p === 'string' ? { title: p, detail: null } : { title: String(p && p.title), detail: p && p.detail != null ? String(p.detail) : null },
  );
  return { ...meta, phases };
}

// ---------------------------------------------------------------------------
// Loader hooks (Strategy B). Stringified into a data: URL module; runs off-thread.

async function ucResolve(specifier, context, nextResolve) {
  let run = null;
  if (context.parentURL && context.parentURL.startsWith('file:')) {
    try {
      run = new URL(context.parentURL).searchParams.get('ultracode_run');
    } catch {
      run = null;
    }
  }
  if (specifier === 'claude') {
    if (!run) throw new Error('ultracode: the "claude" module is only available to workflow scripts run by ultracode-run.mjs');
    return { url: 'ultracode:claude?run=' + encodeURIComponent(run), shortCircuit: true };
  }
  const r = await nextResolve(specifier, context);
  if (run && r.url.startsWith('file:') && !r.url.includes('/node_modules/') && /^(\.{1,2}\/|\/|file:)/.test(specifier)) {
    const u = new URL(r.url);
    u.searchParams.set('ultracode_run', run);
    return { ...r, url: u.href };
  }
  return r;
}

async function ucLoad(url, context, nextLoad) {
  if (url.startsWith('ultracode:claude')) {
    const run = new URL(url).searchParams.get('run') || '';
    const names = ['agent', 'pipeline', 'parallel', 'phase', 'log', 'budget', 'workflow', 'args'];
    const source =
      `const reg = (globalThis[Symbol.for('ultracode.registry')] || new Map()).get(${JSON.stringify(run)});\n` +
      `if (!reg) throw new Error(${JSON.stringify('ultracode: "claude" imported outside an active run ' + run)});\n` +
      names.map((n) => `export const ${n} = reg.${n};`).join('\n') +
      '\nexport default reg;\n';
    return { format: 'module', source, shortCircuit: true };
  }
  if (url.startsWith('file:') && url.includes('ultracode_form=')) {
    const u = new URL(url);
    const form = u.searchParams.get('ultracode_form');
    u.search = '';
    u.hash = '';
    const src = readFileSync(fileURLToPath(u), 'utf8');
    return { format: 'module', source: form === 'body' ? transformBody(src) : src, shortCircuit: true };
  }
  return nextLoad(url, context);
}

function hooksSource() {
  return [
    "import { readFileSync } from 'node:fs';",
    "import { fileURLToPath } from 'node:url';",
    scanTopLevel.toString(),
    parseLiteralAt.toString(),
    extractMeta.toString(),
    transformBody.toString(),
    ucResolve.toString(),
    ucLoad.toString(),
    'export { ucResolve as resolve, ucLoad as load };',
  ].join('\n');
}

let hooksRegistered = false;
function ensureLoaderHooks() {
  if (hooksRegistered) return;
  hooksRegistered = true;
  // module.register is deprecated (DEP0205) in favour of registerHooks on newest
  // Node; Strategy B uses it deliberately (off-thread data: URL hooks), so the one
  // warning is silenced for this call only.
  const prev = process.noDeprecation;
  process.noDeprecation = true;
  try {
    register('data:text/javascript;base64,' + Buffer.from(hooksSource()).toString('base64'));
  } finally {
    process.noDeprecation = prev;
  }
}

function scriptUrl(scriptPath, runId, form, attempt) {
  const u = pathToFileURL(scriptPath);
  u.searchParams.set('ultracode_run', runId);
  u.searchParams.set('ultracode_form', form);
  if (attempt) u.searchParams.set('ultracode_try', String(attempt));
  return u.href;
}

// ---------------------------------------------------------------------------
// Draft-07 subset: pre-flight contradiction check + validator

const KNOWN_TYPES = new Set(['object', 'array', 'string', 'number', 'integer', 'boolean', 'null']);

function isPlainObject(v) {
  return v !== null && typeof v === 'object' && !Array.isArray(v);
}

function schemaPreflight(schema) {
  if (!isPlainObject(schema)) return ['$: schema must be a JSON Schema object'];
  const errs = [];
  if (schema.type !== 'object') errs.push(`$: root schema must have type "object" (got ${JSON.stringify(schema.type)})`);
  preflightWalk(schema, '$', errs);
  return errs;
}

function preflightWalk(s, p, errs) {
  if (s === true || s === false) return;
  if (!isPlainObject(s)) {
    errs.push(`${p}: subschema must be an object or boolean`);
    return;
  }
  if (s.type !== undefined) {
    const ts = Array.isArray(s.type) ? s.type : [s.type];
    if (!ts.length) errs.push(`${p}.type: empty type list`);
    for (const t of ts) if (!KNOWN_TYPES.has(t)) errs.push(`${p}.type: unknown type ${JSON.stringify(t)}`);
  }
  let props = null;
  if (s.properties !== undefined) {
    if (isPlainObject(s.properties)) props = s.properties;
    else errs.push(`${p}.properties: must be an object`);
  }
  if (s.required !== undefined) {
    if (!Array.isArray(s.required) || s.required.some((k) => typeof k !== 'string')) errs.push(`${p}.required: must be an array of strings`);
    else {
      for (const k of s.required) {
        const missing = props ? !Object.prototype.hasOwnProperty.call(props, k) : s.additionalProperties === false;
        if (missing) errs.push(`${p}.required: "${k}" is required but not declared in properties`);
      }
    }
  }
  if (s.enum !== undefined && (!Array.isArray(s.enum) || s.enum.length === 0)) errs.push(`${p}.enum: must be a non-empty array`);
  for (const [lo, hi] of [
    ['minItems', 'maxItems'],
    ['minimum', 'maximum'],
    ['minLength', 'maxLength'],
    ['minProperties', 'maxProperties'],
  ]) {
    if (typeof s[lo] === 'number' && typeof s[hi] === 'number' && s[lo] > s[hi]) errs.push(`${p}: ${lo} ${s[lo]} > ${hi} ${s[hi]}`);
  }
  if (s.pattern !== undefined) {
    try {
      new RegExp(s.pattern, 'u');
    } catch (e) {
      errs.push(`${p}.pattern: ${e.message}`);
    }
  }
  if (props) for (const [k, v] of Object.entries(props)) preflightWalk(v, `${p}.properties.${k}`, errs);
  if (s.items !== undefined) {
    if (Array.isArray(s.items)) s.items.forEach((it, i) => preflightWalk(it, `${p}.items[${i}]`, errs));
    else preflightWalk(s.items, `${p}.items`, errs);
  }
  if (isPlainObject(s.additionalProperties)) preflightWalk(s.additionalProperties, `${p}.additionalProperties`, errs);
  for (const kw of ['allOf', 'anyOf', 'oneOf']) if (Array.isArray(s[kw])) s[kw].forEach((x, i) => preflightWalk(x, `${p}.${kw}[${i}]`, errs));
  if (s.not !== undefined) preflightWalk(s.not, `${p}.not`, errs);
}

function jsType(v) {
  if (v === null) return 'null';
  if (Array.isArray(v)) return 'array';
  if (typeof v === 'number' && Number.isInteger(v)) return 'integer';
  return typeof v;
}

function typeMatches(t, v) {
  switch (t) {
    case 'object':
      return isPlainObject(v);
    case 'array':
      return Array.isArray(v);
    case 'string':
      return typeof v === 'string';
    case 'integer':
      return Number.isInteger(v);
    case 'number':
      return typeof v === 'number' && Number.isFinite(v);
    case 'boolean':
      return typeof v === 'boolean';
    case 'null':
      return v === null;
    default:
      return false;
  }
}

function validateSchema(s, v, p = '$', errs = []) {
  if (s === true || s === undefined) return errs;
  if (s === false) {
    errs.push(`${p}: no value is allowed here`);
    return errs;
  }
  if (!isPlainObject(s)) return errs;
  if (s.type !== undefined) {
    const ts = Array.isArray(s.type) ? s.type : [s.type];
    if (!ts.some((t) => typeMatches(t, v))) {
      errs.push(`${p}: expected ${ts.join('|')}, got ${jsType(v)}`);
      return errs;
    }
  }
  if (Array.isArray(s.enum) && !s.enum.some((e) => canonicalJSON(e) === canonicalJSON(v))) errs.push(`${p}: must be one of ${JSON.stringify(s.enum)}`);
  if ('const' in s && canonicalJSON(s.const) !== canonicalJSON(v)) errs.push(`${p}: must equal ${JSON.stringify(s.const)}`);
  if (typeof v === 'string') {
    const len = [...v].length;
    if (typeof s.minLength === 'number' && len < s.minLength) errs.push(`${p}: shorter than minLength ${s.minLength}`);
    if (typeof s.maxLength === 'number' && len > s.maxLength) errs.push(`${p}: longer than maxLength ${s.maxLength}`);
    if (typeof s.pattern === 'string' && !new RegExp(s.pattern, 'u').test(v)) errs.push(`${p}: does not match pattern ${s.pattern}`);
  }
  if (typeof v === 'number') {
    if (typeof s.minimum === 'number' && v < s.minimum) errs.push(`${p}: ${v} < minimum ${s.minimum}`);
    if (typeof s.maximum === 'number' && v > s.maximum) errs.push(`${p}: ${v} > maximum ${s.maximum}`);
    if (typeof s.exclusiveMinimum === 'number' && v <= s.exclusiveMinimum) errs.push(`${p}: ${v} <= exclusiveMinimum ${s.exclusiveMinimum}`);
    if (typeof s.exclusiveMaximum === 'number' && v >= s.exclusiveMaximum) errs.push(`${p}: ${v} >= exclusiveMaximum ${s.exclusiveMaximum}`);
    if (typeof s.multipleOf === 'number' && s.multipleOf > 0 && Math.abs(v / s.multipleOf - Math.round(v / s.multipleOf)) > 1e-9) errs.push(`${p}: not a multiple of ${s.multipleOf}`);
  }
  if (Array.isArray(v)) {
    if (typeof s.minItems === 'number' && v.length < s.minItems) errs.push(`${p}: fewer than minItems ${s.minItems}`);
    if (typeof s.maxItems === 'number' && v.length > s.maxItems) errs.push(`${p}: more than maxItems ${s.maxItems}`);
    if (s.uniqueItems === true && new Set(v.map(canonicalJSON)).size !== v.length) errs.push(`${p}: items are not unique`);
    if (Array.isArray(s.items)) s.items.forEach((it, i) => i < v.length && validateSchema(it, v[i], `${p}[${i}]`, errs));
    else if (s.items !== undefined) v.forEach((x, i) => validateSchema(s.items, x, `${p}[${i}]`, errs));
  }
  if (isPlainObject(v)) {
    const props = isPlainObject(s.properties) ? s.properties : {};
    if (Array.isArray(s.required)) for (const k of s.required) if (!Object.prototype.hasOwnProperty.call(v, k)) errs.push(`${p}: missing required property "${k}"`);
    for (const [k, x] of Object.entries(v)) {
      if (Object.prototype.hasOwnProperty.call(props, k)) validateSchema(props[k], x, `${p}.${k}`, errs);
      else if (s.additionalProperties === false) errs.push(`${p}: unexpected property "${k}" (additionalProperties: false)`);
      else if (isPlainObject(s.additionalProperties)) validateSchema(s.additionalProperties, x, `${p}.${k}`, errs);
    }
    const nk = Object.keys(v).length;
    if (typeof s.minProperties === 'number' && nk < s.minProperties) errs.push(`${p}: fewer than minProperties ${s.minProperties}`);
    if (typeof s.maxProperties === 'number' && nk > s.maxProperties) errs.push(`${p}: more than maxProperties ${s.maxProperties}`);
  }
  if (Array.isArray(s.allOf)) for (const x of s.allOf) validateSchema(x, v, p, errs);
  if (Array.isArray(s.anyOf) && !s.anyOf.some((x) => validateSchema(x, v, p, []).length === 0)) errs.push(`${p}: matches none of anyOf`);
  if (Array.isArray(s.oneOf) && s.oneOf.filter((x) => validateSchema(x, v, p, []).length === 0).length !== 1) errs.push(`${p}: must match exactly one of oneOf`);
  if (s.not !== undefined && validateSchema(s.not, v, p, []).length === 0) errs.push(`${p}: must not match "not" schema`);
  return errs;
}

// Response parse order: whole text as JSON, else the last fenced json block, else the
// outermost {...}.
function parseStructured(response) {
  if (response !== null && typeof response === 'object') return { ok: true, value: response };
  const t = String(response ?? '').trim();
  try {
    return { ok: true, value: JSON.parse(t) };
  } catch {
    // fall through
  }
  const fences = [...t.matchAll(/```[ \t]*([A-Za-z0-9_-]*)[ \t]*\r?\n([\s\S]*?)```/g)];
  const tagged = fences.filter((f) => /^json5?$/i.test(f[1]));
  for (const pool of [tagged, fences]) {
    if (pool.length) {
      try {
        return { ok: true, value: JSON.parse(pool[pool.length - 1][2].trim()) };
      } catch {
        // fall through
      }
    }
  }
  const a = t.indexOf('{');
  const b = t.lastIndexOf('}');
  if (a >= 0 && b > a) {
    try {
      return { ok: true, value: JSON.parse(t.slice(a, b + 1)) };
    } catch {
      // fall through
    }
  }
  return { ok: false, error: '$: final message is not a JSON object (no parseable JSON, fenced json block, or {...} span)' };
}

// ---------------------------------------------------------------------------
// Journal and resume sources

class Journal {
  constructor(file) {
    this.file = file;
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, '');
  }

  write(o) {
    fs.appendFileSync(this.file, JSON.stringify(o) + '\n');
  }
}

// A resume source is a Claude run transcript dir (journal keys v2:...) or a ZCode run dir
// (keys zc1:...). Entries keep journal order; per label they are ordered by the `n`
// field when every entry carries one (ZCode journals), else by journal line order.
function loadResumeSource(from) {
  let st;
  try {
    st = fs.statSync(from);
  } catch {
    throw new UltracodeError('RESUME_SOURCE', `--resume-from ${from}: no such file or directory`);
  }
  const dir = st.isDirectory() ? from : path.dirname(from);
  const file = st.isDirectory() ? path.join(from, 'journal.jsonl') : from;
  if (!fs.existsSync(file)) throw new UltracodeError('RESUME_SOURCE', `--resume-from ${from}: no journal.jsonl`);
  const entries = [];
  const open = new Map();
  let bad = 0;
  fs.readFileSync(file, 'utf8')
    .split('\n')
    .forEach((line, order) => {
      if (!line.trim()) return;
      let j;
      try {
        j = JSON.parse(line);
      } catch {
        bad++;
        return;
      }
      if (j.type === 'started' && typeof j.key === 'string') {
        const e = { key: j.key, agentId: j.agentId ?? null, label: j.label ?? null, phase: j.phase ?? null, n: Number.isInteger(j.n) ? j.n : null, hasResult: false, result: undefined, order };
        entries.push(e);
        if (!open.has(j.key)) open.set(j.key, []);
        open.get(j.key).push(e);
      } else if (j.type === 'result' && typeof j.key === 'string') {
        const q = open.get(j.key) || [];
        let e = q.find((x) => !x.hasResult && j.agentId != null && x.agentId === j.agentId) || q.find((x) => !x.hasResult);
        if (!e) {
          e = { key: j.key, agentId: j.agentId ?? null, label: null, phase: null, n: null, hasResult: false, result: undefined, order };
          entries.push(e);
        }
        e.hasResult = true;
        e.result = j.result === undefined ? null : j.result;
        if (e.agentId == null) e.agentId = j.agentId ?? null;
      }
    });
  for (const e of entries) {
    if (e.label || !e.agentId) continue;
    try {
      const m = JSON.parse(fs.readFileSync(path.join(dir, `agent-${e.agentId}.meta.json`), 'utf8'));
      if (typeof m.description === 'string' && m.description) e.label = m.description;
      if (!e.phase && typeof m.workflowPhase === 'string') e.phase = m.workflowPhase;
    } catch {
      // no Claude meta.json for this agent
    }
  }
  const byKey = new Map();
  const byLabel = new Map();
  for (const e of entries) {
    if (!byKey.has(e.key)) byKey.set(e.key, []);
    byKey.get(e.key).push(e);
    if (e.label) {
      if (!byLabel.has(e.label)) byLabel.set(e.label, []);
      byLabel.get(e.label).push(e);
    }
  }
  for (const list of byLabel.values()) if (list.every((e) => e.n !== null)) list.sort((a, b) => a.n - b.n || a.order - b.order);
  return { dir: path.resolve(dir), file, entries, byKey, byLabel, bad, results: entries.filter((e) => e.hasResult).length };
}

// Match order: own-key exact match; else the nth agent() call with label L receives
// the nth recorded result for L. Each recorded result is consumed at most once.
class ResumeMatcher {
  constructor(sources) {
    this.sources = sources;
    this.labelCount = new Map();
    this.consumed = new Set();
  }

  take(key, label) {
    let n = null;
    if (label != null) {
      n = this.labelCount.get(label) ?? 0;
      this.labelCount.set(label, n + 1);
    }
    for (const src of this.sources) {
      const e = (src.byKey.get(key) || []).find((x) => x.hasResult && !this.consumed.has(x));
      if (e) {
        this.consumed.add(e);
        return { entry: e, via: 'key', n };
      }
    }
    if (label != null) {
      for (const src of this.sources) {
        const e = (src.byLabel.get(label) || [])[n];
        if (e && e.hasResult && !this.consumed.has(e)) {
          this.consumed.add(e);
          return { entry: e, via: 'label', n };
        }
      }
    }
    return { entry: null, via: null, n };
  }
}

// ---------------------------------------------------------------------------
// Live agent execution

function envInt(name, dflt) {
  const v = process.env[name];
  if (v === undefined || v === '') return dflt;
  const n = Number.parseInt(v, 10);
  return Number.isFinite(n) && n >= 0 ? n : dflt;
}

function splitCommand(s) {
  const out = [];
  let cur = '';
  let q = null;
  let has = false;
  for (let i = 0; i < s.length; i++) {
    const c = s[i];
    if (q) {
      if (c === q) q = null;
      else if (c === '\\' && q === '"' && i + 1 < s.length) cur += s[++i];
      else cur += c;
    } else if (c === '"' || c === "'") {
      q = c;
      has = true;
    } else if (/\s/.test(c)) {
      if (has || cur) out.push(cur);
      cur = '';
      has = false;
    } else if (c === '\\' && i + 1 < s.length) {
      cur += s[++i];
      has = true;
    } else {
      cur += c;
      has = true;
    }
  }
  if (has || cur) out.push(cur);
  return out;
}

function agentCommand() {
  const custom = process.env.ULTRACODE_AGENT_CMD;
  if (custom && custom.trim()) return splitCommand(custom.trim());
  const cliDir = process.env.ZCODE_CLI_DIR || '/Users/sac/dev/zcode-cli';
  return [process.execPath, path.join(cliDir, 'bin', 'zcode.js')];
}

function claudeHome() {
  return process.env.ULTRACODE_CLAUDE_HOME || path.join(os.homedir(), '.claude');
}

function ultracodeHome() {
  return process.env.ULTRACODE_HOME || path.join(os.homedir(), '.zcode', 'ultracode');
}

function runProcess(argv, { cwd, timeoutMs }) {
  return new Promise((resolve) => {
    let stdout = '';
    let stderr = '';
    let timer = null;
    let child;
    try {
      child = spawn(argv[0], argv.slice(1), { cwd, env: process.env, stdio: ['ignore', 'pipe', 'pipe'] });
    } catch (e) {
      resolve({ code: -1, stdout: '', stderr: String(e.message) });
      return;
    }
    child.stdout.on('data', (d) => (stdout += d));
    child.stderr.on('data', (d) => (stderr += d));
    child.on('error', (e) => {
      if (timer) clearTimeout(timer);
      resolve({ code: -1, stdout, stderr: stderr + String(e.message) });
    });
    child.on('close', (code, signal) => {
      if (timer) clearTimeout(timer);
      resolve({ code: code ?? (signal ? 128 : -1), stdout, stderr });
    });
    if (timeoutMs > 0) timer = setTimeout(() => child.kill('SIGKILL'), timeoutMs);
  });
}

function parseAgentStdout(stdout) {
  const t = String(stdout || '').trim();
  if (!t) return null;
  try {
    const j = JSON.parse(t);
    if (isPlainObject(j)) return j;
  } catch {
    // fall through to per-line scan
  }
  const lines = t.split('\n');
  for (let k = lines.length - 1; k >= 0; k--) {
    try {
      const j = JSON.parse(lines[k]);
      if (isPlainObject(j) && 'response' in j) return j;
    } catch {
      // not JSON
    }
  }
  return null;
}

const RATE_LIMIT_RE = /\b429\b|rate[\s_-]?limit|too many requests|\b1302\b/i;
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

// One agent turn, with bounded exponential backoff on rate limits (429 / 1302 / exit 75).
async function invokeAgent(prompt, cwd, resumeSession, shared) {
  const maxRl = envInt('ULTRACODE_RATE_LIMIT_RETRIES', 5);
  const base = envInt('ULTRACODE_BACKOFF_BASE_MS', 5000);
  const cap = envInt('ULTRACODE_BACKOFF_MAX_MS', 120000);
  const timeoutMs = envInt('ULTRACODE_AGENT_TIMEOUT_MS', 0);
  for (let rl = 0; ; rl++) {
    const argv = [...agentCommand(), '--prompt', prompt, '--json', '--cwd', cwd, '--mode', 'yolo'];
    if (resumeSession) argv.push('--resume', resumeSession);
    const r = await runProcess(argv, { cwd, timeoutMs });
    shared.stats.spawns++;
    const parsed = parseAgentStdout(r.stdout);
    const response = parsed ? parsed.response : undefined;
    if (r.code === 0 && parsed && (typeof response === 'string' || isPlainObject(response))) {
      return { ok: true, sessionId: parsed.sessionId ?? null, response };
    }
    const limited = r.code === 75 || RATE_LIMIT_RE.test(`${r.stderr}\n${r.stdout}`);
    if (limited && rl < maxRl && !shared.halted) {
      const wait = Math.min(cap, base * 2 ** rl);
      narrate(shared, `rate limited (exit ${r.code}); retry ${rl + 1}/${maxRl} in ${wait}ms`);
      await sleep(wait);
      continue;
    }
    const why = limited ? `rate limit persisted after ${maxRl} retries` : `exit ${r.code}: ${String(r.stderr || r.stdout).trim().split('\n').slice(-1)[0] || 'no output'}`;
    return { ok: false, sessionId: parsed ? parsed.sessionId ?? null : null, why };
  }
}

function buildHarness(prompt, opts, extra) {
  const lines = [
    'You are a subagent running one agent() step of an UltraCode workflow (a Claude Code Workflow script executed by ZCode).',
    'Your FINAL message IS the return value handed to the orchestrating script: raw data only. No greeting, no summary for a human, no commentary around it.',
  ];
  if (opts.agentType === 'Explore') {
    lines.push('READ-ONLY (agentType Explore): do not create, edit, move or delete files; do not commit, push, install or build; only read, search and run read-only commands.');
  } else if (opts.agentType) lines.push(`Agent type: ${opts.agentType}.`);
  if (extra.worktree) lines.push(`You are working in an isolated git worktree at ${extra.worktree}; keep every change inside it and commit there if the task calls for changes.`);
  if (opts.model || opts.effort) lines.push(`Requested model: ${opts.model ?? 'default'}; effort: ${opts.effort ?? 'default'} (advisory).`);
  if (opts.schema != null) {
    lines.push('Your final message must be exactly one JSON object (no code fences, no prose) that validates against this JSON Schema (Draft-07):');
    lines.push(JSON.stringify(opts.schema));
  }
  if (extra.label || extra.phase) lines.push(`Step: ${extra.label ?? '(unlabelled)'}${extra.phase ? ` [phase ${extra.phase}]` : ''}.`);
  lines.push('', '--- TASK ---', prompt);
  return lines.join('\n');
}

function reaskText(errs, schema) {
  return [
    'Your previous final message did not validate against the required JSON Schema. Validator errors:',
    ...errs.slice(0, 40).map((e) => `- ${e}`),
    'Reply again with ONLY the corrected JSON object as your final message (no prose, no code fences). Schema:',
    JSON.stringify(schema),
  ].join('\n');
}

function git(cwd, ...args) {
  const r = spawnSync('git', args, { cwd, encoding: 'utf8' });
  return { code: r.status, out: String(r.stdout || '').trim(), err: String(r.stderr || '').trim() };
}

function makeWorktree(cwd, dir) {
  const top = git(cwd, 'rev-parse', '--show-toplevel');
  if (top.code !== 0) throw new UltracodeError('WORKTREE', `isolation 'worktree' needs a git repository at ${cwd}: ${top.err}`);
  const head = git(cwd, 'rev-parse', 'HEAD');
  if (head.code !== 0) throw new UltracodeError('WORKTREE', `isolation 'worktree': no HEAD in ${top.out}`);
  fs.mkdirSync(path.dirname(dir), { recursive: true });
  const add = git(top.out, 'worktree', 'add', '--detach', dir, head.out);
  if (add.code !== 0) throw new UltracodeError('WORKTREE', `git worktree add ${dir}: ${add.err}`);
  return { dir, repo: top.out, head: head.out };
}

function finishWorktree(wt) {
  const st = git(wt.dir, 'status', '--porcelain');
  const h = git(wt.dir, 'rev-parse', 'HEAD');
  if (st.code === 0 && st.out === '' && h.out === wt.head) {
    const rm = git(wt.repo, 'worktree', 'remove', wt.dir);
    return { kept: rm.code !== 0, dir: wt.dir, head: h.out };
  }
  return { kept: true, dir: wt.dir, head: h.out, dirty: st.out !== '' };
}

class Semaphore {
  constructor(n) {
    this.n = Math.max(1, n);
    this.active = 0;
    this.queue = [];
  }

  async run(fn) {
    if (this.active >= this.n) await new Promise((r) => this.queue.push(r));
    else this.active++;
    try {
      return await fn();
    } finally {
      const next = this.queue.shift();
      if (next) next();
      else this.active--;
    }
  }
}

function narrate(shared, msg) {
  if (!shared.quiet) process.stderr.write(`[ultracode] ${msg}\n`);
}

async function liveAgent(shared, a) {
  return shared.sem.run(async () => {
    if (shared.halted) return null;
    shared.stats.live++;
    let wt = null;
    let cwd = shared.cwd;
    if (a.opts.isolation === 'worktree') {
      try {
        wt = makeWorktree(shared.cwd, path.join(shared.runDir, 'worktrees', String(a.seq).padStart(4, '0')));
        cwd = wt.dir;
      } catch (e) {
        narrate(shared, `agent ${a.label ?? a.seq}: ${e.message}`);
        shared.journal.write({ type: 'log', msg: `agent ${a.label ?? a.seq} not started: ${e.message}` });
        return null;
      }
    }
    const harness = buildHarness(a.prompt, a.opts, { label: a.label, phase: a.phase, worktree: wt && wt.dir });
    const maxRetries = envInt('MAX_STRUCTURED_OUTPUT_RETRIES', 5);
    let prompt = harness;
    let resume = null;
    let sessionId = null;
    let started = false;
    let retries = 0;
    let result = null;
    for (;;) {
      const out = await invokeAgent(prompt, cwd, resume, shared);
      if (out.sessionId) sessionId = out.sessionId;
      if (!started) {
        const line = { type: 'started', key: a.key, agentId: sessionId, label: a.label, phase: a.phase };
        if (a.n !== null) line.n = a.n;
        shared.journal.write(line);
        started = true;
      }
      if (!out.ok) {
        narrate(shared, `agent ${a.label ?? a.seq} -> null (${out.why})`);
        break;
      }
      if (a.opts.schema == null) {
        result = out.response;
        break;
      }
      const parsed = parseStructured(out.response);
      const errs = parsed.ok ? validateSchema(a.opts.schema, parsed.value) : [parsed.error];
      if (!errs.length) {
        result = parsed.value;
        break;
      }
      if (retries >= maxRetries || shared.halted) {
        narrate(shared, `agent ${a.label ?? a.seq} -> null (structured output invalid after ${retries} re-asks)`);
        break;
      }
      retries++;
      const reask = reaskText(errs, a.opts.schema);
      if (out.sessionId) {
        resume = out.sessionId;
        prompt = reask;
      } else {
        resume = null;
        prompt = `${harness}\n\n${reask}`;
      }
    }
    if (wt) {
      const fin = finishWorktree(wt);
      if (fin.kept) {
        shared.journal.write({ type: 'log', msg: `worktree kept: ${fin.dir} (agent ${a.label ?? a.seq}, head ${fin.head}${fin.dirty ? ', uncommitted changes' : ''})` });
      }
    }
    if (result !== null && result !== undefined) shared.journal.write({ type: 'result', key: a.key, agentId: sessionId, result });
    return result ?? null;
  });
}

// ---------------------------------------------------------------------------
// Run context and primitives

function halt(shared, err) {
  if (!shared.halted) shared.halted = err;
  return shared.halted;
}

async function runAgent(shared, p, o) {
  let prompt;
  let opts;
  if (isPlainObject(p)) {
    const { prompt: pp, ...rest } = p;
    prompt = pp;
    opts = { ...rest, ...(isPlainObject(o) ? o : {}) };
  } else {
    prompt = p;
    opts = isPlainObject(o) ? { ...o } : {};
  }
  if (shared.halted) throw shared.halted;
  prompt = typeof prompt === 'string' ? prompt : prompt == null ? '' : String(prompt);
  shared.stats.calls++;
  if (shared.stats.calls > shared.maxAgents) {
    if (shared.mode === 'preflight') throw halt(shared, new PreflightStop('agent cap'));
    throw halt(shared, new UltracodeError('AGENT_CAP_EXCEEDED', `more than ${shared.maxAgents} agent() calls in one run`));
  }
  if (opts.schema != null) {
    const errs = schemaPreflight(opts.schema);
    if (errs.length) {
      throw halt(
        shared,
        new UltracodeError('SCHEMA_PREFLIGHT', `contradictory schema for agent ${JSON.stringify(opts.label ?? prompt.slice(0, 60))}: ${errs.join('; ')}`, {
          label: opts.label ?? null,
          errors: errs,
        }),
      );
    }
  }
  const label = opts.label != null ? String(opts.label) : null;
  const phase = opts.phase != null ? String(opts.phase) : shared.currentPhase;
  const key = 'zc1:' + sha256(canonicalJSON({ prompt, opts: jsonSafe(opts) }));
  const seq = ++shared.seq;
  const { entry, n } = shared.matcher.take(key, label);
  if (entry) {
    shared.stats.resumed++;
    if (shared.journal) {
      const line = { type: 'started', key, agentId: entry.agentId, label, phase, resumed: true };
      if (n !== null) line.n = n;
      shared.journal.write(line);
      shared.journal.write({ type: 'result', key, agentId: entry.agentId, result: entry.result });
    }
    return entry.result === null || entry.result === undefined ? null : structuredClone(entry.result);
  }
  if (shared.mode !== 'live') {
    shared.stats.liveNeeded++;
    return null;
  }
  const result = await liveAgent(shared, { prompt, opts, key, label, phase, seq, n });
  if (result === null) shared.stats.nulls++;
  return result;
}

function makePrimitives(shared, ctx) {
  const drop = (e) => {
    if (e && e !== shared.halted) narrate(shared, `dropped to null: ${e && e.message ? e.message : e}`);
    return null;
  };
  const agent = (p, o) => runAgent(shared, p, o);
  const parallel = async (items) => {
    const list = Array.from(items ?? []);
    return Promise.all(
      list.map(async (it) => {
        try {
          return await (typeof it === 'function' ? it() : it);
        } catch (e) {
          return drop(e);
        }
      }),
    );
  };
  const pipeline = async (items, ...stages) => {
    const list = Array.from(items ?? []);
    return Promise.all(
      list.map(async (item, index) => {
        let v = item;
        for (const stage of stages) {
          try {
            v = await stage(v, item, index);
          } catch (e) {
            return drop(e);
          }
        }
        return v;
      }),
    );
  };
  const phase = (title) => {
    shared.currentPhase = String(title);
    narrate(shared, `== ${title}`);
  };
  const log = (msg) => {
    const m = typeof msg === 'string' ? msg : JSON.stringify(msg);
    if (shared.journal) shared.journal.write({ type: 'log', msg: m });
    narrate(shared, m);
  };
  const budget = Object.freeze({ total: null, spent: () => 0, remaining: () => Infinity });
  const workflow = (ref, childArgs) => runChildWorkflow(shared, ctx, ref, childArgs);
  return { agent, pipeline, parallel, phase, log, budget, workflow, args: ctx.args };
}

function resolveWorkflowRef(ref, parentScript, cwd) {
  let p = null;
  let name = null;
  if (isPlainObject(ref)) {
    p = ref.scriptPath ?? ref.path ?? null;
    name = ref.name ?? null;
  } else if (typeof ref === 'string') {
    if (ref.includes('/') || /\.m?js$/.test(ref)) p = ref;
    else name = ref;
  }
  const candidates = [];
  if (p) {
    if (path.isAbsolute(p)) candidates.push(p);
    else candidates.push(path.resolve(path.dirname(parentScript), p), path.resolve(cwd, p));
  } else if (name) {
    for (const ext of ['.js', '.mjs']) {
      candidates.push(path.join(cwd, '.claude', 'workflows', name + ext), path.join(claudeHome(), 'workflows', name + ext));
    }
  }
  const hit = candidates.find((c) => fs.existsSync(c));
  if (!hit) throw new UltracodeError('WORKFLOW_NOT_FOUND', `workflow(${JSON.stringify(ref)}): not found (looked in ${candidates.join(', ') || 'nothing'})`);
  return hit;
}

async function runChildWorkflow(shared, parent, ref, childArgs) {
  if (parent.depth >= 1) throw new UltracodeError('WORKFLOW_DEPTH', 'workflow() runs a child one level deep only');
  const scriptPath = resolveWorkflowRef(ref, parent.scriptPath, shared.cwd);
  shared.children++;
  const ctx = { runId: `${parent.runId}-w${shared.children}`, depth: parent.depth + 1, args: childArgs === undefined ? null : childArgs, scriptPath };
  narrate(shared, `workflow ${path.basename(scriptPath)} (child ${ctx.runId})`);
  return executeScript(shared, ctx);
}

function wrapLoadError(e, scriptPath) {
  if (e instanceof UltracodeError) return e;
  if (e instanceof SyntaxError) return new UltracodeError('SCRIPT_LOAD', `${scriptPath}: ${e.message}`);
  return e;
}

async function executeScript(shared, ctx) {
  let src;
  try {
    src = fs.readFileSync(ctx.scriptPath, 'utf8');
  } catch (e) {
    throw new UltracodeError('SCRIPT_LOAD', `cannot read ${ctx.scriptPath}: ${e.message}`);
  }
  const info = extractMeta(src);
  if (!info.ok) throw new UltracodeError(info.code, `${ctx.scriptPath}: ${info.message}`);
  ctx.meta = normalizeMeta(info.meta);
  const prims = makePrimitives(shared, ctx);
  REGISTRY.set(ctx.runId, prims);
  ensureLoaderHooks();
  try {
    let form = detectForm(src);
    let mod;
    try {
      mod = await import(scriptUrl(ctx.scriptPath, ctx.runId, form));
    } catch (e) {
      if (form === 'module' && e instanceof SyntaxError) {
        form = 'body';
        try {
          mod = await import(scriptUrl(ctx.scriptPath, ctx.runId, form, 2));
        } catch (e2) {
          throw wrapLoadError(e2, ctx.scriptPath);
        }
      } else throw wrapLoadError(e, ctx.scriptPath);
    }
    if (form === 'body') return await mod.default(prims);
    const run = typeof mod.run === 'function' ? mod.run : typeof mod.default === 'function' ? mod.default : null;
    if (!run) throw new UltracodeError('SCRIPT_LOAD', `${ctx.scriptPath}: module form must export async function run(promptContext)`);
    return await run(ctx.args);
  } finally {
    REGISTRY.delete(ctx.runId);
  }
}

function newShared(o) {
  return {
    mode: o.mode,
    quiet: o.quiet,
    journal: o.journal ?? null,
    matcher: o.matcher,
    sem: new Semaphore(o.concurrency),
    maxAgents: o.maxAgents,
    runDir: o.runDir ?? null,
    cwd: o.cwd,
    stats: { calls: 0, live: 0, resumed: 0, nulls: 0, liveNeeded: 0, spawns: 0 },
    halted: null,
    currentPhase: null,
    seq: 0,
    children: 0,
  };
}

// ---------------------------------------------------------------------------
// CLI

const USAGE = `usage:
  node ultracode-run.mjs run <script.js> [--args <json|text|@file>] [--run-dir <dir>]
       [--resume-from <claudeTranscriptDir|zcodeRunDir>] [--cwd <dir>] [--concurrency N]
       [--dry-run] [--json]
  node ultracode-run.mjs selftest`;

function parseRunArgs(argv) {
  const o = { script: null, args: undefined, runDir: null, resumeFrom: null, cwd: null, concurrency: null, dryRun: false, json: false };
  for (let i = 0; i < argv.length; i++) {
    let a = argv[i];
    let inline;
    if (a.startsWith('--') && a.includes('=')) {
      inline = a.slice(a.indexOf('=') + 1);
      a = a.slice(0, a.indexOf('='));
    }
    const val = () => {
      if (inline !== undefined) return inline;
      if (i + 1 >= argv.length) throw new UltracodeError('USAGE', `${a} needs a value\n${USAGE}`);
      return argv[++i];
    };
    switch (a) {
      case '--args':
        o.args = val();
        break;
      case '--run-dir':
        o.runDir = val();
        break;
      case '--resume-from':
        o.resumeFrom = val();
        break;
      case '--cwd':
        o.cwd = val();
        break;
      case '--concurrency': {
        const n = Number.parseInt(val(), 10);
        if (!(n > 0)) throw new UltracodeError('USAGE', '--concurrency must be a positive integer');
        o.concurrency = n;
        break;
      }
      case '--dry-run':
        o.dryRun = true;
        break;
      case '--json':
        o.json = true;
        break;
      default:
        if (a.startsWith('--')) throw new UltracodeError('USAGE', `unknown option ${a}\n${USAGE}`);
        if (o.script) throw new UltracodeError('USAGE', `unexpected argument ${a}\n${USAGE}`);
        o.script = a;
    }
  }
  if (!o.script) throw new UltracodeError('USAGE', `run needs a script path\n${USAGE}`);
  return o;
}

function loadArgs(raw) {
  if (raw === undefined) return null;
  let text = raw;
  if (raw.startsWith('@')) {
    try {
      text = fs.readFileSync(raw.slice(1), 'utf8');
    } catch (e) {
      throw new UltracodeError('USAGE', `--args ${raw}: ${e.message}`);
    }
  }
  try {
    return JSON.parse(text);
  } catch {
    return raw.startsWith('@') ? text.replace(/\r?\n$/, '') : text;
  }
}

function defaultConcurrency() {
  const env = envInt('ULTRACODE_CONCURRENCY', 0);
  if (env > 0) return env;
  const cpus = typeof os.availableParallelism === 'function' ? os.availableParallelism() : os.cpus().length;
  return Math.max(1, Math.min(16, cpus - 2));
}

function newRunId() {
  return 'zc-' + new Date().toISOString().replace(/[-:TZ]/g, '').replace(/\..*/, '') + '-' + randomBytes(3).toString('hex');
}

function withTimeout(promise, ms, onTimeout) {
  if (!(ms > 0)) return promise;
  let t;
  return Promise.race([
    promise.finally(() => clearTimeout(t)),
    new Promise((resolve) => {
      t = setTimeout(() => resolve(onTimeout()), ms);
    }),
  ]);
}

const FATAL_PASS_CODES = new Set(['META_MISSING', 'META_NOT_LITERAL', 'META_INVALID', 'SCHEMA_PREFLIGHT', 'SCRIPT_LOAD', 'RESUME_SOURCE', 'USAGE']);

async function cmdRun(argv) {
  const o = parseRunArgs(argv);
  const t0 = Date.now();
  const scriptPath = path.resolve(o.script);
  const args = loadArgs(o.args);
  const cwd = path.resolve(o.cwd ?? process.cwd());
  const concurrency = o.concurrency ?? defaultConcurrency();
  const maxAgents = envInt('ULTRACODE_MAX_AGENTS', 1000) || 1000;
  const sources = o.resumeFrom ? [loadResumeSource(path.resolve(o.resumeFrom))] : [];
  const runId = newRunId();

  // Pass 1: dry / preflight. Executes control flow with cached results; any agent that
  // would need a live spawn resolves null. Contradictory schemas halt here, before any
  // spawn.
  const pre = newShared({ mode: o.dryRun ? 'dry' : 'preflight', quiet: true, matcher: new ResumeMatcher(sources), concurrency, maxAgents, cwd });
  let preErr = null;
  try {
    await withTimeout(executeScript(pre, { runId: `${runId}-pre`, depth: 0, args, scriptPath }), envInt('ULTRACODE_PREFLIGHT_TIMEOUT_MS', 30000), () =>
      halt(pre, new PreflightStop('timeout')),
    );
  } catch (e) {
    preErr = e;
  }
  if (pre.halted) preErr = pre.halted;
  if (preErr instanceof PreflightStop) preErr = null;

  if (o.dryRun) {
    const out = {
      live_agents_needed: pre.stats.liveNeeded,
      resumed: pre.stats.resumed,
      completed: pre.stats.liveNeeded === 0 && !preErr,
      agent_calls: pre.stats.calls,
    };
    if (preErr) out.error = errInfo(preErr);
    process.stdout.write(JSON.stringify(out, null, o.json ? 0 : 2) + '\n');
    return preErr ? 1 : 0;
  }
  if (preErr && FATAL_PASS_CODES.has(preErr.code)) return reportFailure(o, runId, null, preErr, { live_agents: 0, resumed_agents: 0, null_agents: 0, duration_ms: Date.now() - t0 });

  // Pass 2: live.
  const runDir = path.resolve(o.runDir ?? path.join(ultracodeHome(), 'runs', runId));
  const journalFile = path.join(runDir, 'journal.jsonl');
  if (fs.existsSync(journalFile)) fs.renameSync(journalFile, path.join(runDir, `journal.${runId}.prev.jsonl`));
  const journal = new Journal(journalFile);
  journal.write({ type: 'launched' });
  fs.writeFileSync(
    path.join(runDir, 'run.json'),
    JSON.stringify({ runId, script: scriptPath, args, cwd, resumeFrom: o.resumeFrom ? path.resolve(o.resumeFrom) : null, concurrency, startedAt: new Date(t0).toISOString() }, null, 2) + '\n',
  );
  const shared = newShared({ mode: 'live', quiet: false, journal, matcher: new ResumeMatcher(sources), concurrency, maxAgents, cwd, runDir });
  const ctx = { runId, depth: 0, args, scriptPath };
  let result;
  let err = null;
  try {
    result = await executeScript(shared, ctx);
  } catch (e) {
    err = e;
  }
  if (shared.halted) err = shared.halted;
  const summary = { live_agents: shared.stats.live, resumed_agents: shared.stats.resumed, null_agents: shared.stats.nulls, duration_ms: Date.now() - t0 };
  if (ctx.meta) {
    const runJson = JSON.parse(fs.readFileSync(path.join(runDir, 'run.json'), 'utf8'));
    runJson.meta = ctx.meta;
    fs.writeFileSync(path.join(runDir, 'run.json'), JSON.stringify(runJson, null, 2) + '\n');
  }
  if (err) return reportFailure(o, runId, runDir, err, summary);
  fs.writeFileSync(path.join(runDir, 'result.json'), JSON.stringify(result === undefined ? null : result, null, 2) + '\n');
  fs.writeFileSync(path.join(runDir, 'summary.json'), JSON.stringify(summary, null, 2) + '\n');
  if (o.json) process.stdout.write(JSON.stringify({ runId, runDir, result: result === undefined ? null : result, summary }) + '\n');
  else {
    process.stdout.write(`run ${runId} complete: ${summary.live_agents} live, ${summary.resumed_agents} resumed, ${summary.null_agents} null, ${summary.duration_ms}ms\n`);
    process.stdout.write(`result: ${path.join(runDir, 'result.json')}\n`);
  }
  return 0;
}

function reportFailure(o, runId, runDir, err, summary) {
  const info = errInfo(err);
  summary.error = info;
  if (runDir) fs.writeFileSync(path.join(runDir, 'summary.json'), JSON.stringify(summary, null, 2) + '\n');
  process.stderr.write(`ultracode-run: ${info.code}: ${info.message}\n`);
  if (o.json) process.stdout.write(JSON.stringify({ runId, runDir, error: info, summary }) + '\n');
  return 1;
}

// ---------------------------------------------------------------------------
// selftest: real processes, a real tmp git repo, real files; the only double is the
// scripted agent backend (ULTRACODE_AGENT_CMD), which pins model nondeterminism.

const ST_SCENARIOS = {
  alpha: { replies: ['alpha'] },
  'b-json': { replies: [{ json: { n: 2 } }] },
  echo: { replies: [{ echo: true }] },
  plan: { replies: [{ json: { targets: ['x', 'y', 'z'] } }] },
  'build-x': { replies: ['built-x'] },
  'build-y': { replies: ['built-y'] },
  'build-z': { replies: ['built-z'] },
  tag: { replies: ['tagged-done'] },
  p1: { replies: ['one'] },
  's1-a': { replies: ['S1-a'] },
  's1-b': { replies: ['S1-b'] },
  's1-c': { replies: ['S1-c'] },
  fenced: { replies: ['draft:\n```json\n{"v": 0}\n```\nrevised:\n```json\n{"v": 4}\n```\n'] },
  braces: { replies: ['result: {"v": 5} (done)'] },
  reask: { replies: ['no json here', { json: { v: 0 } }, { json: { v: 6 } }] },
  fresh: { replies: [{ text: 'nope', no_session: true }, { json: { v: 7 }, no_session: true }] },
  never: { replies: [{ json: { v: 'x' } }] },
  ratelimit: { replies: [{ exit: 75, stderr: '429 Too Many Requests' }, { exit: 1, stderr: 'API error 1302: rate limit reached' }, 'recovered'] },
  dead: { replies: [{ exit: 1, stderr: 'fatal: backend crashed' }] },
  'wt-write': { replies: [{ write: { file: 'made-by-agent.txt', content: 'hi\n' }, echo: true }] },
  'wt-clean': { replies: [{ echo: true }] },
  slow: { replies: [{ sleep_ms: 250, text: 'slept' }] },
  cap: { replies: ['capped'] },
  child: { replies: ['from-child'] },
  k1: { replies: ['K1'] },
  k2: { replies: [{ json: { k: 2 } }] },
  unfinished: { replies: ['finished-live'] },
};

const ST_FIXTURES = {
  'body.js': `export const meta = {
  name: 'st-body',
  description: 'body form fixture', // comment inside the literal
  phases: [{ title: 'One', detail: 'first' }, { title: 'Two', detail: 'second' }],
}
import path from 'node:path'
phase('One')
log('hello ' + args.who)
const a = await agent('say A SCRIPTED:alpha', { label: 'a', phase: 'One' })
const b = await agent({ prompt: 'say B SCRIPTED:b-json', label: 'b', schema: { type: 'object', properties: { n: { type: 'integer' } }, required: ['n'], additionalProperties: false } })
phase('Two')
const c = await agent('explore SCRIPTED:echo', { label: 'c', agentType: 'Explore' })
return { a: a, b: b, c: JSON.parse(c), base: path.basename('/x/y.txt'), budgetTotal: budget.total, remaining: budget.remaining() === Infinity }
`,
  'helper.mjs': `import { agent } from "claude";
export async function tag(x) { return agent("tag " + x + " SCRIPTED:tag", { label: "tag" }); }
`,
  'module.js': `import { agent, parallel, pipeline } from "claude";
import { tag } from "./helper.mjs";
export const meta = { name: "st-module", description: "module form fixture", phases: ["discover", "build"] };
export async function run(promptContext) {
  const plan = await agent({ prompt: "plan for " + promptContext + " SCRIPTED:plan", label: "plan", schema: { type: "object", required: ["targets"], properties: { targets: { type: "array", items: { type: "string" }, minItems: 1 } }, additionalProperties: false } });
  if (!plan) throw new Error("dropped");
  const built = await parallel(plan.targets.map(function (t) { return agent({ prompt: "build " + t + " SCRIPTED:build-" + t, label: "build:" + t }); }));
  const tagged = await tag("done");
  return { built: built, tagged: tagged, ctx: promptContext, pipelineType: typeof pipeline };
}
`,
  'flow.js': `export const meta = { name: 'st-flow', description: 'parallel and pipeline semantics' }
const par = await parallel([
  function () { return agent('p1 SCRIPTED:p1', { label: 'p1' }) },
  function () { throw new Error('boom') },
  function () { return Promise.reject(new Error('nope')) },
  function () { return 7 },
])
const seen = []
const pipe = await pipeline(['a', 'b', 'c'],
  function (prev, item, i) { seen.push('s1:' + prev + ':' + item + ':' + i); return agent('stage1 ' + item + ' SCRIPTED:s1-' + item, { label: 's1:' + item }) },
  function (prev, item, i) { if (item === 'b') throw new Error('drop b'); return prev + '+' + item + i },
)
return { par: par, pipe: pipe, seen: seen.sort() }
`,
  'meta-var.js': `const NAME = 'x'
export const meta = { name: NAME, description: 'not a literal' }
return await agent('never SCRIPTED:alpha')
`,
  'meta-call.js': `export const meta = Object.freeze({ name: 'x', description: 'not a literal' })
return await agent('never SCRIPTED:alpha')
`,
  'preflight-required.js': `export const meta = { name: 'st-preflight-required', description: 'contradictory schema after a good one' }
const first = await agent('ok SCRIPTED:alpha', { label: 'first', schema: { type: 'object', properties: { a: { type: 'string' } }, required: ['a'] } })
const second = await agent('bad SCRIPTED:alpha', { label: 'second', schema: { type: 'object', properties: { a: { type: 'string' } }, required: ['a', 'b'], additionalProperties: false } })
return { first: first, second: second }
`,
  'preflight-type.js': `export const meta = { name: 'st-preflight-type', description: 'unknown type name' }
return await agent('bad SCRIPTED:alpha', { schema: { type: 'object', properties: { a: { type: 'strnig' } } } })
`,
  'preflight-root.js': `export const meta = { name: 'st-preflight-root', description: 'non-object root' }
return await agent('bad SCRIPTED:alpha', { schema: { type: 'array', items: { type: 'string' } } })
`,
  'reask.js': `export const meta = { name: 'st-reask', description: 'structured output parse, validate, re-ask' }
const S = { type: 'object', properties: { v: { type: 'integer', minimum: 1 } }, required: ['v'], additionalProperties: false }
const fenced = await agent('fenced SCRIPTED:fenced', { label: 'fenced', schema: S })
const braces = await agent('braces SCRIPTED:braces', { label: 'braces', schema: S })
const reask = await agent('reask SCRIPTED:reask', { label: 'reask', schema: S })
const fresh = await agent('fresh SCRIPTED:fresh', { label: 'fresh', schema: S })
const never = await agent('never SCRIPTED:never', { label: 'never', schema: S })
return { fenced: fenced, braces: braces, reask: reask, fresh: fresh, never: never }
`,
  'ratelimit.js': `export const meta = { name: 'st-ratelimit', description: 'rate limits back off; hard failures resolve null' }
const limited = await agent('rl SCRIPTED:ratelimit', { label: 'rl' })
const dead = await agent('dead SCRIPTED:dead', { label: 'dead' })
return { limited: limited, dead: dead }
`,
  'worktree.js': `export const meta = { name: 'st-worktree', description: 'isolation worktree kept when changed, removed when clean' }
const changed = await agent('write SCRIPTED:wt-write', { label: 'wt-write', isolation: 'worktree' })
const clean = await agent('look SCRIPTED:wt-clean', { label: 'wt-clean', isolation: 'worktree' })
return { changed: JSON.parse(changed), clean: JSON.parse(clean) }
`,
  'concurrency.js': `export const meta = { name: 'st-concurrency', description: 'live spawns respect the concurrency cap' }
const xs = [1, 2, 3, 4, 5, 6]
return await parallel(xs.map(function (x) { return function () { return agent('slow ' + x + ' SCRIPTED:slow', { label: 'slow:' + x }) } }))
`,
  'cap.js': `export const meta = { name: 'st-cap', description: 'agent cap halts the run' }
const out = []
for (const i of [1, 2, 3, 4, 5]) out.push(await agent('cap ' + i + ' SCRIPTED:cap', { label: 'cap:' + i }))
return out
`,
  'parent.js': `export const meta = { name: 'st-parent', description: 'workflow() runs a child inline, one level deep' }
const byPath = await workflow({ scriptPath: args.child }, { n: 2, self: args.child })
const byName = await workflow('st-child', { n: 3, self: args.child })
const byHome = await workflow('st-home', { n: 4, self: args.child })
return { byPath: byPath, byName: byName, byHome: byHome, budgetTotal: budget.total, remaining: budget.remaining() === Infinity }
`,
  'child.js': `export const meta = { name: 'st-child', description: 'child workflow' }
const v = await agent('child ' + args.n + ' SCRIPTED:child', { label: 'child:' + args.n })
let nested = null
try { await workflow({ scriptPath: args.self }, { n: 9 }) } catch (e) { nested = e.code || String(e.message) }
return { v: v, n: args.n, nested: nested }
`,
  'resume-key.js': `export const meta = { name: 'st-resume-key', description: 'own-key resume (no labels)' }
const a = await agent('k1 SCRIPTED:k1')
const b = await agent('k2 SCRIPTED:k2', { schema: { type: 'object', properties: { k: { type: 'integer' } }, required: ['k'] } })
return [a, b]
`,
  'resume-label.js': `export const meta = { name: 'st-resume-label', description: 'label resume against a Claude journal' }
const s = await agent('survey prompt differs SCRIPTED:dead', { label: 'survey:x', schema: { type: 'object', properties: { ok: { type: 'boolean' } }, required: ['ok'] } })
const d = await parallel([function () { return agent('d1 SCRIPTED:dead', { label: 'dup' }) }, function () { return agent('d2 SCRIPTED:dead', { label: 'dup' }) }])
const m = await agent('m SCRIPTED:dead', { label: 'meta-labelled' })
const u = await agent('u SCRIPTED:unfinished', { label: 'unfinished' })
return { s: s, d: d, m: m, u: u }
`,
};

function readJsonl(file) {
  if (!fs.existsSync(file)) return [];
  return fs
    .readFileSync(file, 'utf8')
    .split('\n')
    .filter((l) => l.trim())
    .map((l) => JSON.parse(l));
}

function maxOverlap(calls) {
  const ev = [];
  for (const c of calls) ev.push([c.t0, 1], [c.t1, -1]);
  ev.sort((a, b) => a[0] - b[0] || a[1] - b[1]);
  let cur = 0;
  let max = 0;
  for (const [, d] of ev) {
    cur += d;
    max = Math.max(max, cur);
  }
  return max;
}

function deepEqual(a, b) {
  return canonicalJSON(a) === canonicalJSON(b);
}

async function cmdSelftest() {
  const backend = process.env.ULTRACODE_SELFTEST_AGENT || path.resolve(SELF_DIR, '..', '..', '..', 'test', 'ultracode-scripted-agent.mjs');
  const results = [];
  const record = (name, fn) => {
    try {
      fn();
      results.push([name, null]);
      process.stdout.write(`PASS ${name}\n`);
    } catch (e) {
      results.push([name, e.message]);
      process.stdout.write(`FAIL ${name}: ${e.message}\n`);
    }
  };
  if (!fs.existsSync(backend)) {
    process.stdout.write(`FAIL backend: scripted agent backend not found at ${backend} (set ULTRACODE_SELFTEST_AGENT)\n`);
    return 1;
  }
  const root = fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(), 'ultracode-selftest-')));
  const repo = path.join(root, 'repo');
  const fx = path.join(root, 'fixtures');
  const claudeHomeDir = path.join(root, 'claude-home');
  const zhome = path.join(root, 'zcode-home');
  fs.mkdirSync(repo, { recursive: true });
  fs.mkdirSync(fx, { recursive: true });
  fs.mkdirSync(path.join(claudeHomeDir, 'workflows'), { recursive: true });
  fs.mkdirSync(path.join(repo, '.claude', 'workflows'), { recursive: true });
  for (const [name, src] of Object.entries(ST_FIXTURES)) fs.writeFileSync(path.join(fx, name), src);
  fs.copyFileSync(path.join(fx, 'child.js'), path.join(repo, '.claude', 'workflows', 'st-child.js'));
  fs.copyFileSync(path.join(fx, 'child.js'), path.join(claudeHomeDir, 'workflows', 'st-home.js'));
  const g = (...a) => {
    const r = git(repo, ...a);
    if (r.code !== 0) throw new Error(`git ${a.join(' ')}: ${r.err}`);
    return r.out;
  };
  g('init', '-q', '-b', 'main');
  g('config', 'user.email', 'selftest@ultracode.local');
  g('config', 'user.name', 'ultracode selftest');
  fs.writeFileSync(path.join(repo, 'README.md'), 'selftest repo\n');
  fs.writeFileSync(path.join(repo, '.gitignore'), '.claude/\n');
  g('add', 'README.md', '.gitignore');
  g('commit', '-q', '-m', 'init');

  let caseNo = 0;
  const cli = (args, extraEnv = {}) => {
    caseNo++;
    const state = extraEnv.ULTRACODE_SCRIPTED_STATE ?? path.join(root, `state-${caseNo}`);
    fs.mkdirSync(state, { recursive: true });
    fs.writeFileSync(path.join(state, 'scenarios.json'), JSON.stringify(ST_SCENARIOS));
    const env = {
      ...process.env,
      ULTRACODE_AGENT_CMD: JSON.stringify(backend),
      ULTRACODE_SCRIPTED_STATE: state,
      ULTRACODE_HOME: zhome,
      ULTRACODE_CLAUDE_HOME: claudeHomeDir,
      ULTRACODE_BACKOFF_BASE_MS: '20',
      ULTRACODE_BACKOFF_MAX_MS: '200',
      ...extraEnv,
    };
    for (const k of ['ULTRACODE_CONCURRENCY', 'ULTRACODE_MAX_AGENTS', 'MAX_STRUCTURED_OUTPUT_RETRIES']) if (!(k in extraEnv)) delete env[k];
    const r = spawnSync(process.execPath, [SELF, ...args], { cwd: repo, env, encoding: 'utf8', timeout: 120000 });
    let json = null;
    try {
      json = JSON.parse(String(r.stdout).trim().split('\n').pop());
    } catch {
      json = null;
    }
    return { code: r.status, stdout: r.stdout, stderr: r.stderr, json, state, calls: readJsonl(path.join(state, 'calls.jsonl')) };
  };
  const check = (cond, msg) => {
    if (!cond) throw new Error(msg);
  };
  const run = (fixture, extra = [], env = {}) => {
    const runDir = path.join(root, 'runs', `${fixture.replace(/\W/g, '_')}-${caseNo + 1}`);
    const r = cli(['run', path.join(fx, fixture), '--run-dir', runDir, '--cwd', repo, '--json', ...extra], env);
    r.runDir = runDir;
    r.journal = readJsonl(path.join(runDir, 'journal.jsonl'));
    return r;
  };
  const ok = (r) => check(r.code === 0 && r.json && !r.json.error, `exit ${r.code}: ${String(r.stderr).trim().split('\n').slice(-3).join(' | ')}`);

  record('body-form: globals, top-level await, return, import hoist, phases, journal, summary', () => {
    const r = run('body.js', ['--args', '{"who":"zcode"}']);
    ok(r);
    const res = r.json.result;
    check(res.a === 'alpha' && deepEqual(res.b, { n: 2 }) && res.base === 'y.txt', `result ${JSON.stringify(res)}`);
    check(res.budgetTotal === null && res.remaining === true, 'budget total null / remaining Infinity');
    check(res.c.readOnly === true, 'Explore agent must get the READ-ONLY harness instruction');
    check(r.journal[0] && r.journal[0].type === 'launched', 'journal starts with launched');
    const started = r.journal.filter((l) => l.type === 'started');
    const results = r.journal.filter((l) => l.type === 'result');
    check(started.length === 3 && results.length === 3, `3 started + 3 result lines, got ${started.length}/${results.length}`);
    check(started.every((l) => /^zc1:[0-9a-f]{64}$/.test(l.key) && typeof l.agentId === 'string' && l.agentId.startsWith('sess-')), 'started lines carry zc1 keys and the sessionId');
    const a = started.find((l) => l.label === 'a');
    check(a && a.key === 'zc1:' + sha256(canonicalJSON({ prompt: 'say A SCRIPTED:alpha', opts: { label: 'a', phase: 'One' } })), 'key = zc1:sha256(canonical {prompt, opts})');
    check(started.find((l) => l.label === 'c').phase === 'Two', 'phase() sets the phase of unphased agents');
    check(r.journal.some((l) => l.type === 'log' && l.msg === 'hello zcode'), 'log() line in journal');
    const onDisk = JSON.parse(fs.readFileSync(path.join(r.runDir, 'result.json'), 'utf8'));
    check(deepEqual(onDisk, res), 'result.json equals the returned value');
    const sum = JSON.parse(fs.readFileSync(path.join(r.runDir, 'summary.json'), 'utf8'));
    check(sum.live_agents === 3 && sum.resumed_agents === 0 && sum.null_agents === 0 && Number.isInteger(sum.duration_ms), `summary ${JSON.stringify(sum)}`);
    const meta = JSON.parse(fs.readFileSync(path.join(r.runDir, 'run.json'), 'utf8')).meta;
    check(meta && meta.phases.length === 2 && meta.phases[1].title === 'Two', 'run.json records normalized meta');
    check(r.calls.length === 3 && r.calls.every((c) => c.cwd === repo), 'agents spawned with --cwd <cwd>');
  });

  record('module-form: import from "claude", run(promptContext), agent({prompt,schema}), parallel over promises, string phases, relative import', () => {
    const r = run('module.js', ['--args', 'ship it']);
    ok(r);
    const res = r.json.result;
    check(deepEqual(res.built, ['built-x', 'built-y', 'built-z']), `built ${JSON.stringify(res.built)}`);
    check(res.tagged === 'tagged-done' && res.ctx === 'ship it' && res.pipelineType === 'function', `result ${JSON.stringify(res)}`);
    const meta = JSON.parse(fs.readFileSync(path.join(r.runDir, 'run.json'), 'utf8')).meta;
    check(deepEqual(meta.phases, [{ title: 'discover', detail: null }, { title: 'build', detail: null }]), 'string phases normalized');
  });

  record('parallel over thunks + pipeline stage semantics', () => {
    const r = run('flow.js');
    ok(r);
    const res = r.json.result;
    check(deepEqual(res.par, ['one', null, null, 7]), `parallel ${JSON.stringify(res.par)}`);
    check(deepEqual(res.pipe, ['S1-a+a0', null, 'S1-c+c2']), `pipeline ${JSON.stringify(res.pipe)}`);
    check(deepEqual(res.seen, ['s1:a:a:0', 's1:b:b:1', 's1:c:c:2']), `stage args ${JSON.stringify(res.seen)}`);
  });

  record('meta must be a pure literal (typed error, zero spawns)', () => {
    for (const f of ['meta-var.js', 'meta-call.js']) {
      const r = run(f);
      check(r.code === 1 && r.json && r.json.error && r.json.error.code === 'META_NOT_LITERAL', `${f}: ${JSON.stringify(r.json)}`);
      check(r.calls.length === 0, `${f}: spawned ${r.calls.length}`);
    }
  });

  record('schema pre-flight: contradiction halts with typed error before any spawn', () => {
    for (const f of ['preflight-required.js', 'preflight-type.js', 'preflight-root.js']) {
      const r = run(f);
      check(r.code === 1 && r.json && r.json.error && r.json.error.code === 'SCHEMA_PREFLIGHT', `${f}: ${JSON.stringify(r.json)}`);
      check(r.calls.length === 0, `${f}: ${r.calls.length} spawns before halt`);
    }
  });

  record('structured output: parse order, re-ask on the same session, fresh re-ask, exhaustion -> null', () => {
    const r = run('reask.js', [], { MAX_STRUCTURED_OUTPUT_RETRIES: '2' });
    ok(r);
    const res = r.json.result;
    check(deepEqual(res, { fenced: { v: 4 }, braces: { v: 5 }, reask: { v: 6 }, fresh: { v: 7 }, never: null }), `result ${JSON.stringify(res)}`);
    const by = (s) => r.calls.filter((c) => c.scenario === s);
    const rk = by('reask');
    check(rk.length === 3 && rk[0].resume === null && rk[1].resume === rk[0].sessionId && rk[2].resume === rk[0].sessionId && rk[1].reask, 're-ask resumes the zcode session with validator errors');
    const fr = by('fresh');
    check(fr.length === 2 && fr[1].resume === null && fr[1].reask, 'no sessionId -> fresh re-ask carrying the errors');
    check(by('never').length === 3, `MAX_STRUCTURED_OUTPUT_RETRIES=2 -> 3 attempts, got ${by('never').length}`);
    const sum = JSON.parse(fs.readFileSync(path.join(r.runDir, 'summary.json'), 'utf8'));
    check(sum.null_agents === 1, `null_agents ${sum.null_agents}`);
    check(!r.journal.some((l) => l.type === 'result' && l.result === null), 'null results are not journaled (they re-run on resume)');
  });

  record('rate limit (exit 75 / 429 / 1302) backs off and retries; unrecoverable -> null', () => {
    const r = run('ratelimit.js');
    ok(r);
    check(deepEqual(r.json.result, { limited: 'recovered', dead: null }), `result ${JSON.stringify(r.json.result)}`);
    check(r.calls.filter((c) => c.scenario === 'ratelimit').length === 3, 'ratelimit: 3 attempts');
    check(r.calls.filter((c) => c.scenario === 'dead').length === 1, 'dead: no retry');
    check(r.json.summary.null_agents === 1, 'null_agents 1');
  });

  record("isolation 'worktree': fresh worktree per agent, kept when changed, removed when clean", () => {
    const r = run('worktree.js');
    ok(r);
    const { changed, clean } = r.json.result;
    check(changed.cwd !== repo && clean.cwd !== repo && changed.cwd !== clean.cwd, 'agents ran in their own worktrees');
    check(fs.existsSync(path.join(changed.cwd, 'made-by-agent.txt')), 'changed worktree kept with the agent file');
    check(!fs.existsSync(clean.cwd), 'clean worktree removed');
    const list = g('worktree', 'list', '--porcelain');
    check(list.includes(changed.cwd) && !list.includes(clean.cwd), 'git worktree list agrees');
    check(r.journal.some((l) => l.type === 'log' && l.msg.startsWith('worktree kept: ' + changed.cwd)), 'kept worktree logged in journal');
    check(!fs.existsSync(path.join(repo, 'made-by-agent.txt')), 'main checkout untouched');
  });

  record('concurrency cap: --concurrency and ULTRACODE_CONCURRENCY bound live spawns', () => {
    const r = run('concurrency.js', ['--concurrency', '2']);
    ok(r);
    check(deepEqual(r.json.result, ['slept', 'slept', 'slept', 'slept', 'slept', 'slept']), 'six results');
    check(maxOverlap(r.calls) === 2, `--concurrency 2 -> max overlap ${maxOverlap(r.calls)}`);
    const r2 = run('concurrency.js', [], { ULTRACODE_CONCURRENCY: '3' });
    ok(r2);
    check(maxOverlap(r2.calls) === 3, `ULTRACODE_CONCURRENCY=3 -> max overlap ${maxOverlap(r2.calls)}`);
  });

  record('agent cap halts the run with a typed error (ULTRACODE_MAX_AGENTS, default 1000)', () => {
    const r = run('cap.js', [], { ULTRACODE_MAX_AGENTS: '3' });
    check(r.code === 1 && r.json && r.json.error && r.json.error.code === 'AGENT_CAP_EXCEEDED', JSON.stringify(r.json));
    check(r.calls.length === 3, `spawned ${r.calls.length}, cap 3`);
  });

  record('workflow(): {scriptPath}, project name, ULTRACODE_CLAUDE_HOME name, one level deep, --args @file', () => {
    const argsFile = path.join(root, 'parent-args.json');
    fs.writeFileSync(argsFile, JSON.stringify({ child: path.join(fx, 'child.js') }));
    const r = run('parent.js', ['--args', '@' + argsFile]);
    ok(r);
    const res = r.json.result;
    check(deepEqual(res.byPath, { v: 'from-child', n: 2, nested: 'WORKFLOW_DEPTH' }), `byPath ${JSON.stringify(res.byPath)}`);
    check(res.byName.n === 3 && res.byHome.n === 4 && res.byHome.nested === 'WORKFLOW_DEPTH', `byName/byHome ${JSON.stringify([res.byName, res.byHome])}`);
    check(res.budgetTotal === null && res.remaining === true, 'budget');
    check(['child:2', 'child:3', 'child:4'].every((l) => r.journal.some((x) => x.type === 'started' && x.label === l)), 'child agents journaled in the parent run');
  });

  record('resume from a ZCode run dir: own-key match, never re-spawned, chainable', () => {
    const first = run('resume-key.js');
    ok(first);
    check(first.calls.length === 2, 'first run spawns 2');
    const second = run('resume-key.js', ['--resume-from', first.runDir], { ULTRACODE_SCRIPTED_STATE: first.state });
    ok(second);
    check(deepEqual(second.json.result, ['K1', { k: 2 }]), `resumed result ${JSON.stringify(second.json.result)}`);
    check(second.json.summary.live_agents === 0 && second.json.summary.resumed_agents === 2, `summary ${JSON.stringify(second.json.summary)}`);
    check(readJsonl(path.join(first.state, 'calls.jsonl')).length === 2, 'no re-spawn');
    const dry = cli(['run', path.join(fx, 'resume-key.js'), '--resume-from', second.runDir, '--dry-run', '--json'], { ULTRACODE_SCRIPTED_STATE: first.state });
    check(dry.code === 0 && dry.json && dry.json.live_agents_needed === 0 && dry.json.resumed === 2 && dry.json.completed === true, `dry-run over resumed run ${JSON.stringify(dry.json)}`);
  });

  // A Claude-shaped transcript dir: v2 keys, a duplicated label, a label only in
  // agent-<id>.meta.json, and one started agent without a result.
  const claudeDir = path.join(claudeHomeDir, 'projects', 'p', 's', 'subagents', 'workflows', 'wf_selftest');
  fs.mkdirSync(claudeDir, { recursive: true });
  const k = (s) => 'v2:' + sha256(s);
  const claudeLines = [
    { type: 'launched' },
    { type: 'started', key: k('s'), agentId: 'a1', label: 'survey:x', phase: 'Survey' },
    { type: 'started', key: k('d1'), agentId: 'a2', label: 'dup', phase: 'Survey' },
    { type: 'started', key: k('d2'), agentId: 'a3', label: 'dup', phase: 'Survey' },
    { type: 'result', key: k('d2'), agentId: 'a3', result: 'dup-second' },
    { type: 'result', key: k('s'), agentId: 'a1', result: { ok: true } },
    { type: 'result', key: k('d1'), agentId: 'a2', result: 'dup-first' },
    { type: 'started', key: k('m'), agentId: 'a4', phase: 'Survey' },
    { type: 'result', key: k('m'), agentId: 'a4', result: 'from-meta' },
    { type: 'started', key: k('u'), agentId: 'a5', label: 'unfinished', phase: 'Survey' },
  ];
  fs.writeFileSync(path.join(claudeDir, 'journal.jsonl'), claudeLines.map((l) => JSON.stringify(l)).join('\n') + '\n');
  fs.writeFileSync(path.join(claudeDir, 'agent-a4.meta.json'), JSON.stringify({ agentType: 'Explore', description: 'meta-labelled', workflowPhase: 'Survey' }));

  record('dry-run against a Claude transcript: counts live agents needed, zero spawns', () => {
    const d = cli(['run', path.join(fx, 'resume-label.js'), '--resume-from', claudeDir, '--dry-run', '--json']);
    check(d.code === 0 && d.json && d.json.live_agents_needed === 1 && d.json.resumed === 4 && d.json.completed === false, JSON.stringify(d.json));
    check(d.calls.length === 0, 'dry-run spawned');
    const doneDir = path.join(root, 'claude-complete');
    fs.mkdirSync(doneDir, { recursive: true });
    fs.copyFileSync(path.join(claudeDir, 'agent-a4.meta.json'), path.join(doneDir, 'agent-a4.meta.json'));
    fs.writeFileSync(path.join(doneDir, 'journal.jsonl'), [...claudeLines, { type: 'result', key: k('u'), agentId: 'a5', result: 'done-by-claude' }].map((l) => JSON.stringify(l)).join('\n') + '\n');
    const d2 = cli(['run', path.join(fx, 'resume-label.js'), '--resume-from', doneDir, '--dry-run', '--json']);
    check(d2.code === 0 && d2.json && d2.json.live_agents_needed === 0 && d2.json.resumed === 5 && d2.json.completed === true, JSON.stringify(d2.json));
  });

  record('resume from a Claude transcript: nth-label matching, meta.json label fallback, only unfinished agents run live', () => {
    const r = run('resume-label.js', ['--resume-from', claudeDir]);
    ok(r);
    check(deepEqual(r.json.result, { s: { ok: true }, d: ['dup-first', 'dup-second'], m: 'from-meta', u: 'finished-live' }), `result ${JSON.stringify(r.json.result)}`);
    check(r.calls.length === 1 && r.calls[0].scenario === 'unfinished', `spawns ${JSON.stringify(r.calls.map((c) => c.scenario))}`);
    check(r.json.summary.live_agents === 1 && r.json.summary.resumed_agents === 4, `summary ${JSON.stringify(r.json.summary)}`);
    const resumedLines = r.journal.filter((l) => l.type === 'started' && l.resumed);
    check(resumedLines.length === 4 && resumedLines.every((l) => /^zc1:/.test(l.key)), 'resumed agents re-journaled under zc1 keys');
    const dup = r.journal.filter((l) => l.type === 'started' && l.label === 'dup');
    check(dup.map((l) => l.n).join(',') === '0,1' && dup[0].agentId === 'a2', 'nth mapping recorded (n, original agentId)');
  });

  record('real ~/.claude and ~/.zcode untouched: runs land under ULTRACODE_HOME', () => {
    const r = cli(['run', path.join(fx, 'resume-key.js'), '--json']);
    ok(r);
    check(r.json.runDir.startsWith(path.join(zhome, 'runs') + path.sep), `default run dir ${r.json.runDir}`);
  });

  const failed = results.filter(([, e]) => e);
  process.stdout.write(`selftest: ${results.length - failed.length} passed, ${failed.length} failed\n`);
  if (failed.length) process.stdout.write(`selftest tmp kept for inspection: ${root}\n`);
  else fs.rmSync(root, { recursive: true, force: true });
  return failed.length ? 1 : 0;
}

// ---------------------------------------------------------------------------

async function main(argv) {
  const major = Number(process.versions.node.split('.')[0]);
  if (major < 22) {
    process.stderr.write(`ultracode-run: node >= 22 required (have ${process.versions.node})\n`);
    return 2;
  }
  const [cmd, ...rest] = argv;
  try {
    if (cmd === 'run') return await cmdRun(rest);
    if (cmd === 'selftest') return await cmdSelftest();
    process.stdout.write(USAGE + '\n');
    return cmd === undefined || cmd === 'help' || cmd === '--help' ? 0 : 2;
  } catch (e) {
    const info = errInfo(e);
    process.stderr.write(`ultracode-run: ${info.code}: ${info.message}\n`);
    if (rest.includes('--json')) process.stdout.write(JSON.stringify({ error: info }) + '\n');
    return info.code === 'USAGE' ? 2 : 1;
  }
}

process.exitCode = await main(process.argv.slice(2));

