#!/usr/bin/env node
// ultracode-watch.mjs -- stall detector and takeover driver for Claude Code
// Workflow ("ultracode") runs. Spec: skills/ultracode-takeover/SKILL.md.
//
// GENERATED by `cd priv/zcode_plugin && ggen sync run` from
// templates/script-ultracode-watch.mjs.tmpl. Edit the template, never this file.
// The body is irreducible handwritten residue (HANDWRITTEN.md:
// UNSUPPORTED(generator-capability): workflow runtime logic).
//
// Subcommands
//   scan [--json]                  classify every open handoff record: runId, eligible, reason
//   takeover <runId>               O_EXCL lock, then resume the run under ZCode via the runtime
//   run-once [--auto]              scan; with --auto take over every eligible run, serially
//   print | install | uninstall | status
//                                  launchd agent dev.zcode.ultracode-watch (StartInterval 300)
//   selftest                       real-process qualification in a tmp claude/ultracode home
//
// Eligibility (per open record, status not completed/taken_over):
//   session dead  AND stale >= ULTRACODE_DEAD_GRACE_MIN (default 2), or
//   session alive AND stale >= ULTRACODE_STALE_MINUTES (default 45) AND the last 200 lines
//   of the session transcript carry an API-failure marker;
//   then `ultracode-run.mjs run --dry-run --resume-from` must report live_agents_needed > 0
//   (0 => the run is already complete: record marked completed, result.json written).
//   Liveness = <claudeHome>/sessions/<pid>.json with the record's sessionId, kill -0 pid,
//   and `ps -o lstart= -p pid` == procStart (guards pid reuse).
//   Staleness = minutes since the newest mtime of journal.jsonl / agent-*.jsonl.
//
// Environment
//   ULTRACODE_CLAUDE_HOME (default ~/.claude)    ULTRACODE_HOME (default ~/.zcode/ultracode)
//   ULTRACODE_RUNTIME (default: sibling ultracode-run.mjs)
//   ULTRACODE_STALE_MINUTES (45)  ULTRACODE_DEAD_GRACE_MIN (2)
//   ULTRACODE_DRYRUN_TIMEOUT_MS (120000)  ULTRACODE_LAUNCH_AGENTS_DIR (~/Library/LaunchAgents)
//
// Node >= 22, node: builtins only. Exit codes: 0 ok, 1 failure, 2 typed refusal, 64 usage.
import fs from "node:fs";
import path from "node:path";
import os from "node:os";
import { spawn, spawnSync } from "node:child_process";
import { fileURLToPath, pathToFileURL } from "node:url";
import { createHash } from "node:crypto";

const SELF = fileURLToPath(import.meta.url);
const HERE = path.dirname(SELF);
export const LABEL = "dev.zcode.ultracode-watch";
export const START_INTERVAL = 300;
const CLOSED = new Set(["completed", "taken_over"]);
const TAIL_LINES = 200;
const TAIL_BYTES = 8 * 1024 * 1024;
// rate_limit|overloaded|usage limit|api_error, and 529/503 only as an HTTP/API status
// (bare digits also occur in durations, timestamps and ids).
export const API_FAILURE =
  /rate_limit|overloaded|usage limit|api_error|(?:error|status|code|http)\W{0,4}(?:529|503)\b/i;

// ---------------------------------------------------------------------------
// configuration and small helpers
// ---------------------------------------------------------------------------

export function config(env = process.env) {
  const home = os.homedir();
  const num = (v, d) => {
    if (v === undefined || v === "") return d;
    const n = Number(v);
    return Number.isFinite(n) && n >= 0 ? n : d;
  };
  return {
    env,
    claudeHome: path.resolve(env.ULTRACODE_CLAUDE_HOME || path.join(home, ".claude")),
    ultracodeHome: path.resolve(env.ULTRACODE_HOME || path.join(home, ".zcode", "ultracode")),
    runtime: path.resolve(env.ULTRACODE_RUNTIME || path.join(HERE, "ultracode-run.mjs")),
    staleMinutes: num(env.ULTRACODE_STALE_MINUTES, 45),
    deadGraceMin: num(env.ULTRACODE_DEAD_GRACE_MIN, 2),
    dryRunTimeoutMs: num(env.ULTRACODE_DRYRUN_TIMEOUT_MS, 120000),
    launchAgentsDir: path.resolve(
      env.ULTRACODE_LAUNCH_AGENTS_DIR || path.join(home, "Library", "LaunchAgents")
    ),
  };
}

const handoffDir = (c) => path.join(c.claudeHome, "workflow-handoff");
const recordPath = (c, runId) => path.join(handoffDir(c), `${runId}.json`);
export const lockPath = (c, runId) => path.join(handoffDir(c), `${runId}.takeover`);
const runDirOf = (c, runId) => path.join(c.ultracodeHome, "runs", runId);
const workDirOf = (c, runId) => path.join(c.ultracodeHome, "takeovers", runId);
const iso = (t = Date.now()) => new Date(t).toISOString();
const round1 = (x) => (Number.isFinite(x) ? Math.round(x * 10) / 10 : null);
const RUN_ID = /^[A-Za-z0-9_.:-]+$/;

function readJson(p) {
  try {
    return JSON.parse(fs.readFileSync(p, "utf8"));
  } catch {
    return undefined;
  }
}
function isDir(p) {
  try {
    return fs.statSync(p).isDirectory();
  } catch {
    return false;
  }
}
function isFile(p) {
  try {
    return fs.statSync(p).isFile();
  } catch {
    return false;
  }
}
function sortKeys(o) {
  return Object.fromEntries(Object.keys(o).sort().map((k) => [k, o[k]]));
}
function writeJsonAtomic(p, obj) {
  fs.mkdirSync(path.dirname(p), { recursive: true });
  const tmp = `${p}.${process.pid}.${Date.now()}.tmp`;
  fs.writeFileSync(tmp, JSON.stringify(obj, null, 1) + "\n");
  fs.renameSync(tmp, p);
}
function updateRecord(c, runId, patch) {
  const p = recordPath(c, runId);
  const next = sortKeys({ ...(readJson(p) ?? { runId }), ...patch });
  writeJsonAtomic(p, next);
  return next;
}
const lastLine = (s) =>
  String(s ?? "")
    .trim()
    .split("\n")
    .pop()
    .slice(0, 300);

// ---------------------------------------------------------------------------
// liveness: sessions/<pid>.json + kill -0 + ps lstart == procStart
// ---------------------------------------------------------------------------

function pidAlive(pid) {
  try {
    process.kill(pid, 0);
    return true;
  } catch (e) {
    return e.code === "EPERM";
  }
}
const norm = (s) => String(s ?? "").trim().replace(/\s+/g, " ");

function lstart(pid, tz) {
  const env = { ...process.env, LC_ALL: "C" };
  if (tz) env.TZ = tz;
  const ps = isFile("/bin/ps") ? "/bin/ps" : "ps";
  const r = spawnSync(ps, ["-o", "lstart=", "-p", String(pid)], { env, encoding: "utf8" });
  return r.status === 0 ? norm(r.stdout) : "";
}

// true/false, or null when the session file carries no procStart (pid reuse unguarded).
// Claude writes procStart in UTC; the local-zone rendering is accepted as well.
export function procStartMatches(pid, procStart) {
  const want = norm(procStart);
  if (!want) return null;
  return lstart(pid, "UTC") === want || lstart(pid, undefined) === want;
}

export function sessionLiveness(c, sessionId) {
  if (!sessionId) return { alive: false, pid: null, why: "no-sessionId" };
  const dir = path.join(c.claudeHome, "sessions");
  let names = [];
  try {
    names = fs.readdirSync(dir).filter((n) => /^\d+\.json$/.test(n));
  } catch {}
  const seen = [];
  for (const n of names.sort()) {
    const s = readJson(path.join(dir, n));
    if (!s || s.sessionId !== sessionId) continue;
    const pid = Number(s.pid ?? n.slice(0, -5));
    if (!Number.isInteger(pid) || pid <= 0) continue;
    if (!pidAlive(pid)) {
      seen.push({ pid, why: "pid-dead" });
      continue;
    }
    const m = procStartMatches(pid, s.procStart);
    if (m === false) {
      seen.push({ pid, why: "pid-reused" });
      continue;
    }
    // an unguarded live pid counts as alive: the conservative side for a takeover
    return { alive: true, pid, why: m === null ? "alive(procStart-absent)" : "alive" };
  }
  if (!seen.length) return { alive: false, pid: null, why: "no-session-file" };
  return { alive: false, pid: seen[0].pid, why: seen.map((s) => `${s.pid}:${s.why}`).join(",") };
}

// ---------------------------------------------------------------------------
// staleness and the API-failure marker
// ---------------------------------------------------------------------------

export function staleness(c, rec, now = Date.now()) {
  let newest = 0;
  let source = null;
  const dir = rec.transcriptDir;
  if (dir && isDir(dir)) {
    for (const n of fs.readdirSync(dir)) {
      if (n !== "journal.jsonl" && !/^agent-.*\.jsonl$/.test(n)) continue;
      try {
        const t = fs.statSync(path.join(dir, n)).mtimeMs;
        if (t > newest) [newest, source] = [t, n];
      } catch {}
    }
  }
  if (!newest) {
    const t = Date.parse(rec.launchedAt ?? "");
    if (Number.isFinite(t)) [newest, source] = [t, "launchedAt"];
  }
  if (!newest) {
    try {
      [newest, source] = [fs.statSync(recordPath(c, rec.runId)).mtimeMs, "record-mtime"];
    } catch {}
  }
  return { minutes: newest ? Math.max(0, (now - newest) / 60000) : Infinity, source };
}

function tailLines(file, n = TAIL_LINES) {
  const fd = fs.openSync(file, "r");
  try {
    const size = fs.fstatSync(fd).size;
    const start = Math.max(0, size - TAIL_BYTES);
    const buf = Buffer.alloc(size - start);
    fs.readSync(fd, buf, 0, buf.length, start);
    let lines = buf.toString("utf8").split("\n");
    if (start > 0) lines = lines.slice(1);
    return lines.filter((l) => l.length).slice(-n);
  } finally {
    fs.closeSync(fd);
  }
}

export function sessionTranscriptPath(c, sessionId) {
  const root = path.join(c.claudeHome, "projects");
  let best = null;
  let dirs = [];
  try {
    dirs = fs.readdirSync(root);
  } catch {}
  for (const d of dirs) {
    const p = path.join(root, d, `${sessionId}.jsonl`);
    try {
      const st = fs.statSync(p);
      if (st.isFile() && (!best || st.mtimeMs > best.mtimeMs)) best = { p, mtimeMs: st.mtimeMs };
    } catch {}
  }
  return best?.p ?? null;
}

export function apiFailureMarker(c, sessionId) {
  if (!sessionId) return null;
  const t = sessionTranscriptPath(c, sessionId);
  if (!t) return null;
  for (const line of tailLines(t).reverse()) {
    const m = API_FAILURE.exec(line);
    if (m) return m[0];
  }
  return null;
}

// ---------------------------------------------------------------------------
// runtime contract: node ultracode-run.mjs run <script> [--args @file] [--resume-from dir]
//                   [--run-dir dir] [--cwd dir] [--dry-run] [--json]
// ---------------------------------------------------------------------------

export function handoffArgs(rec) {
  if (rec.args === null || rec.args === undefined) {
    if (rec.argsNote) return { refused: "ARGS_UNAVAILABLE", detail: String(rec.argsNote) };
    return { value: undefined };
  }
  return { value: rec.args };
}

function runtimeArgv(c, rec, extra) {
  const argv = [c.runtime, "run", rec.scriptFile];
  const a = handoffArgs(rec);
  if (a.value !== undefined) {
    const f = path.join(workDirOf(c, rec.runId), "args.json");
    fs.mkdirSync(path.dirname(f), { recursive: true });
    fs.writeFileSync(f, JSON.stringify(a.value) + "\n");
    argv.push("--args", `@${f}`);
  }
  if (rec.transcriptDir && isDir(rec.transcriptDir)) argv.push("--resume-from", rec.transcriptDir);
  if (rec.cwd && isDir(rec.cwd)) argv.push("--cwd", rec.cwd);
  argv.push(...extra);
  return argv;
}

export function parseLiveAgents(stdout) {
  const text = String(stdout ?? "").trim();
  const pick = (o) =>
    o && typeof o === "object" ? o.live_agents_needed ?? o.liveAgentsNeeded : undefined;
  const tryParse = (s) => {
    try {
      return JSON.parse(s);
    } catch {
      return undefined;
    }
  };
  let obj = tryParse(text);
  if (pick(obj) === undefined) {
    obj = undefined;
    for (const line of text.split("\n").reverse()) {
      const o = tryParse(line.trim());
      if (pick(o) !== undefined) {
        obj = o;
        break;
      }
    }
  }
  if (obj && Number.isFinite(Number(pick(obj)))) return { n: Number(pick(obj)), report: obj };
  const m = /live_agents_needed["']?\s*[:=]\s*(\d+)/.exec(text);
  return m ? { n: Number(m[1]), report: null } : null;
}

function dryRun(c, rec) {
  const argv = runtimeArgv(c, rec, ["--dry-run", "--json"]);
  const r = spawnSync(process.execPath, argv, {
    env: c.env,
    encoding: "utf8",
    timeout: c.dryRunTimeoutMs,
    maxBuffer: 64 << 20,
  });
  return {
    exit: r.status,
    signal: r.signal,
    parsed: parseLiveAgents(r.stdout),
    diag: lastLine(r.stderr || r.error?.message || r.stdout),
  };
}

// ---------------------------------------------------------------------------
// scan
// ---------------------------------------------------------------------------

export function classify(c, rec, { now = Date.now() } = {}) {
  const out = {
    runId: rec.runId,
    status: rec.status ?? "launched",
    eligible: false,
    candidate: false,
    reason: "",
  };
  const live = sessionLiveness(c, rec.sessionId);
  const st = staleness(c, rec, now);
  const m = round1(st.minutes);
  Object.assign(out, { session: live, staleMinutes: m, staleSource: st.source });
  const lp = lockPath(c, rec.runId);
  if (fs.existsSync(lp)) {
    out.reason = `LOCKED(${JSON.stringify(readJson(lp) ?? lp)})`;
    return out;
  }
  if (!live.alive) {
    if (st.minutes < c.deadGraceMin) {
      out.reason = `SESSION_DEAD_BUT_FRESH(${live.why}; stale ${m}m < ${c.deadGraceMin}m)`;
      return out;
    }
    out.candidate = true;
    out.reason = `SESSION_DEAD(${live.why}; stale ${m}m >= ${c.deadGraceMin}m)`;
  } else {
    if (st.minutes < c.staleMinutes) {
      out.reason = `SESSION_ALIVE_PROGRESSING(stale ${m}m < ${c.staleMinutes}m)`;
      return out;
    }
    const marker = apiFailureMarker(c, rec.sessionId);
    out.apiFailureMarker = marker;
    if (!marker) {
      out.reason = `SESSION_ALIVE_STALE_NO_API_FAILURE(stale ${m}m)`;
      return out;
    }
    out.candidate = true;
    out.reason = `SESSION_ALIVE_API_FAILURE(${marker}; stale ${m}m >= ${c.staleMinutes}m)`;
  }
  const a = handoffArgs(rec);
  if (a.refused) {
    out.reason = `REFUSED(ARGS_UNAVAILABLE: ${a.detail}); ${out.reason}`;
    return out;
  }
  if (!rec.scriptFile || !isFile(rec.scriptFile)) {
    out.reason = `REFUSED(SCRIPT_MISSING: ${rec.scriptFile ?? "null"}); ${out.reason}`;
    return out;
  }
  if (!isFile(c.runtime)) {
    out.reason = `RUNTIME_ABSENT(${c.runtime}); ${out.reason}`;
    return out;
  }
  const dr = dryRun(c, rec);
  if (!dr.parsed) {
    out.reason = `DRY_RUN_FAILED(exit ${dr.exit}${dr.signal ? ` ${dr.signal}` : ""}: ${dr.diag}); ${out.reason}`;
    return out;
  }
  out.liveAgentsNeeded = dr.parsed.n;
  if (dr.parsed.n > 0) {
    out.eligible = true;
    out.reason = `${out.reason}; live_agents_needed=${dr.parsed.n}`;
    return out;
  }
  // replay reaches `return` with zero live agents: the run is already complete
  const resultFile = path.join(runDirOf(c, rec.runId), "result.json");
  writeJsonAtomic(resultFile, {
    runId: rec.runId,
    completedBy: "ultracode-watch",
    source: "claude-journal-replay",
    at: iso(now),
    result: dr.parsed.report?.result ?? null,
    dryRun: dr.parsed.report,
  });
  updateRecord(c, rec.runId, {
    status: "completed",
    completedAt: iso(now),
    completedBy: "ultracode-watch",
    resultFile,
  });
  out.status = "completed";
  out.reason = `COMPLETED(live_agents_needed=0 -> ${resultFile})`;
  return out;
}

export function scan(c, opts = {}) {
  let names = [];
  try {
    names = fs
      .readdirSync(handoffDir(c))
      .filter((n) => n.endsWith(".json") && !n.startsWith("_") && !n.startsWith("."))
      .sort();
  } catch {}
  const rows = [];
  for (const n of names) {
    const rec = readJson(path.join(handoffDir(c), n));
    const runId = (rec && typeof rec === "object" && rec.runId) || n.slice(0, -5);
    if (!rec || typeof rec !== "object" || !RUN_ID.test(runId)) {
      rows.push({ runId, eligible: false, candidate: false, reason: "RECORD_UNPARSEABLE" });
      continue;
    }
    if (CLOSED.has(rec.status)) continue;
    try {
      rows.push(classify(c, { ...rec, runId }, opts));
    } catch (e) {
      rows.push({ runId, eligible: false, candidate: false, reason: `SCAN_ERROR(${e.message})` });
    }
  }
  return rows;
}

// ---------------------------------------------------------------------------
// takeover
// ---------------------------------------------------------------------------

export function acquireLock(c, runId, now = Date.now()) {
  const p = lockPath(c, runId);
  fs.mkdirSync(path.dirname(p), { recursive: true });
  const body = { owner: "zcode", pid: process.pid, at: iso(now), host: os.hostname() };
  let fd;
  try {
    fd = fs.openSync(p, "wx", 0o644); // O_CREAT|O_EXCL: exactly one creator wins
  } catch (e) {
    if (e.code === "EEXIST") return { acquired: false, path: p, holder: readJson(p) ?? null };
    throw e;
  }
  try {
    fs.writeSync(fd, JSON.stringify(body) + "\n");
    fs.fsyncSync(fd);
  } finally {
    fs.closeSync(fd);
  }
  return { acquired: true, path: p, holder: body };
}

function spawnCollect(cmd, argv, env) {
  return new Promise((resolve) => {
    const child = spawn(cmd, argv, { env, stdio: ["ignore", "pipe", "inherit"] });
    const chunks = [];
    child.stdout.on("data", (d) => chunks.push(d));
    child.on("error", (e) => resolve({ code: 127, signal: null, stdout: String(e.message) }));
    child.on("close", (code, signal) =>
      resolve({ code: code ?? 128, signal, stdout: Buffer.concat(chunks).toString("utf8") })
    );
  });
}

export async function takeover(c, runId) {
  const refuse = (code, detail) => ({
    runId,
    outcome: "REFUSED",
    code,
    reason: `REFUSED(${code})`,
    detail: detail ?? null,
  });
  if (!runId || !RUN_ID.test(runId)) return refuse("BAD_RUN_ID", runId ?? null);
  const rec0 = readJson(recordPath(c, runId));
  if (!rec0 || typeof rec0 !== "object") return refuse("NO_RECORD", recordPath(c, runId));
  const rec = { ...rec0, runId };
  const lp = lockPath(c, runId);
  if (fs.existsSync(lp)) return refuse("LOCKED", readJson(lp) ?? lp);
  if (CLOSED.has(rec.status)) return refuse(`ALREADY_${rec.status.toUpperCase()}`, rec.resultFile);
  const a = handoffArgs(rec);
  if (a.refused) return refuse("ARGS_UNAVAILABLE", a.detail);
  if (!rec.scriptFile || !isFile(rec.scriptFile)) return refuse("SCRIPT_MISSING", rec.scriptFile);
  if (!isFile(c.runtime)) return refuse("RUNTIME_ABSENT", c.runtime);
  const lock = acquireLock(c, runId);
  if (!lock.acquired) return refuse("LOCKED", lock.holder ?? lock.path);

  const runDir = runDirOf(c, runId);
  const work = workDirOf(c, runId);
  fs.mkdirSync(path.dirname(runDir), { recursive: true });
  fs.mkdirSync(work, { recursive: true });
  const info = {
    owner: "zcode",
    pid: process.pid,
    at: iso(),
    runDir,
    lock: lp,
    session: sessionLiveness(c, rec.sessionId),
  };
  updateRecord(c, runId, { status: "taken_over", owner: "zcode", takeover: info });
  const argv = runtimeArgv(c, rec, ["--run-dir", runDir, "--json"]);
  fs.writeFileSync(
    path.join(work, "argv.json"),
    JSON.stringify([process.execPath, ...argv], null, 1) + "\n"
  );
  const res = await spawnCollect(process.execPath, argv, c.env);
  fs.writeFileSync(path.join(work, "runtime.stdout"), res.stdout);
  const resultFile = path.join(runDir, "result.json");
  const hasResult = isFile(resultFile);
  const done = { ...info, exit: res.code, signal: res.signal ?? null, finishedAt: iso() };
  const ok = res.code === 0;
  updateRecord(
    c,
    runId,
    ok
      ? {
          status: "completed",
          completedAt: done.finishedAt,
          completedBy: "zcode",
          resultFile: hasResult ? resultFile : null,
          takeover: done,
        }
      : { takeover: done }
  );
  return {
    runId,
    outcome: ok ? "completed" : "failed",
    exit: res.code,
    runDir,
    resultFile: hasResult ? resultFile : null,
    lock: lp,
    stdout: path.join(work, "runtime.stdout"),
  };
}

export async function runOnce(c, auto) {
  const scanned = scan(c);
  const actions = [];
  for (const r of scanned) {
    if (!r.eligible) continue;
    actions.push(auto ? await takeover(c, r.runId) : { runId: r.runId, action: "would-take-over" });
  }
  return { at: iso(), auto: !!auto, claudeHome: c.claudeHome, scanned, actions };
}

// ---------------------------------------------------------------------------
// launchd
// ---------------------------------------------------------------------------

const xml = (s) =>
  String(s)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");

function launchPath(c) {
  const dirs = [path.dirname(process.execPath)];
  for (const d of String(c.env.PATH ?? "").split(":")) {
    if (d && isFile(path.join(d, "zcode"))) {
      dirs.push(d);
      break;
    }
  }
  dirs.push(
    "/opt/homebrew/bin",
    "/usr/local/bin",
    path.join(os.homedir(), ".local", "bin"),
    "/usr/bin",
    "/bin",
    "/usr/sbin",
    "/sbin"
  );
  return [...new Set(dirs)].join(":");
}

export function plist(c) {
  const bin = path.join(c.ultracodeHome, "bin");
  const logs = path.join(c.ultracodeHome, "logs");
  const env = {
    PATH: launchPath(c),
    ULTRACODE_CLAUDE_HOME: c.claudeHome,
    ULTRACODE_HOME: c.ultracodeHome,
  };
  for (const k of ["ULTRACODE_STALE_MINUTES", "ULTRACODE_DEAD_GRACE_MIN", "ULTRACODE_CONCURRENCY"]) {
    if (c.env[k]) env[k] = c.env[k];
  }
  const s = (v) => `<string>${xml(v)}</string>`;
  const args = [process.execPath, path.join(bin, "ultracode-watch.mjs"), "run-once", "--auto"];
  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">',
    '<plist version="1.0">',
    "<dict>",
    `  <key>Label</key>${s(LABEL)}`,
    "  <key>ProgramArguments</key>",
    "  <array>",
    ...args.map((a) => `    ${s(a)}`),
    "  </array>",
    `  <key>StartInterval</key><integer>${START_INTERVAL}</integer>`,
    "  <key>RunAtLoad</key><true/>",
    `  <key>ProcessType</key>${s("Background")}`,
    `  <key>WorkingDirectory</key>${s(c.ultracodeHome)}`,
    `  <key>StandardOutPath</key>${s(path.join(logs, "ultracode-watch.out.log"))}`,
    `  <key>StandardErrorPath</key>${s(path.join(logs, "ultracode-watch.err.log"))}`,
    "  <key>EnvironmentVariables</key>",
    "  <dict>",
    ...Object.entries(env).map(([k, v]) => `    <key>${xml(k)}</key>${s(v)}`),
    "  </dict>",
    "</dict>",
    "</plist>",
    "",
  ].join("\n");
}

const plistPath = (c) => path.join(c.launchAgentsDir, `${LABEL}.plist`);
const guiDomain = () => `gui/${process.getuid()}`;

function install(c) {
  if (process.platform !== "darwin") return { code: 2, out: { refused: "UNSUPPORTED(platform)" } };
  if (!isFile(c.runtime)) return { code: 2, out: { refused: "RUNTIME_ABSENT", runtime: c.runtime } };
  const bin = path.join(c.ultracodeHome, "bin");
  fs.mkdirSync(bin, { recursive: true });
  fs.mkdirSync(path.join(c.ultracodeHome, "logs"), { recursive: true });
  fs.copyFileSync(SELF, path.join(bin, "ultracode-watch.mjs"));
  fs.copyFileSync(c.runtime, path.join(bin, "ultracode-run.mjs"));
  const p = plistPath(c);
  fs.mkdirSync(path.dirname(p), { recursive: true });
  fs.writeFileSync(p, plist(c));
  const lint = spawnSync("plutil", ["-lint", p], { encoding: "utf8" });
  if (lint.status !== 0) return { code: 1, out: { plist: p, lint: lastLine(lint.stdout || lint.stderr) } };
  spawnSync("launchctl", ["bootout", `${guiDomain()}/${LABEL}`], { encoding: "utf8" });
  const b = spawnSync("launchctl", ["bootstrap", guiDomain(), p], { encoding: "utf8" });
  return {
    code: b.status === 0 ? 0 : 1,
    out: { installed: b.status === 0, plist: p, bin, bootstrap: { exit: b.status, err: lastLine(b.stderr) } },
  };
}

function uninstall(c) {
  if (process.platform !== "darwin") return { code: 2, out: { refused: "UNSUPPORTED(platform)" } };
  const b = spawnSync("launchctl", ["bootout", `${guiDomain()}/${LABEL}`], { encoding: "utf8" });
  const p = plistPath(c);
  const had = isFile(p);
  if (had) fs.unlinkSync(p);
  return { code: 0, out: { uninstalled: true, plistRemoved: had, bootout: { exit: b.status, err: lastLine(b.stderr) } } };
}

function status(c) {
  const out = {
    label: LABEL,
    plist: plistPath(c),
    plistInstalled: isFile(plistPath(c)),
    bin: {
      watch: isFile(path.join(c.ultracodeHome, "bin", "ultracode-watch.mjs")),
      runtime: isFile(path.join(c.ultracodeHome, "bin", "ultracode-run.mjs")),
    },
    runtime: { path: c.runtime, present: isFile(c.runtime) },
    launchd: null,
    handoff: { claudeHome: c.claudeHome, byStatus: {}, locks: 0 },
  };
  if (process.platform === "darwin") {
    const r = spawnSync("launchctl", ["print", `${guiDomain()}/${LABEL}`], { encoding: "utf8" });
    out.launchd =
      r.status === 0
        ? {
            loaded: true,
            state: /\bstate = (\S+)/.exec(r.stdout)?.[1] ?? null,
            runs: Number(/\bruns = (\d+)/.exec(r.stdout)?.[1] ?? NaN),
            lastExitCode: /last exit code = (.+)/.exec(r.stdout)?.[1]?.trim() ?? null,
          }
        : { loaded: false, exit: r.status };
  }
  let names = [];
  try {
    names = fs.readdirSync(handoffDir(c));
  } catch {}
  for (const n of names) {
    if (n.endsWith(".takeover")) out.handoff.locks++;
    if (!n.endsWith(".json") || n.startsWith("_")) continue;
    const st = readJson(path.join(handoffDir(c), n))?.status ?? "unparseable";
    out.handoff.byStatus[st] = (out.handoff.byStatus[st] ?? 0) + 1;
  }
  return out;
}

// ---------------------------------------------------------------------------
// selftest -- Chicago-style qualification, real collaborators only.
//
// Everything exercised is real: child processes (`sleep` as the Claude session
// whose liveness is probed and then killed; this very script run as a CLI
// subprocess for every scan/takeover/run-once/print case; 8 racing node
// processes importing this module for the O_EXCL lock), real files in a fresh
// mkdtemp claude home and ultracode home per case, a real tmp git repo as the run
// cwd, real `ps`, real `plutil`, and the real runtime (ULTRACODE_RUNTIME, default
// the sibling ultracode-run.mjs). The real ~/.claude and ~/.zcode are never read or
// written: every child gets ULTRACODE_CLAUDE_HOME / ULTRACODE_HOME inside the tmp
// root. `install` is never called.
//
// The ONE test double is the scripted agent backend: a real executable selected by
// ULTRACODE_AGENT_CMD that answers `--prompt ... --json` with the same JSON shape as
// `zcode --prompt --json` ({sessionId, traceId, response}). Justification: a live
// model is nondeterministic (answer text varies run to run, so replay/resume results
// could not be asserted exactly), spends paid tokens, and needs network and
// credentials. The scripted backend pins that nondeterminism; every other
// collaborator stays real. No module of this codebase is mocked.
//
// Cases that need the runtime print `SKIP <name>: <reason>` when it is absent; the
// integration stage reruns them once the runtime is merged beside this script.
// ---------------------------------------------------------------------------

class Skip extends Error {}
const assert = (cond, msg) => {
  if (!cond) throw new Error(msg);
};
const sha256 = (s) => createHash("sha256").update(s).digest("hex");

const SELFTEST_SCRIPT = `export const meta = {
  name: 'uc-watch-selftest',
  description: 'two sequential labeled agents',
  phases: [{ title: 'selftest' }],
}
phase('selftest')
const first = await agent('Reply with only the token after ANSWER. ANSWER:alpha', { label: 'first', phase: 'selftest' })
const second = await agent('Reply with only the token after ANSWER. ANSWER:beta', { label: 'second', phase: 'selftest' })
return { first, second }
`;

function writeBackend(root, logFile) {
  const js = path.join(root, "scripted-agent-backend.mjs");
  fs.writeFileSync(
    js,
    `// Scripted agent backend (the one test double; see ultracode-watch.mjs selftest header).
import { appendFileSync } from "node:fs";
import { createHash } from "node:crypto";
const argv = process.argv.slice(2);
const i = argv.indexOf("--prompt");
const prompt = i >= 0 ? String(argv[i + 1] ?? "") : "";
const all = [...prompt.matchAll(/ANSWER:([A-Za-z0-9_-]+)/g)];
const response = all.length ? all[all.length - 1][1] : "ok";
const h = createHash("sha256").update(prompt).digest("hex").slice(0, 16);
appendFileSync(${JSON.stringify(logFile)}, JSON.stringify({ response, argv: argv.filter((a) => a !== prompt) }) + "\\n");
process.stdout.write(JSON.stringify({ sessionId: "scripted-" + h, traceId: "trace-" + h, response }) + "\\n");
`
  );
  const sh = path.join(root, "scripted-agent-backend");
  fs.writeFileSync(sh, `#!/bin/sh\nexec ${JSON.stringify(process.execPath)} ${JSON.stringify(js)} "$@"\n`);
  fs.chmodSync(sh, 0o755);
  return sh;
}

async function selftest() {
  const root = fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(), "ultracode-watch-selftest-")));
  const runtime = path.resolve(process.env.ULTRACODE_RUNTIME || path.join(HERE, "ultracode-run.mjs"));
  const hasRuntime = isFile(runtime);
  const backendLog = path.join(root, "backend-calls.jsonl");
  const backend = writeBackend(root, backendLog);
  const repo = path.join(root, "repo");
  fs.mkdirSync(repo);
  const gi = spawnSync("git", ["init", "-q", repo], { encoding: "utf8" });
  const sleepers = [];
  let caseNo = 0;

  const mkCase = (tag) => {
    const base = path.join(root, `case-${String(++caseNo).padStart(2, "0")}-${tag}`);
    const ch = path.join(base, "claude");
    const uh = path.join(base, "zcode-ultracode");
    fs.mkdirSync(path.join(ch, "workflow-handoff"), { recursive: true });
    fs.mkdirSync(path.join(ch, "sessions"), { recursive: true });
    fs.mkdirSync(path.join(ch, "projects", "-selftest-proj"), { recursive: true });
    const env = {
      ...process.env,
      ULTRACODE_CLAUDE_HOME: ch,
      ULTRACODE_HOME: uh,
      ULTRACODE_RUNTIME: runtime,
      ULTRACODE_AGENT_CMD: backend,
      ULTRACODE_STALE_MINUTES: "45",
      ULTRACODE_DEAD_GRACE_MIN: "2",
    };
    return { base, ch, uh, env, c: config(env) };
  };

  const setMtime = (files, minutesAgo) => {
    const t = new Date(Date.now() - minutesAgo * 60000);
    for (const f of files) fs.utimesSync(f, t, t);
  };

  // Claude-side artifacts of one launched run, exactly as SKILL.md section 1 lays them out.
  const addRun = (k, runId, o = {}) => {
    const { sessionId, staleMin = 10, done = ["first"], status = "launched" } = o;
    const proj = path.join(k.ch, "projects", "-selftest-proj");
    const tdir = path.join(proj, sessionId, "subagents", "workflows", runId);
    fs.mkdirSync(tdir, { recursive: true });
    const lines = [{ type: "launched" }];
    done.forEach((label, i) => {
      const key = `v2:${sha256(`${runId}/${label}`)}`;
      lines.push({ type: "started", key, agentId: `a${i}`, label, phase: "selftest" });
      lines.push({ type: "result", key, agentId: `a${i}`, result: i === 0 ? "from-claude" : "from-claude-2" });
    });
    const jf = path.join(tdir, "journal.jsonl");
    fs.writeFileSync(jf, lines.map((l) => JSON.stringify(l)).join("\n") + "\n");
    const af = path.join(tdir, "agent-a0.jsonl");
    fs.writeFileSync(af, JSON.stringify({ type: "user", message: "first" }) + "\n");
    setMtime([jf, af], staleMin);
    const sdir = path.join(proj, sessionId, "workflows", "scripts");
    fs.mkdirSync(sdir, { recursive: true });
    const scriptFile = path.join(sdir, `uc-watch-selftest-${runId}.js`);
    fs.writeFileSync(scriptFile, SELFTEST_SCRIPT);
    const rec = {
      runId,
      scriptFile,
      transcriptDir: tdir,
      cwd: repo,
      sessionId,
      launchedAt: iso(Date.now() - (staleMin + 1) * 60000),
      status,
      owner: "claude",
      workflowName: "uc-watch-selftest",
    };
    if ("argsNote" in o) Object.assign(rec, { args: null, argsNote: o.argsNote });
    else rec.args = o.args ?? { topic: "selftest" };
    fs.writeFileSync(path.join(k.ch, "workflow-handoff", `${runId}.json`), JSON.stringify(rec, null, 1));
    return { rec, jf, af };
  };

  const liveSession = async (k, sessionId, procStartOverride) => {
    const child = spawn("sleep", ["600"], { stdio: "ignore" });
    sleepers.push(child);
    await new Promise((r, j) => {
      child.once("spawn", r);
      child.once("error", j);
    });
    const ps = spawnSync("/bin/sh", ["-c", `TZ=UTC LC_ALL=C ps -o lstart= -p ${child.pid}`], {
      encoding: "utf8",
    });
    const procStart = procStartOverride ?? ps.stdout.trim();
    assert(procStart, `could not read lstart for sleep pid ${child.pid}`);
    fs.writeFileSync(
      path.join(k.ch, "sessions", `${child.pid}.json`),
      JSON.stringify({ pid: child.pid, sessionId, cwd: repo, procStart, kind: "interactive" })
    );
    return { child, pid: child.pid, procStart };
  };
  const kill = async (child) => {
    if (child.exitCode !== null || child.signalCode !== null) return;
    const exited = new Promise((r) => child.once("exit", r));
    child.kill("SIGKILL");
    await exited;
  };
  const writeSessionTranscript = (k, sessionId, lines) =>
    fs.writeFileSync(
      path.join(k.ch, "projects", "-selftest-proj", `${sessionId}.jsonl`),
      lines.map((l) => JSON.stringify(l)).join("\n") + "\n"
    );

  const cli = (k, ...args) => {
    const r = spawnSync(process.execPath, [SELF, ...args], {
      env: k.env,
      encoding: "utf8",
      timeout: 300000,
      maxBuffer: 64 << 20,
    });
    return { code: r.status, out: r.stdout ?? "", err: r.stderr ?? "" };
  };
  const scanJson = (k) => {
    const r = cli(k, "scan", "--json");
    assert(r.code === 0, `scan exit ${r.code}: ${r.err.slice(-400)}`);
    return Object.fromEntries(JSON.parse(r.out).records.map((x) => [x.runId, x]));
  };
  const record = (k, runId) => readJson(path.join(k.ch, "workflow-handoff", `${runId}.json`));
  const lockOf = (k, runId) => path.join(k.ch, "workflow-handoff", `${runId}.takeover`);
  const backendCalls = () =>
    isFile(backendLog)
      ? fs.readFileSync(backendLog, "utf8").trim().split("\n").filter(Boolean).map((l) => JSON.parse(l))
      : [];

  const cases = [
    ["liveness: live pid with matching procStart is alive", false, async () => {
      const k = mkCase("live");
      const s = await liveSession(k, "sess-live");
      const l = sessionLiveness(k.c, "sess-live");
      assert(l.alive === true && l.pid === s.pid && l.why === "alive", `got ${JSON.stringify(l)}`);
      assert(procStartMatches(s.pid, s.procStart) === true, "procStart did not match its own lstart");
      await kill(s.child);
    }],
    ["liveness: pid reuse (procStart mismatch) is dead", false, async () => {
      const k = mkCase("reuse");
      const s = await liveSession(k, "sess-reuse", "Thu Jan 1 00:00:00 1970");
      const l = sessionLiveness(k.c, "sess-reuse");
      assert(l.alive === false && l.why === `${s.pid}:pid-reused`, `got ${JSON.stringify(l)}`);
      await kill(s.child);
    }],
    ["liveness: killed pid is dead; unknown session is dead", false, async () => {
      const k = mkCase("dead");
      const s = await liveSession(k, "sess-dead");
      assert(sessionLiveness(k.c, "sess-dead").alive === true, "not alive before kill");
      await kill(s.child);
      const l = sessionLiveness(k.c, "sess-dead");
      assert(l.alive === false && l.why === `${s.pid}:pid-dead`, `got ${JSON.stringify(l)}`);
      const u = sessionLiveness(k.c, "sess-never-registered");
      assert(u.alive === false && u.why === "no-session-file", `got ${JSON.stringify(u)}`);
    }],
    ["scan: dead session -- stale >= 2m is a candidate, fresh is not", false, async () => {
      const k = mkCase("dead-stale-fresh");
      const s = await liveSession(k, "sess-d");
      await kill(s.child);
      addRun(k, "wf_st-stale-01", { sessionId: "sess-d", staleMin: 10 });
      addRun(k, "wf_st-fresh-01", { sessionId: "sess-d", staleMin: 0 });
      const rows = scanJson(k);
      const st = rows["wf_st-stale-01"];
      const fr = rows["wf_st-fresh-01"];
      assert(st.candidate === true && /SESSION_DEAD\(/.test(st.reason), `stale: ${JSON.stringify(st)}`);
      assert(st.staleMinutes >= 9.9, `stale minutes ${st.staleMinutes}`);
      assert(fr.candidate === false && fr.eligible === false, `fresh: ${JSON.stringify(fr)}`);
      assert(/SESSION_DEAD_BUT_FRESH/.test(fr.reason), `fresh reason: ${fr.reason}`);
      if (hasRuntime) assert(st.eligible === true && st.liveAgentsNeeded > 0, `stale: ${st.reason}`);
      else assert(st.eligible === false && /RUNTIME_ABSENT/.test(st.reason), `stale: ${st.reason}`);
      const text = cli(k, "scan");
      assert(text.code === 0, `scan text exit ${text.code}`);
      assert(
        /^wf_st-fresh-01\teligible=false\tSESSION_DEAD_BUT_FRESH/m.test(text.out),
        `text scan line missing: ${text.out}`
      );
    }],
    ["scan: alive session needs stale >= 45m AND an API-failure marker", false, async () => {
      const k = mkCase("alive");
      const s1 = await liveSession(k, "sess-a1");
      const s2 = await liveSession(k, "sess-a2");
      writeSessionTranscript(k, "sess-a1", [
        { type: "user", message: "go" },
        {
          type: "assistant",
          isApiErrorMessage: true,
          message: { content: [{ type: "text", text: 'API Error: 529 {"type":"error","error":{"type":"overloaded_error"}}' }] },
        },
      ]);
      // false-positive bait: 503 inside a duration, a timestamp and an id is not a failure marker
      writeSessionTranscript(k, "sess-a2", [
        { type: "assistant", uuid: "a503b2c1-0503-4503-8503-503503503503", durationMs: 503, timestamp: "2026-09-22T22:56:55.503Z", message: "fine" },
      ]);
      addRun(k, "wf_al-apifail", { sessionId: "sess-a1", staleMin: 60 });
      addRun(k, "wf_al-nomarker", { sessionId: "sess-a2", staleMin: 60 });
      addRun(k, "wf_al-progress", { sessionId: "sess-a1", staleMin: 10 });
      const rows = scanJson(k);
      const a = rows["wf_al-apifail"];
      assert(a.candidate === true && a.session.alive === true, `apifail: ${JSON.stringify(a)}`);
      assert(a.apiFailureMarker && /SESSION_ALIVE_API_FAILURE/.test(a.reason), `apifail: ${a.reason}`);
      const b = rows["wf_al-nomarker"];
      assert(b.candidate === false && /SESSION_ALIVE_STALE_NO_API_FAILURE/.test(b.reason), `nomarker: ${b.reason}`);
      const p = rows["wf_al-progress"];
      assert(p.candidate === false && /SESSION_ALIVE_PROGRESSING/.test(p.reason), `progress: ${p.reason}`);
      await kill(s1.child);
      await kill(s2.child);
    }],
    ["scan: completed and taken_over records are not processed", false, async () => {
      const k = mkCase("closed");
      addRun(k, "wf_cl-done", { sessionId: "sess-c", staleMin: 30, status: "completed" });
      addRun(k, "wf_cl-taken", { sessionId: "sess-c", staleMin: 30, status: "taken_over" });
      addRun(k, "wf_cl-open", { sessionId: "sess-c", staleMin: 30 });
      const rows = scanJson(k);
      assert(!("wf_cl-done" in rows) && !("wf_cl-taken" in rows), `closed rows listed: ${Object.keys(rows)}`);
      assert("wf_cl-open" in rows, "open row missing");
    }],
    ["takeover: args null + argsNote refuses typed ARGS_UNAVAILABLE, no lock", false, async () => {
      const k = mkCase("args-unavailable");
      addRun(k, "wf_ar-none", { sessionId: "sess-x", staleMin: 30, argsNote: "args exceeded hook payload; not captured" });
      const r = cli(k, "takeover", "wf_ar-none");
      assert(r.code === 2, `exit ${r.code}: ${r.out}${r.err}`);
      const j = JSON.parse(r.out);
      assert(j.outcome === "REFUSED" && j.code === "ARGS_UNAVAILABLE", `got ${r.out}`);
      assert(!fs.existsSync(lockOf(k, "wf_ar-none")), "lock written despite refusal");
      assert(record(k, "wf_ar-none").status === "launched", "record status changed");
      const row = scanJson(k)["wf_ar-none"];
      assert(row.eligible === false && /ARGS_UNAVAILABLE/.test(row.reason), `scan: ${row.reason}`);
    }],
    ["takeover: an existing lock refuses typed LOCKED", false, async () => {
      const k = mkCase("locked");
      addRun(k, "wf_lk-held", { sessionId: "sess-y", staleMin: 30 });
      fs.writeFileSync(lockOf(k, "wf_lk-held"), JSON.stringify({ owner: "zcode", pid: 1, at: iso() }));
      const r = cli(k, "takeover", "wf_lk-held");
      assert(r.code === 2 && JSON.parse(r.out).code === "LOCKED", `exit ${r.code}: ${r.out}`);
      assert(record(k, "wf_lk-held").status === "launched", "record status changed");
      const row = scanJson(k)["wf_lk-held"];
      assert(row.eligible === false && /^LOCKED/.test(row.reason), `scan: ${row.reason}`);
    }],
    ["lock: 8 concurrent O_EXCL acquirers, exactly one wins", false, async () => {
      const k = mkCase("lock-race");
      const go = path.join(k.base, "go");
      const code = `
import { acquireLock, config } from ${JSON.stringify(pathToFileURL(SELF).href)};
import { existsSync } from "node:fs";
while (!existsSync(${JSON.stringify(go)})) await new Promise((r) => setTimeout(r, 2));
const r = acquireLock(config(process.env), "wf_race-01");
process.stdout.write(JSON.stringify({ acquired: r.acquired, pid: process.pid }));
`;
      const racers = Array.from({ length: 8 }, () =>
        new Promise((resolve) => {
          const child = spawn(process.execPath, ["--input-type=module", "-e", code], { env: k.env });
          let out = "";
          let err = "";
          child.stdout.on("data", (d) => (out += d));
          child.stderr.on("data", (d) => (err += d));
          child.on("close", (c) => resolve({ c, out, err }));
        })
      );
      await new Promise((r) => setTimeout(r, 300));
      fs.writeFileSync(go, "");
      const res = await Promise.all(racers);
      for (const r of res) assert(r.c === 0, `racer exit ${r.c}: ${r.err.slice(-300)}`);
      const wins = res.map((r) => JSON.parse(r.out)).filter((r) => r.acquired);
      assert(wins.length === 1, `${wins.length} winners`);
      const held = readJson(lockOf(k, "wf_race-01"));
      assert(held.owner === "zcode" && held.pid === wins[0].pid && held.at, `lock body ${JSON.stringify(held)}`);
    }],
    ["print: launchd plist passes plutil -lint", false, async () => {
      const k = mkCase("print");
      const plu = spawnSync("/bin/sh", ["-c", "command -v plutil"], { encoding: "utf8" });
      if (plu.status !== 0) throw new Skip("plutil not on PATH (non-macOS host)");
      const r = cli(k, "print");
      assert(r.code === 0, `print exit ${r.code}`);
      const lint = spawnSync("plutil", ["-lint", "-"], { input: r.out, encoding: "utf8" });
      assert(lint.status === 0 && /OK/.test(lint.stdout), `plutil: ${lint.stdout}${lint.stderr}`);
      for (const needle of [
        `<string>${LABEL}</string>`,
        `<integer>${START_INTERVAL}</integer>`,
        `<string>${path.join(k.uh, "bin", "ultracode-watch.mjs")}</string>`,
        "<string>run-once</string>",
        "<string>--auto</string>",
        `<string>${k.ch}</string>`,
      ]) assert(r.out.includes(needle), `plist lacks ${needle}`);
    }],
    ["run-once without --auto takes no action", false, async () => {
      const k = mkCase("run-once-report");
      addRun(k, "wf_ro-report", { sessionId: "sess-r", staleMin: 30 });
      const r = cli(k, "run-once");
      assert(r.code === 0, `exit ${r.code}: ${r.err.slice(-300)}`);
      const j = JSON.parse(r.out);
      assert(j.auto === false && j.actions.every((a) => a.action === "would-take-over"), r.out);
      assert(!fs.existsSync(lockOf(k, "wf_ro-report")), "lock written without --auto");
      assert(record(k, "wf_ro-report").status === "launched", "record changed without --auto");
    }],
    ["scan+runtime: complete journal -> record completed, result.json written", true, async () => {
      const k = mkCase("rt-complete");
      addRun(k, "wf_rt-complete", { sessionId: "sess-rc", staleMin: 30, done: ["first", "second"] });
      const before = backendCalls().length;
      const row = scanJson(k)["wf_rt-complete"];
      assert(row.liveAgentsNeeded === 0 && row.status === "completed", `row ${JSON.stringify(row)}`);
      const rec = record(k, "wf_rt-complete");
      assert(rec.status === "completed" && isFile(rec.resultFile), `record ${JSON.stringify(rec)}`);
      assert(rec.resultFile === path.join(k.uh, "runs", "wf_rt-complete", "result.json"), rec.resultFile);
      assert(backendCalls().length === before, "a dry-run spawned a live agent");
    }],
    ["takeover+runtime: 6 concurrent takeovers past one barrier, exactly one wins and completes", true, async () => {
      const k = mkCase("rt-takeover");
      addRun(k, "wf_rt-take", { sessionId: "sess-rt", staleMin: 30 });
      const before = backendCalls().length;
      const go = path.join(k.base, "go");
      // every racer passes the lock pre-check together, so only O_EXCL can pick the winner
      const code = `
import { takeover, config } from ${JSON.stringify(pathToFileURL(SELF).href)};
import { existsSync } from "node:fs";
while (!existsSync(${JSON.stringify(go)})) await new Promise((r) => setTimeout(r, 2));
const r = await takeover(config(process.env), "wf_rt-take");
process.stdout.write(JSON.stringify({ ...r, pid: process.pid }));
`;
      const racers = Array.from({ length: 6 }, () =>
        new Promise((resolve) => {
          const child = spawn(process.execPath, ["--input-type=module", "-e", code], { env: k.env });
          let out = "";
          let err = "";
          child.stdout.on("data", (d) => (out += d));
          child.stderr.on("data", (d) => (err += d));
          child.on("close", (c) => resolve({ c, out, err }));
        })
      );
      await new Promise((r) => setTimeout(r, 400));
      fs.writeFileSync(go, "");
      const res = await Promise.all(racers);
      for (const r of res) assert(r.c === 0 && r.out, `racer exit ${r.c}: ${r.err.slice(-300)}`);
      const js = res.map((r) => JSON.parse(r.out));
      const won = js.filter((j) => j.outcome === "completed");
      const lost = js.filter((j) => j.outcome === "REFUSED" && j.code === "LOCKED");
      assert(won.length === 1 && lost.length === 5, `outcomes ${js.map((j) => j.outcome + ":" + (j.code ?? j.exit))}`);
      const w = won[0];
      assert(w.runDir === path.join(k.uh, "runs", "wf_rt-take"), `winner ${JSON.stringify(w)}`);
      const rec = record(k, "wf_rt-take");
      assert(rec.status === "completed" && rec.owner === "zcode" && rec.takeover.runDir === w.runDir, JSON.stringify(rec));
      assert(readJson(lockOf(k, "wf_rt-take")).pid === w.pid, "lock pid is not the winner's");
      const result = fs.readFileSync(path.join(w.runDir, "result.json"), "utf8");
      assert(result.includes("from-claude") && result.includes("beta"), `result.json ${result}`);
      const calls = backendCalls().slice(before);
      assert(calls.length >= 1 && calls.every((c) => c.response !== "alpha"), `backend calls ${JSON.stringify(calls)}`);
      const again = cli(k, "takeover", "wf_rt-take");
      assert(again.code === 2 && JSON.parse(again.out).code === "LOCKED", `late CLI takeover: ${again.out}`);
    }],
    ["takeover+runtime: CLI takeover exits 0 and records the zcode run dir", true, async () => {
      const k = mkCase("rt-cli");
      addRun(k, "wf_rt-cli", { sessionId: "sess-cli", staleMin: 30, args: "free-text prompt args" });
      const r = cli(k, "takeover", "wf_rt-cli");
      assert(r.code === 0, `exit ${r.code}: ${r.out} ${r.err.slice(-300)}`);
      const j = JSON.parse(r.out);
      const rec = record(k, "wf_rt-cli");
      assert(j.outcome === "completed" && rec.status === "completed" && rec.takeover.exit === 0, `${r.out} ${JSON.stringify(rec)}`);
      assert(rec.resultFile === path.join(k.uh, "runs", "wf_rt-cli", "result.json") && isFile(rec.resultFile), rec.resultFile);
      const argsFile = path.join(k.uh, "takeovers", "wf_rt-cli", "args.json");
      assert(JSON.parse(fs.readFileSync(argsFile, "utf8")) === "free-text prompt args", "args file mismatch");
    }],
    ["run-once --auto + runtime: takes over every eligible run serially", true, async () => {
      const k = mkCase("rt-auto");
      addRun(k, "wf_au-one", { sessionId: "sess-au", staleMin: 30 });
      addRun(k, "wf_au-two", { sessionId: "sess-au", staleMin: 30 });
      addRun(k, "wf_au-fresh", { sessionId: "sess-au", staleMin: 0 });
      const r = cli(k, "run-once", "--auto");
      assert(r.code === 0, `exit ${r.code}: ${r.err.slice(-400)}`);
      const j = JSON.parse(r.out);
      const took = j.actions.map((x) => `${x.runId}:${x.outcome}`).sort();
      assert(JSON.stringify(took) === JSON.stringify(["wf_au-one:completed", "wf_au-two:completed"]), `actions ${took}`);
      assert(record(k, "wf_au-one").status === "completed" && record(k, "wf_au-two").status === "completed", "not completed");
      assert(record(k, "wf_au-fresh").status === "launched" && !fs.existsSync(lockOf(k, "wf_au-fresh")), "fresh touched");
    }],
  ];

  let pass = 0;
  let fail = 0;
  let skip = 0;
  console.log(`selftest root ${root}`);
  console.log(`runtime ${runtime} (${hasRuntime ? "present" : "ABSENT"}); git init ${gi.status === 0 ? "ok" : "failed"}`);
  try {
    for (const [name, needsRuntime, fn] of cases) {
      if (needsRuntime && !hasRuntime) {
        console.log(`SKIP ${name}: runtime absent at ${runtime} (set ULTRACODE_RUNTIME; rerun at integration)`);
        skip++;
        continue;
      }
      try {
        await fn();
        console.log(`PASS ${name}`);
        pass++;
      } catch (e) {
        if (e instanceof Skip) {
          console.log(`SKIP ${name}: ${e.message}`);
          skip++;
        } else {
          console.log(`FAIL ${name}: ${e.message}`);
          fail++;
        }
      }
    }
  } finally {
    for (const s of sleepers) await kill(s);
    if (!fail && !process.env.ULTRACODE_SELFTEST_KEEP) fs.rmSync(root, { recursive: true, force: true });
  }
  console.log(`selftest: ${pass} passed, ${fail} failed, ${skip} skipped${fail ? ` (kept ${root})` : ""}`);
  return fail ? 1 : 0;
}

// ---------------------------------------------------------------------------
// CLI
// ---------------------------------------------------------------------------

const USAGE = `usage: ultracode-watch.mjs <command>
  scan [--json]        classify open handoff records (runId, eligible, reason)
  takeover <runId>     lock and resume one run under ZCode
  run-once [--auto]    scan; --auto takes over every eligible run serially
  print                print the launchd plist (${LABEL})
  install | uninstall  bootstrap / boot out the launchd agent
  status               launchd + handoff summary
  selftest             real-process qualification
`;

async function main(argv) {
  const [cmd, ...rest] = argv;
  const c = config();
  const emit = (o) => process.stdout.write(JSON.stringify(o, null, 1) + "\n");
  switch (cmd) {
    case "scan": {
      const rows = scan(c);
      if (rest.includes("--json")) emit({ at: iso(), claudeHome: c.claudeHome, records: rows });
      else for (const r of rows) process.stdout.write(`${r.runId}\teligible=${r.eligible}\t${r.reason}\n`);
      return 0;
    }
    case "takeover": {
      if (!rest[0]) {
        process.stderr.write(USAGE);
        return 64;
      }
      const r = await takeover(c, rest[0]);
      process.stdout.write(JSON.stringify(r) + "\n");
      return r.outcome === "completed" ? 0 : r.outcome === "REFUSED" ? 2 : 1;
    }
    case "run-once": {
      const r = await runOnce(c, rest.includes("--auto"));
      process.stdout.write(JSON.stringify(r) + "\n");
      return 0;
    }
    case "print":
      process.stdout.write(plist(c));
      return 0;
    case "install":
    case "uninstall": {
      const r = cmd === "install" ? install(c) : uninstall(c);
      emit(r.out);
      return r.code;
    }
    case "status":
      emit(status(c));
      return 0;
    case "selftest":
      return selftest();
    case undefined:
    case "help":
    case "--help":
      process.stdout.write(USAGE);
      return cmd === undefined ? 64 : 0;
    default:
      process.stderr.write(`unknown command: ${cmd}\n${USAGE}`);
      return 64;
  }
}

const isMain = (() => {
  try {
    return !!process.argv[1] && fs.realpathSync(process.argv[1]) === fs.realpathSync(SELF);
  } catch {
    return false;
  }
})();
if (isMain) {
  main(process.argv.slice(2)).then(
    (code) => {
      process.exitCode = code;
    },
    (e) => {
      process.stderr.write(`ultracode-watch: ${e?.stack ?? e}\n`);
      process.exitCode = 1;
    }
  );
}
