defmodule Xaas.Marketplace.Pack do
  @moduledoc """
  One pack in the ggen-marketplace catalog projection
  (#{Xaas.Marketplace.Catalog.catalog_schema_url()}).

  The marketplace catalog is generated by `scripts/marketplace.py catalog`
  in ggen-marketplace; this resource is the consumer-side projection of one
  `packs` entry. Mirrors the v2 catalog record surface:

    name (primary key/slug), version, digest (sha256:hex), download_url,
    lifecycle_tier, readiness, pack_class, ontology_fingerprint,
    description, deprecated.

  Like `Xaas.Marketplace.Provider`, this resource is also projected onto
  public ontologies by `Xaas.Semantics.Registry`.

  Uses `Ash.DataLayer.Ets` — the catalog is regenerated wholesale from the
  marketplace source of truth on every ingest, so durable Postgres storage
  would buy nothing; the file IS the store, this is a queryable projection.
  """
  use Xaas.Resource,
    otp_app: :xaas,
    domain: Xaas.Marketplace,
    data_layer: Ash.DataLayer.Ets,
    extensions: [AshJsonApi.Resource, AshGraphql.Resource]

  ets do
    private?(true)
  end

  attributes do
    attribute :name, :string do
      allow_nil?(false)
      public?(true)
      primary_key?(true)
      writable?(true)
    end

    attribute(:version, :string, allow_nil?: false, public?: true)
    attribute(:digest, :string, allow_nil?: false, public?: true)
    attribute(:download_url, :string, allow_nil?: false, public?: true)

    attribute(:lifecycle_tier, :string,
      allow_nil?: false,
      public?: true,
      description: "Denormalized from the v2 catalog `lifecycle`/`tier` field."
    )

    attribute :readiness, :string do
      allow_nil?(false)
      public?(true)

      description(
        "Denormalized from the v2 catalog `readiness` map: the sorted, " <>
          "'+'-joined list of readiness flags that are true (e.g. \"gates\", " <>
          "\"gates+readiness+verify+witnesses\")."
      )
    end

    attribute(:pack_class, :string, public?: true)
    attribute(:ontology_fingerprint, :string, public?: true)
    attribute(:description, :string, allow_nil?: false, public?: true)
    attribute(:deprecated, :boolean, allow_nil?: false, public?: true, default: false)

    create_timestamp(:inserted_at)
    update_timestamp(:updated_at)
  end

  graphql do
    type(:marketplace_pack)
  end

  json_api do
    type("marketplace_pack")

    routes do
      base("/marketplace/packs")
      get(:get_by_id)
      index(:read)
    end
  end

  identities do
    identity(:unique_name, [:name], pre_check_with: Ash.DataLayer.Ets)
  end

  actions do
    defaults([:read, :destroy])

    # AshJsonApi's `get` route feeds the path segment to the action as an
    # `:id` input (the plain `:read` default declares no such argument, so
    # `GET /api/marketplace/packs/:id` on `:read` raises a real
    # `NoSuchInput` -- same failure class as Xaas.Library.Book's
    # `get_by_id`, caught via a real HTTP court, not inspection).
    read :get_by_id do
      argument(:id, :string, allow_nil?: false)
      get?(true)
      filter(expr(name == ^arg(:id)))
    end

    create :create do
      accept([
        :name,
        :version,
        :digest,
        :download_url,
        :lifecycle_tier,
        :readiness,
        :pack_class,
        :ontology_fingerprint,
        :description,
        :deprecated
      ])
    end

    update :update do
      accept([
        :version,
        :digest,
        :download_url,
        :lifecycle_tier,
        :readiness,
        :pack_class,
        :ontology_fingerprint,
        :description,
        :deprecated
      ])

      require_atomic?(false)
    end
  end
end
