defmodule XaasWeb.MarketplacePackJsonApiTest do
  @moduledoc """
  Real Chicago-style court: real Phoenix HTTP GET against the real
  `/api/marketplace/packs` JSON:API route generated by
  `Xaas.Marketplace.Pack`'s `json_api do routes do ... end end` block,
  gated by the real `XaasWeb.Plugs.RequireInternalApiToken` plug on the
  `/api` forward. The fixture is the real `Xaas.Marketplace.Catalog.ingest/1`
  over real generated catalog records. No mocks.
  """
  use ExUnit.Case, async: false
  use Phoenix.ConnTest

  alias Xaas.Marketplace.Catalog
  alias Xaas.Marketplace.Pack

  @endpoint XaasWeb.Endpoint

  setup do
    wipe()

    on_exit(fn ->
      wipe()
    end)

    :ok
  end

  defp wipe do
    Pack |> Ash.bulk_destroy!(:destroy, %{}, authorize?: false)
  end

  defp json_conn(conn) do
    conn
    |> put_req_header("authorization", "Bearer " <> System.fetch_env!("INTERNAL_API_TOKEN"))
    |> put_req_header("accept", "application/vnd.api+json")
  end

  defp catalog(packs), do: %{"schema" => Catalog.catalog_schema_url(), "packs" => packs}

  defp pack_record(suffix) do
    %{
      "name" => "pack-json-api-#{suffix}",
      "version" => "1.2.3",
      "digest" => "sha256:" <> String.duplicate("ab", 32),
      "download_url" => "https://example.com/packs/#{suffix}.tar.gz",
      "lifecycle_tier" => "stable",
      "readiness" => "gates+verify",
      "pack_class" => "CapabilityPack",
      "ontology_fingerprint" => "fp-#{suffix}",
      "description" => "JSON:API surface court pack #{suffix}",
      "deprecated" => false
    }
  end

  test "GET /api/marketplace/packs returns the ingested packs" do
    assert {:ok, 2} = Catalog.ingest(catalog([pack_record("a"), pack_record("b")]))

    resp =
      Phoenix.ConnTest.build_conn()
      |> json_conn()
      |> get("/api/marketplace/packs")

    assert resp.status == 200

    body = json_response(resp, 200)
    assert body["data"] |> length() == 2

    names = Enum.map(body["data"], & &1["id"]) |> Enum.sort()
    assert names == ["pack-json-api-a", "pack-json-api-b"]

    first = Enum.find(body["data"], &(&1["id"] == "pack-json-api-a"))
    assert first["type"] == "marketplace_pack"
    assert first["attributes"]["version"] == "1.2.3"
    assert first["attributes"]["pack_class"] == "CapabilityPack"
    assert first["attributes"]["deprecated"] == false
  end

  test "GET /api/marketplace/packs without the internal API token is rejected" do
    Catalog.ingest(catalog([pack_record("noauth")]))

    resp =
      Phoenix.ConnTest.build_conn()
      |> put_req_header("accept", "application/vnd.api+json")
      |> get("/api/marketplace/packs")

    assert resp.status in [401, 403, 503]
  end

  test "GET /api/marketplace/packs/:id returns one ingested pack" do
    Catalog.ingest(catalog([pack_record("solo")]))

    resp =
      Phoenix.ConnTest.build_conn()
      |> json_conn()
      |> get("/api/marketplace/packs/pack-json-api-solo")

    assert resp.status == 200

    body = json_response(resp, 200)
    assert body["data"]["id"] == "pack-json-api-solo"
    assert body["data"]["type"] == "marketplace_pack"
    assert body["data"]["attributes"]["readiness"] == "gates+verify"
  end
end
