[project]
name = "xaas-r80-forced-top25-consumer"

[ontology]
source = "ontology.ttl"

[packs]
forced-top25-admissibility-factory-pack = { git = "https://github.com/seanchatmangpt/ggen-marketplace.git", version = "9bba137bf2ceb43c4694ac8c580c459782e09643", subdir = "packs/forced-top25-admissibility-factory-pack" }

[templates]
dir = "templates"
