[project]
name = "xaas-r80-forced-top25-consumer"

[ontology]
source = "ontology.ttl"

[packs]
forced-top25-admissibility-factory-pack = { git = "https://github.com/seanchatmangpt/ggen-marketplace.git", version = "629f8276852c2248451b8b77d29e76d5e83b4533", subdir = "packs/forced-top25-admissibility-factory-pack" }

[templates]
dir = "templates"
