defmodule Xaas.Governance.InternalApiTokenAuth do
  @moduledoc """
  Real, plain (non-DSL) entry points onto `Xaas.Governance.InternalApiToken`
  for `:issue`/`:revoke`/verification. Kept as a separate module from the
  resource itself -- not stylistic preference: an Ash resource's own struct
  (`%Xaas.Governance.InternalApiToken{}`) is generated by a DSL transformer
  that only finishes running after the resource module itself is fully
  compiled, so a function defined *inside* that same module cannot pattern
  -match `%__MODULE__{}` against it (confirmed by a real, reproduced
  `mix compile` failure this session: "cannot expand struct ...
  Xaas.Governance.InternalApiToken ... cyclic module usage" -- fixed by
  moving these functions here, into a module that references the resource
  from outside its own compilation unit, the same way every other consumer
  in this codebase -- tests, controllers, mix tasks -- already does).

  Every call here is `authorize?: false` by design (see
  `Xaas.Governance.InternalApiToken`'s own moduledoc: this resource has no
  actor-authorized path at all, HTTP or otherwise -- `issue/2` and
  `revoke/1` are operator/mix-task-only, and `verify/1` is exactly how a
  request establishes any authority in the first place, so it cannot itself
  require authority to run).
  """

  alias Xaas.Accounts.Org
  alias Xaas.Governance.InternalApiToken

  @prefix "iat_live_"
  @display_prefix_len 12

  @doc "The raw-token prefix minted tokens are given (`\"iat_live_\"`)."
  def prefix, do: @prefix

  @doc "How many raw-token characters are kept as the stored, displayable `token_prefix`."
  def display_prefix_len, do: @display_prefix_len

  @doc """
  Real token minting: generates a raw bearer token, persists its hash via
  the `:issue` action (`authorize?: false` -- operator/system context, no
  actor exists yet), and returns the raw token exactly once (via
  `Ash.Resource.get_metadata/2`, the ephemeral carrier `Xaas.Governance.
  Changes.GenerateInternalApiToken` attaches to the result). Never stored,
  never re-derivable after this call returns.

  `org` (real, optional, added this pass): `nil` (default) mints an
  internal/admin-tier token, unchanged from before this pass. Passed a real
  `Xaas.Accounts.Org` struct, its own `slug`, or its own `id`, resolves the
  real org and stores its `id` as this token's `org_id` -- the fact
  `XaasWeb.Plugs.RequireInternalApiToken` later loads back into
  `conn.assigns[:current_org]` for the org-scoped execution-fabric surface.
  An org identifier that resolves to no real `Org` row is a real, typed
  error (`{:error, {:org_not_found, org}}`), never a silently org-less
  token.
  """
  @spec issue(String.t(), DateTime.t() | nil, String.t() | Org.t() | nil) ::
          {:ok, raw_token :: String.t(), InternalApiToken.t()} | {:error, term()}
  def issue(created_by, expires_at \\ nil, org \\ nil) when is_binary(created_by) do
    with {:ok, org_id} <- resolve_org_id(org) do
      InternalApiToken
      |> Ash.Changeset.for_create(
        :issue,
        %{created_by: created_by, expires_at: expires_at, org_id: org_id},
        authorize?: false
      )
      |> Ash.create()
      |> case do
        {:ok, token} -> {:ok, Ash.Resource.get_metadata(token, :raw_token), token}
        {:error, error} -> {:error, error}
      end
    end
  end

  defp resolve_org_id(nil), do: {:ok, nil}
  defp resolve_org_id(%Org{id: id}), do: {:ok, id}

  defp resolve_org_id(org) when is_binary(org) do
    case Ash.get(Org, [slug: org], authorize?: false) do
      {:ok, %Org{id: id}} ->
        {:ok, id}

      {:error, _} ->
        # Real fallback: the identifier may already be the org's own real
        # `id` (an operator scripting against a known uuid, not a slug)
        # rather than its slug.
        case Ash.get(Org, org, authorize?: false) do
          {:ok, %Org{id: id}} -> {:ok, id}
          {:error, _} -> {:error, {:org_not_found, org}}
        end
    end
  end

  @doc "Real revocation: sets `revoked_at`, fails if already revoked."
  @spec revoke(InternalApiToken.t()) :: {:ok, InternalApiToken.t()} | {:error, term()}
  def revoke(%InternalApiToken{} = token) do
    token
    |> Ash.Changeset.for_update(:revoke, %{}, authorize?: false)
    |> Ash.update()
  end

  @doc """
  Real, fail-closed verification called by `XaasWeb.Plugs.
  RequireInternalApiToken` on every `/internal-api/*` request. Hashes the
  presented raw token, looks up the matching row by hash
  (`authorize?: false`), and returns `{:ok, token}` only when a matching
  row exists AND is neither revoked nor expired. Every other case (no
  match, revoked, expired, blank input) is `:error` -- the plug's own
  env-var fallback / 401 path takes over from there.
  """
  @spec verify(String.t() | nil) :: {:ok, InternalApiToken.t()} | :error
  def verify(raw_token) when is_binary(raw_token) and byte_size(raw_token) > 0 do
    token_hash = hash(raw_token)

    InternalApiToken
    |> Ash.Query.for_read(:by_hash, %{token_hash: token_hash})
    |> Ash.read_one(authorize?: false)
    |> case do
      {:ok, %InternalApiToken{} = token} ->
        if active?(token), do: {:ok, token}, else: :error

      _ ->
        :error
    end
  end

  def verify(_), do: :error

  defp active?(%InternalApiToken{revoked_at: nil, expires_at: nil}), do: true

  defp active?(%InternalApiToken{revoked_at: nil, expires_at: %DateTime{} = expires_at}) do
    DateTime.compare(expires_at, DateTime.utc_now()) == :gt
  end

  defp active?(%InternalApiToken{}), do: false

  defp hash(raw_token), do: :crypto.hash(:sha256, raw_token) |> Base.encode16(case: :lower)
end
